### ISSUE TITLE
Bug: Ages are all 999 right now

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#1020]
Well, THAT'S not very useful, is it?

It's probably because I'm not in a session at all right now.  It's Thursday and after 4PM so I should be in the Thursday Session, IIRC.  I also have "default to first session" chosen, so maybe I should just be in "Practice", which is my first session.  But, Day is set to &lt;none&gt; for that.  Maybe that's the problem here?  

I don't use sessions right now, but there's something wrong here.

**Comment by mpogue2** [comment]
See also #967.

**Comment by mpogue2** [comment]
The Ages all go to reasonable values when I set the session to something reasonable (like Wednesday).  So, this might indeed be a dup of #967.

**Comment by mpogue2** [comment]
When I come into SquareDesk, none of the Sessions are checked in the menu.  
And, the Ages that I see are not the same as ANY session.  

Here are my current Preferences > Session (don't ask me how it got this way...):

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/404a3896-94d4-4140-b216-f17e3e565f68)

So, what Session am I in, with nothing checked?

**Comment by mpogue2** [comment]
Hmmm....why all these extra columns?  Bug here?

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/4e95e7c9-b599-4234-8fee-cdabfc3e928d)

**Comment by mpogue2** [comment]
Should there be an "end_minutes" column, so that one Afternoon session could be from say 1PM to 3PM and a second Evening session from 6PM to 9:30PM?

I forget -- is the session set at SquareDesk startup time, or at song play time, or?

It certainly seems like I am currently in a Session that is not shown, even though "Default to first session" is selected (I think the first session is "Practice", right?).  Did I mess up my sqlite DB at some point?

**Comment by mpogue2** [comment]
NOTE: Once I manually select a Session in the Session menu, I can't get back to my original session state.  I have to leave and come back in, and then I can see the Ages numbers I am used to....

**Comment by mpogue2** [comment]
Found this by accident!
I think I might have figured out #967 and #1020.  
I just realized that the first 8 items in the sessions DB have a unique and unusual name.

In mainwindow.cpp L1234, we see this:
```
    setCurrentSessionIdReloadSongAgesCheckMenu(
        static_cast<SessionDefaultType>(prefsManager.GetSessionDefault() == SessionDefaultDOW)
        ? songSettings.currentSessionIDByTime() : 1); // on app entry, ages must show current session
    populateMenuSessionOptions();
```
which sets the session to 1, if the user has selected `SessionDefaultPractice` in the Sessions preferences dropdown box.

BUT, row 1 in the sessions table in **my** DB is NOT the first session.  Right now, the first row is "GarbageValueForUniquifier1".

We see this "GarbageValue..." string in songsettings.cpp L1138.  It looks to me like when a session is deleted, it is overwritten by the "GarbageValue..." presumably so that song plays that pointed at that session don't by accident point at some new Session that was not in existence at the time of original playback.

So, the REAL FIX would probably be that if GetSessionDefault() != SessionDefaultDOW, we should scan through the sessions table and find the first row whose "name" field doesn't start with "GarbageValueForUniquifier", and then use THAT session.

Right now, all of my played_on records are going to slot 1, which is "GarbageValueForUniquifier1", not "Practice" as I had expected.

My guess is that nobody saw this problem before, because nobody:
- deleted one or more sessions in the past AND
- tried to use sessions (e.g. Age, Recent) AND
- with the "Default to First Session" checked

@danlyke Does this sound like a reasonable explanation to you?

**Comment by danlyke** [comment]
Yes. I don't think I've ever delete a session.

**Comment by mpogue2** [comment]
@danlyke In the newer databases I've created, I do NOT have all those extra columns.  So, I suspect something went wrong at some point and I got them added, and that bug probably doesn't exist anymore.  I'll delete them from my sessions table, (after making a backup) and see what happens.

**Comment by mpogue2** [comment]
Closing, because this hasn't appeared again (although I haven't deleted any sessions lately).
