### ISSUE TITLE
Feature: new font size choice should persist

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#105]
See #45.  When I choose a new font size it should persist when I open the app the next time.

**Comment by mhkull** [comment]
Absolutely!

**Comment by mpogue2** [comment]
Information: Safari font size choice persists.  Firefox font size choice does not persist.  Interesting...

**Comment by mpogue2** [comment]
Fixed by e3d0e2b784ceec83d8b8e723151a73095d8cc2a9 .
