### ISSUE TITLE
Feature: Replace CallerLab call lists with a more generic HTML-based method

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#107]
The Callerlab lists need some serious love, but they were really a placeholder anyway.  

It would be nice to have a generic way of including information from a "Reference" directory (in the musicDirectory).  .htm, .txt, .doc, .pdf would be nice.  With persistent user-selectable font sizes.

**Comment by danlyke** [comment]
So is it reasonable to pull the "check off the call" mechanism out of my choreography exploratory branch? We could either automatically write the "danceprogram_*.txt" files into the music directory if one didn't exist, or just provide the Callerlab files internally...

**Comment by mpogue2** [comment]
Works for me.  I think they should be internal but copied to somewhere in the music directory, maybe under reference/dance programs ?  That way they could do double duty...

**Comment by danlyke** [comment]
Yeah, I'm kind of thinking that if we don't find them, we create them
from internal arrays. That way the user gets a template and we don't
have special case code to deal with internal vs external.

**Comment by mpogue2** [comment]
I think that would work, but either way the call lists are required.  I'd still rather do them external to the program, so that users can change them more easily.  If not musicDir/reference/danceprograms, then how about the programDir/danceprograms ?  On Mac OS X it's somewhat hidden, but it's more accessible on Win32 and Linux.  Then we can ensure that it's there (in a non-messed-up environment), because we stick it there, and yet it still allows for upgradability by the user with a text editor.

**Comment by danlyke** [comment]
It'd be easy to look for them in multiple places, the program first, then in the music directory, but I like keeping the program space inviolate, and writing files we expect the user to change into the user's space.

I'm thinking "create them if no list exists on the target", that way a caller who doesn't call Advanced can delete the Advanced lists, and no problem.

My only concern is sort order: a1 & a2 come before basic... Trying to figure an elegant solution to that....

**Comment by mpogue2** [comment]
How about '1.a1.txt' and then always pull off a leading '#.' if present before use?

**Comment by danlyke** [comment]
Okay, what else would go in the "reference" directory?

Aaaand: We're already writing to the music directory with the database, but do we want to allow the music directory to be read-only?

Anyway, I yanked out my choreography searching stuff and tossed the rest up in tyhe danlyke branch at 8be0b1033f5ace583a1c5a3a7afcba4ca3f23bcf, the commit message for that kind of tells the tale.

Take a look and see what you think.

**Comment by danlyke** [comment]
So I think we're done here. We may add more stuff to the calls (timing data), but I think that's more related to the choreography management...

**Comment by mpogue2** [comment]
I think we might need to open a new Issue for the Reference Tab idea, that would allow the user to see PDF, HTM, and .TXT format stuff in a separate tab.  What you've done for the call lists is great, and so that part is done.  Reference Tab would be a new feature...
