### ISSUE TITLE
cannot run SquareDesk 1.0.7 on M3 MacBookAir

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#1076]
I am the owner of a MacBook Air M3 now. (yeah!)

Bad news: I cannot run SquareDesk on it. (so far)

I downloaded SquareDesk_1.0.7.dmg without the x86 in the filename from the google drive SquareDeskReleases folder, dropped it in the program folder. 
I tried to open it from the program folder by right clicking and selecting "open" from the context menu. I tried several times.

I get a warning that says: 'file is damaged and cannot be opened. It is recommended to put it into the waste bin.'

<img width="298" alt="Bildschirmfoto 2024-04-24 um 14 28 47" src="https://github.com/mpogue2/SquareDesk/assets/128936259/25aeb59b-0253-4732-a0f8-88fbe629c44b">

I put it in the exception list at system settings / security / developer toolbox.
I tried to delete the file and reinstalled it. tried to download it again. that does not help

Do you have any helpful hint for me?

**Comment by mpogue2** [comment]
Thanks for reporting this.  This is a consequence of Apple's security policies, and the fact that I am not currently a registered developer, so I don't digitally sign the SquareDesk releases (it's also kind of a pain in the butt to do so).
The "xattr" approach is the right thing to do for now.

**Comment by mpogue2** [comment]
It's annoying, I agree, but this is indeed the current workaround, given that SquareDesk is not done under the $99/year Apple Developer plan.  Closing for now.
