### ISSUE TITLE
Bug: a couple more titles that don't parse correctly

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#108]
RIV 524Dv - You raise me up (Du baust mich auf)
parses as Label: "", Title: "RIV 524Dv - You raise me up (Du baust mich auf)"

RIV 441j - Winter Wonderland (Japanese Version, called by Kumi Takahashi)
parses as Label: "", Title: "RIV 441j - Winter Wonderland (Japanese Version, called by Kumi Takahashi)"

RIV 524m - You Raise Me Up
parses as Label: "", Title: "RIV 524m - You Raise Me Up"

Changing the extra 1 or 2 letters in Label to UPPER CASE fixes these (I think).  

But surprisingly, "ESP 438v - Uptown Hoedown"
parses correctly.  So, it's not case alone that is the problem?

**Comment by danlyke** [comment]
Fixed in e334dc8007114bd4c6d0e80c6de733f92ed5ad8a

**Comment by mpogue2** [comment]
Verified all fixed on Mac OS X.  Nice.
