### ISSUE TITLE
Bug: In light mode,  cannot easily move a song up or down now

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#1091]
It used to be easy to move a song up or down: command-shift-up I think or right click and select move up.  Neither of these seems to work now.  Most annoying!!!   The right mouse menu seems to have disappeared completely now (but is still there in dark mode).   Please bring it back -- and preferably the key combo too but that's not important!

**Comment by mpogue2** [comment]
Seem like bugs to me!  Thanks for reporting!

**Comment by sharmanr** [comment]
Here's what I found,  when in Light Mode:

1. The right button menu doesn't appear because the bulk of function on_songTable_customContextMenuRequested is not compiled because of the #ifndef DARKMODE.  Remove that and the matching #endif and the right menu appears!   Things like "show audio file in Finder" now work.

2. Playlist items like "Move up in playlist" all do not work because the underlying functions have been renamed.
Rename the xxxItemyyy to xxxItemsyyy (add the s),  e.g. 
change                menu.addAction ( "Add to playlist" , this , SLOT (PlaylistItemToTop()) );
to                             menu.addAction ( "Add to playlist" , this , SLOT (PlaylistItemsToTop()) );
and they work.

3. The shortcuts to move songs up and down, e.g. Command Shift Up, still don't work.
At the top of GlobalEventFilter::eventFilter after setting theKey I added
   qDebug() << "eventFilter: theKey is " << theKey;
and after if ((KeyEvent->modifiers() & Qt::ControlModifier) && (KeyEvent->modifiers() & Qt::ShiftModifier)) {
I put
   qDebug() << "Control + Shift:  theKey = " << theKey;

In dark mode, if I press Shift then Command then Down I see
eventFilter: theKey is  16777248
eventFilter: theKey is  16777249
Control + Shift:  theKey =  16777249
eventFilter: theKey is  16777237
Control + Shift:  theKey =  16777237
eventFilter: theKey is  16777237
So it sees Control Command Down

However, in light mode if I press Shift then Command then Down I see
eventFilter: theKey is  16777248
eventFilter: theKey is  16777249
Control + Shift:  theKey =  16777249
and while holding down Control + Command keep pressing Down or Up I see no more events.
I don't understand this.

4. Possibly related is that in Light Mode if I press just the Up or Down I always see
bad selectRow 2

**Comment by sharmanr** [comment]
I just found that Shift Command Option Down works most of the time to move the song down in Light Mode, similarly Shift Command Option Up moves it up one.   
(That works in Dark Mode too,  i.e. adding the Option key is optional in Dark mode, necessary in Light mode.)

**Comment by sharmanr** [comment]
Please try branch lightmodefixes -- the right button now works in lightmode (and I think it didn't break darkmode!).

**Comment by mpogue2** [comment]
Awesome!  
Looking at the code changes, they look reasonable to me...I'll test dark mode in more detail later tonight (hopefully)...I gotta run right now!

Hmmm...the shortcuts should be just SHIFT-CMD-{UP/DOWN}, no OPTION, IIRC.  Oh, I see that SHIFT-CMD-OPTION-{UP/DOWN} also work, as does SHIFT-CMD-OPTION-CONTROL-{UP/DOWN}, and that's probably a bug that I inserted at some point! It should not just check for SHIFT and COMMAND, it should check that CONTROL and OPTION are NOT down, since we might want to use those key combos at some point in the future...

**Comment by mpogue2** [comment]
Done!  Commit: 777b5e6f150da81c381eb609888502e372d65294
You might want to double check it (I did not test Light Mode), and then close this Issue, when you get a chance...
Thanks!

**Comment by sharmanr** [comment]
Looks good to me!
