### ISSUE TITLE
Bug: Ding Ding didn't play?

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#1093]
I could be wrong about this, but I'm pretty sure the "ding ding" is not playing.  The volume is ducked on the music, but no ding-ding.  Perhaps the files are not installed in the local copy of the app?  I believe I was running from within QtCreator.

**Comment by danlyke** [comment]
I've noticed some inconsistency on this, and suspect that perhaps it's
playing on the wrong device? Haven't chased it.Message ID:
***@***.***>

>

**Comment by mpogue2** [comment]
True.  I know that the sound fx play on the laptop when I have wireless headphones connected. That's #1085.   
This could be related, and could be a Qt bug, I'm not sure.  You're right that these could be the same underlying root cause.

**Comment by mpogue2** [comment]
I just tested this in latest top-of-tree with audio device == wireless headphones, and it worked fine.  So, I'm not sure what's going on here -- is this an intermittent problem, or ??

**Comment by mpogue2** [comment]
I'm about 99.9% sure that this is the same as #1085.  closing this one, and I'll write some notes over there.
