### ISSUE TITLE
Bug: Cue sheet matching (Chaparral)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#113]
./SqViewCueSheets-9-30-16 Text/C 0306 - The Devil Went Down To Georgia.html
should be on the lyrics list for:
CH 306LK - Devil Went Down To Georgia

It's not an exact match, but there should be a way that it's in the dropdown list.

It might be necessary to special case that Chaparral can be abbreviated either C or CH, and that the number portion can have leading zeros?  I'm surprised the rest didn't match though...

**Comment by mpogue2** [comment]
This is the reopened portion of #86.  The rest of #86 was fixed on Mac OS X.

**Comment by danlyke** [comment]
I'm not doing anything to remove leading articles (ie: "The") in the
name yet.

**Comment by mpogue2** [comment]
Did I send you an article on fuzzy string matching a while ago?  The basic idea was to come up with scores for each possible match, and then go with anything that was greater than some threshold.  To calculate the score for two titles with respect to each other, they basically did a sort on the words in each title, and then you get points for each word that case-insensitive matches.  Variants might give more points to longer words.  We could do that with the number, too (maybe with leading zeros removed?). So, matching words in this example would be: devil, went, down, to, georgia, 306.  That would be a pretty strong match, and it would ignore the fact that "The" wasn't there...  Everything over the threshold would be presented to the user, maybe sorted by best score first. Something to think about...

Also, maybe there should be a way to get or see a list of the singing and vocal music that doesn't match anything?  This one could be a new feature request.

**Comment by mpogue2** [comment]
This one is fixed as tested in today's Master Top-of-Tree (edeac1f6238b4610981053220a9b0008b43c724f).  I'm not sure of the exact point when you fixed this, but it's really quite nice that it matches these in a fuzzy way!

I'm going to close this one, since it works!

**Comment by danlyke** [comment]
Woot! I suspect this was when I added the totally fuzzy matching.

**Comment by mpogue2** [comment]
Yep...your code was Super Effective! :-)
