### ISSUE TITLE
Bug: Light mode -- Fields at the top for type, label and title accept only 1 character

### ISSUE THREAD

**Issue by pkbott** [mpogue2/SquareDesk#1131]
Whey you try and type something into the search fields at the top of the columns (didn't try in dark mode) only a single alpha character will go into the box before automatically moving/tabbing over to the Title search field.  Example trying to type ARROW into the label search allows the A to go there but then the rest RROW moves into the Title search.  Attached some screenshots to show the issue.
<img width="1280" alt="Screenshot 2024-06-17 at 9 24 20 AM" src="https://github.com/mpogue2/SquareDesk/assets/55835882/323a1557-6226-4bbb-8550-8bfb4221e9d1">
<img width="1280" alt="Screenshot 2024-06-17 at 9 24 28 AM" src="https://github.com/mpogue2/SquareDesk/assets/55835882/d32fdb2a-dafb-4455-a17f-34a650efafea">

**Comment by mpogue2** [comment]
This bug is easily reproducible, so it should be possible to track it down.

**Comment by mpogue2** [comment]
OK, as per binary search, the bug was introduced by de5eae8866e86c830f356f7275f4abd94afae09b (by me).

**Comment by mpogue2** [comment]
This one is fixed, as of: 66988e9c78afe9d17a59a3dd8b75e0389c134ee6

**Comment by pkbott** [comment]
This seems to be all set.

**Comment by mpogue2** [comment]
Verified, so closing.
