### ISSUE TITLE
Bug: aliases don't track pitch/tempo separately

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#115]
To reproduce:

- Put an MP3 file, "foo.mp3" into the singing call directory.
- Make an alias of it, and put the alias into the "patter" directory. Typical thing for people to do.
Rename the alias from "foo.mp3 alias" to "foo.mp3". Now it will be detected as a normal MP3 file, and will show up in the songTable.
- double click the Patter version

Behavior: 
- changing the pitch/tempo changes the Singing version pitch/tempo in songTable (incorrect)
- double click to the Singing version, and change pitch/tempo changes Singing version (correct)
- double click back to the Patter version, and changes to the Singing version are cleared out (incorrect)

**Comment by danlyke** [comment]
Damn, this should have been fixed when we went to full filenames for
database tracking. Did that fix get hosed somehow?

**Comment by danlyke** [comment]
Should be fixed in 95dc22e417987f9811d41f0ee296dc32aee43d0b
