### ISSUE TITLE
Bug: SqView cue sheet title has incorrect character

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#116]
"MR 0070 - FishermanÔs Luck.html"

I'm sort of amazed that Dan's algorithm found this match at all!  The apostrophe is definitely not itself a match.  Just the filename is wrong.  If we redistribute the SqView files, we should fix any weird characters in filenames.

**Comment by danlyke** [comment]
Character set encoding is a sonofa...

**Comment by mpogue2** [comment]
Yeah...I'm surprised that the umlaut problem is not there in the HTM files, because it's definitely there in the SqView sqliteDB.  I guess we just have to make sure that we do a visual screen on the filenames before redistributing.

Or, maybe this should be done over the net?

**Comment by mpogue2** [comment]
First several files with this problem:
4B 6002 - PaintinÔ This Old Town Blue.html
BBH 20002 - Teddy BearÔs Picnic.html
BO 1350 - IÔll Fly Away.html
BS 2543 - IÔm The One.html
BS 2561 - CanÔt Take My Eyes Off You.html
CRC 167 - Be NobodyÔs DarlinÔ But Mine.html

They're all the same Apostrophe error.

**Comment by mpogue2** [comment]
OK, the problem is that apostrophe (0x27) is showing up (in just SOME of the filenames)
as 0x4F 0xCC 0x27, which is UTF-8 capital O with a combining circumflex.  This is exactly what shows up in the terminal window for these filenames.

If we want to match against these filenames WITHOUT changing them before redistribution (sounds good to me!), we need to do a gsub("0x4F 0xCC 0x82","0x27") before doing the filename string comparisons for cue sheet matching.

Dan, if you can give me a hint about where to fix this, I'll try to fix it.  I just happened to hit this with Fisherman's Luck, which has the bad O-circumflex.

**Comment by danlyke** [comment]
Yeah:

`$ ls 4B\ 6002\ -\ Paintinя\ This\ Old\ Town\ Blue.html`
`4B 6002 - Paintinя This Old Town Blue.html`

I think this is a nudge towards your "split on non-alpha characters and do word counting" technique. It'd go in "MainWindow::findPossibleCuesheets()".

**Comment by danlyke** [comment]
Take a look at the results of 8d9df1bb766628ad27cfc943ea4b1e4eb5f07c4c . There's some numbers to tweak, but it adds different approach to matching names.

**Comment by mpogue2** [comment]
I have to say, this works really well.  It matched up Fisherman's Luck, 
even with the bad apostrophe.
It matched up everything I tried....SWEET

**Comment by danlyke** [comment]
So shall we close this one?

**Comment by mpogue2** [comment]
I agree.  Closed!
