### ISSUE TITLE
Feature: font changes should use Cmd-+, Cmd--, like browsers

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#124]
Right now, font size changes use Cmd-8 and Cmd-9.  The Cmd-+/- key combinations are already used for tempo, so there's a conflict here.

How to resolve?
A) Assign Cmd-+/- to font, leave Tempo as +/- (no Cmd).  This violates the general principle that Cmd-X and X should do the same thing.  But other programs violate this, so maybe not so bad?

B) Assign Cmd-+/- to font, assign something else (what?) to tempo.  SqView uses E/R (right next to each other on the keyboard) for tempo down/up respectively.

There's probably a more general question of SqView compatibility here.  I'm not sure what CSDS uses for tempo hotkeys.

**Comment by danlyke** [comment]
I don't know if this is helpful, but I'd want the things I'm likely to use while actively calling to not involve chorded key combinations.... The system volume keys on the top row of my laptop don't need  control or alt or function (well, of my calling laptop, my working laptop does require the "Fn" key chord for volume), whatever gets chosen should be similar.

I think, though, that this is also a good reason for user assignments of them: I'd like to be able to map the function keys of my working laptop to something resembling the Fn-modified icons on them.

**Comment by mpogue2** [comment]
I think that's a good point, and several people have asked to not be required to use chorded keys.
On Mac OS X, the music player keys already optionally use Cmd.
Tempo = + or = for UP, - for DOWN (Shift key NOT required for +)
Pitch = u for UP, d for DOWN
Volume = uparrow for UP, downarrow for DOWN.

So, are you then leaning toward option A) above, where Cmd-+/- gives Font Size UP/DOWN and +/- gives Tempo UP/DOWN?  (Font size is used less frequently).  Or do you think we should just follow the SqView standard of E/R?
What's the equivalent of Cmd on Linux?

**Comment by mpogue2** [comment]
Another bit of information:  On MAC OS X:
F7 = <<
F8 = >||
F9 = >>
F10 = mute
F11 = vol down
F12 = vol up

I already use F11/F12 when calling for overall volume.  In that sense, the volume slider we have is a per-song overall volume adjustment.  I never use it when calling.  I really don't use it at all actually, so it would be fine to hide it for normal use.

But, the other controls, like tempo and pitch do not appear to have natural mappings to Fn keys on Mac OS X.  There are pictographs on F1-4 that are Mac OS X specific.  Only F5 and F6 are unlabeled.

**Comment by mpogue2** [comment]
OK, in the spirit of experimentation, I've checked in a change that does option A).  It's not too bad!!
+/- (when you're not in a search field) are Tempo Up/Down, same as before.  Cmd-= and Cmd-minus are now Zoom In/Out respectively, as they are in Firefox, Safari, and Chrome.  Try it out, and see if it works for you.  It feels right to me, although my brain still thinks it's weird.

Commit: e7a7488fb1dd660d06a7cf858ed06a1fbf860b57 .

**Comment by mpogue2** [comment]
I'm going to close this one for now.  Reopen if you try it, and you think we should put it back the way it was!
