### ISSUE TITLE
Feature: View > Columns > Age, Pitch, Tempo

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#129]
I think it's time to graduate the Experimental Age/Pitch/Tempo feature, since I think many of us are using it regularly now (I certainly am).  I experimented with a ToolButton menu to select columns, but in the current gridLayout, it doesn't line up well, so it looks bad.  There's no way that I could find to stick it above the vertical scrollbar in the songTable, which is where Thunderbird sticks it.

So, instead I propose we add it to the View menu, as a full-fledged citizen.  Something like: View > Columns > Age, Pitch, Tempo, where Age/Pitch/Tempo each have their own checkmarks.  Each can be checked (visible) or unchecked (invisible).  These settings would be persistent across app restarts.

Comments anybody?

**Comment by danlyke** [comment]
Works for me.

**Comment by mpogue2** [comment]
Implemented by d0082d41d63d87c64223b263dc118219660187c1 .
