### ISSUE TITLE
Feature: Precise loops for Patter

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#13]
For patter, we could overload using the In/Out buttons for coarse setting of in/out loop points.  But, we probably need a text box somewhere for fine precision.

**Comment by danlyke** [comment]
Since we don't yet have the merged repos, on the git@www.flutterby.com:SquareDeskPlayer.git repo branch danlyke commit 2d7f9c6f33fdfb009fab27815a15449e1f229e0e is a first pass at being able to edit these to .001 seconds.

I haven't worried too much about layout yet because I have additional cue sheet features I want to put in that drop-down area.

**Comment by mpogue2** [comment]
Sorry I didn't have time to move the repo yet...I'll try to do that tonight so we can move!

**Comment by danlyke** [comment]
Looking forward to it! I changed my DNS provider, so I'm waiting for DNS changes to propagate before I can access our repo again. Argh.

**Comment by danlyke** [comment]
We have the precise settings for singing call intro and outro points, are you okay with turning the intro and outro setting tools into loop setting tools for patter songs? If so, I have a patch...

**Comment by mpogue2** [comment]
I am...let's try it and see how it feels.  I agree that we might want to change the name of the tab.

**Comment by mpogue2** [comment]
Hey, do you have that patch?  I really want to see if we can get this to be a seamless join.  I am annoyed every time I hear that sudden jump from the middle of a phrase to the wrong spot in another phrase.  Dancers have to readjust each time, too.

I also have a suggestion:  when Patter is loaded, the Intro and Outro buttons should probably be renamed to be "Start Loop" and "End Loop".  The Lyrics tab itself could be renamed something else, too...maybe "Notes" or ???? (suggestions here?)

Also, if there IS a matching cuesheet for a Patter record, we should internally disable Auto-Lyrics Scrolling, even if it was set to ON by the user, because these are not Lyrics...With the new Lyrics Editor (Now AKA "Notes Editor"?), the matching file will be editable, which is a Very Nice Thing.

**Comment by danlyke** [comment]
Hmmm... Afraid I've lost that patch...

I'll try to recreate it at some point.

On Lyrics tab: Yes, I see this becoming tip patter when a patter song
is loaded.

**Comment by mpogue2** [comment]
More thoughts and questions here (I think I might look at this one next, if you don't get to it, since it's on my Super Annoying list, every time I hear a non-seamless transition... :-)
- The blue brackets in the songPosition slider should move to match the loop points.
- In the future, it would be nice to be able to drag those blue brackets themselves, to position the loop points from a coarse point of view, and then allow using Nudge or the text boxes to get it millisecond accurate.
- What should the Lyrics tab name change to, when a patter record is loaded -- just "Patter"?
- Should the loop points be available for singing calls, too (they are today).  If we allow both intro/outro and loop points for singing calls, do both appear on the (renamed) Lyrics tab, or only one?  Or, if not, should the blue brackets have a different meaning for singing calls (e.g. the intro/outro, maybe change the blue to same yellow that means intro/outro?  If the yellow brackets are draggable, that would also be nice for setting intro/outro...)?
- Should the loop points always be forced to the nearest upward-going zero crossing in the music?  (That would make the most seamless transition).

**Comment by mpogue2** [comment]
First cut at this is in: 515c7e6c0e44378ff74c49e9887a0de537cc24de .
Intro/outro fields are used for loop points (patter only).  Singing calls/vocals can currently be looped, but they will use the intro/outro points as loop points.
Blue brackets move to match loop points.
They are millisecond accurate (I think), if typed into the text fields, OR if Start/End Loop buttons are clicked during playback.  Resolution is coarse, if the buttons are clicked when nothing is playing.
The Lyrics tab now changes to "Patter" for known patter folders.
Loop points are NOT forced to zero crossings.  Maybe later.
Can't drag the blue brackets yet.  Later.

**Comment by danlyke** [comment]
Looks like it's working to me! I'm okay with moving this into master.

On forced zero crossings: I started looking at how to load the waveform for #79 and didn't get far enough to have a definitive answer, but it seems like once one of us gets into the libbass API far enough there's a couple of these things that'll fall fairly quickly.

**Comment by mpogue2** [comment]
Cool.  Merged as b00a01c80aece267f91b1926aaf0d9826834b5c2 .

**Comment by mpogue2** [comment]
Closing this one for now!
