### ISSUE TITLE
Bug: volume randomly goes to zero in DB

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#132]
I think this is the sequence:
We had a song that was named "Ex's and Oh's - NB-413V.mp3"
and we played it in V0.8.1.  Then we renamed it to "Ex's and Oh's - NB413V", and I moved
to V0.8.2a, and then renamed to "NB413V - Ex's and Oh's", and then it wouldn't play at all.
Same song played on my machine just fine. 

Renaming it to "NB413X - X and O.mp3" allowed it to play again.

So, I think this is a recurrence of that problem we had a while ago, where we got a bad entry in the DB, that we couldn't get rid of.

When I renamed the songs back, to their the following, I couldn't play them again:
"NB413 - Ex's and Oh's.mp3", "NB413NM - Ex's and Oh's.mp3", "NB413V - Ex's and Oh's.mp3".

When I renamed them to:
"NB413 - Ex's and Oh's.mp3", "NB413NM - Ex's and Oh's (no melody).mp3", "NB413V - Ex's and Oh's (called).mp3", all three could be played.

So, this sounds like the same problem we had with aliases before.  If there are two songs with the same name (not including the label/label#), then only the first one in the DB will work, and the others will look like they are playing but no sound comes out.

**Comment by mpogue2** [comment]
OK, after a little more debugging, the volume slider is going to zero randomly.
This happens on top of tree right now -- I saw it once on edc1fbdbba0499dc98a2d189f12ea679e535fcae, and I have not been able to reproduce it.
But, Regina has seen it several times on 0.8.2a.

When it happened to me once, the volume was suddenly zero, and it was saved as zero in the DB.
It has nothing to do with the filename uniqueness.  That was a red herring.

**Comment by mpogue2** [comment]
OK, after the merge, the same exact failing case we had before doesn't fail now.  There's a partial failure, but the previous one is gone.  Somehow the merge was better than either of the branches separately!

Old failure:  Hit the Road Jack with Volume 0 came in as volume zero (correct). Next I double clicked on I Need to Know (which was not yet in the DB).  The volume slider was left at 0 (incorrect), and when I went to the next song (500 miles, also not in the DB), the volume in the DB for I Need To Know was set to zero.

New failure: Hit the Road Jack with Volume 0 came in as volume zero (correct). Next I double clicked on I Need to Know (which was not yet in the DB).  The volume slider was left at 0 (incorrect), and when I went to the next song (500 miles, also not in the DB), the volume in the DB for I Need To Know was set to 100 (correct).

So, I think the thing that's missing is the reset of the volume slider to match what was read in from the DB, which I think is correct now.

**Comment by mpogue2** [comment]
No, the problem is that it's **intermittent**.
I can't replicate the Hit the Road Jack problem right at the moment, but I have a different problem now that is even simpler.

**New problem:** 
1) Delete old sqlite3 DB, and make a fresh sqlite3 DB by copying from a known good one.
2) Start app (top of tree: 5252088d20aa4f29d32d2d81b8388a3c03424fbd).
3) Scroll down in the songTable to DREAM LOVER and double click.
4) The intro/outro points are messed up (too small values, entire songPosition bar is yellow).
5) Repeat steps several times.  It fails about 25% of the time.

Dream Lover is already in the DB, with values pitch/tempo/volume/intro/outro of -2,128,0,0.033,0.983 .  SongLength and IntroOutroIsTimeBased are NULL.

**Comment by mpogue2** [comment]
I am suspecting the problem with intro/outro is that m_introOutroIsTimeBased and the following several member fields after it are not initialized in the constructor for SongSetting.

**Comment by mpogue2** [comment]
Adding those initializers fixed the intro/outro problem, I think.  I'll check in that change.
I haven't seen the volume goes to zero problem yet.
I still have the last_cuesheet is not being set problem.

**Comment by mpogue2** [comment]
Partial fix for intro/outro being too small: 76de5496c4108f2b7be501eb5312529dd716a3ea .

**Comment by mpogue2** [comment]
Fix for the last_cuesheet is not being set problem: ddf0d9c5c9fcf2c6577b1318c5925982fabc5a8c .
I still haven't see the volume goes to zero problem yet, after these last 2 changes.  If it doesn't show up again in the next day or two, I think we can close this bug.

**Comment by danlyke** [comment]
Ah, that might make sense...

I'm off at an all-day off-site, but might be able to fix that
tomorrow...

**Comment by danlyke** [comment]
These look good to me! Thank you for correcting my oversights.
