### ISSUE TITLE
Bug: Intro/outro are blank the first time

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#134]
To reproduce:
1) rename your sqlite3 DB (wipe the slate clean).
2) start SquareDesk.
3) double click on singing call.
4) go to lyrics page.  Intro/outro are blank.
5) go to music page, double click new song, go to lyrics page: blank.
6) go to music page, double click first song, go to lyrics page: now filled in with values.

**Comment by danlyke** [comment]
Fixed in 17a21ffb731e492dee9de1875acc3cd5a5e86dcd which also resets the intro and outro pos when the song is first loaded.
