### ISSUE TITLE
Feature: Make the song position bar bigger, and colors more contrasted

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#137]
User comment: ITS SUPER USEFUL BUT HARD TO SEE FOR ME.  I THINK IF IT WERE THICKER THAT WOULD HELP.  THE COLORS SORT OF BLEED INTO EACH OTHER AND I DONT RECOGNIZE WHERE I AM AT A GLANCE.

(I agree with this -- the colors are not contrasty enough for my taste, but choosing colors here is not simple...ideas?)

**Comment by mhkull** [comment]
Why not display: OPENER / FIGURE 1 / FIGURE 2 / MIDDLE BREAK / FIGURE 3 / FIGURE 4 / ENDING?

**Comment by mpogue2** [comment]
I love that idea!  On the main page, we can use the Timer area, since timing isn't really needed during a singing call.  But on the Lyrics tab we'll need to find some room for it.

**Comment by mpogue2** [comment]
See also #79 for a related way of viewing the song.

**Comment by mpogue2** [comment]
Fixed by 7dca84ac7585c56bf837c0f4e7e7727e1cc7c6ab .

Now that we have text that says "Opener/Break/FigureN/Closer/etc", I think the key is to make the Opener/Middle Break/Closer sections very distinct and contrasted, and the others (Figures)  much more muted.  

The Closer, in particular, means "this is it -- last chance to get everybody home".  So, this change makes the height of the color bands much larger (7 pixels, up from 3), and the colors are changed to RED for Opener/Break/Closer and DarkGrey for Figures 1/3, and DarkBlue for Figures 2/4.  That keeps the Figure sections distinct (from each other, and from the RED sections), but muted relative to the RED sections.

Note that SqView just alternates Blue/DarkBlue, which I personally don't find easy to parse at a glance.  I personally need the Opener/Break/Closer vs Figures distinction to be really obvious.

Feedback on the new colors would be appreciated...
