### ISSUE TITLE
Bug: Playlist super slow

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#138]
User comment on the Alpha: It takes minutes(!) to load a playlist! Very very slow!

**Comment by mhkull** [comment]
I upload a video to the bleeding edge dropbox folder, for you to look at. 
Video shows how I load 2 playlists, each approx. 50-60 song titles. 
Pls delete video, when you looked at it.

**Comment by mpogue2** [comment]
I won't attach the video, because it is almost 500MB. :-)
But, it clearly shows a playlist with a lot of entries taking a minute to load.  And, a second playlist that has a lot of entries taking 2 minutes to load.
WOW!

Martin,  could you tell us how many entries are in each of those playlists?
Your machine has plenty of CPU power and memory for this operation.  This is clearly something we are doing wrong! :-)

**Comment by mpogue2** [comment]
Martin, could you also let us know how many songs you have total in your Music Directory? 
I created a playlist with 50 items, and it took 4 seconds to load.  If your playlist has 50 songs, but you have 10X more songs than I do, maybe that is the root cause of this problem.  Thanks!

**Comment by mpogue2** [comment]
I am working on a fix for this.  Current version speeds up my small songTable by about 4X.  I suspect it will make yours a lot faster too.  When it's ready to try, I'll let you know!

**Comment by mpogue2** [comment]
My commit is bd4a645eff29327188e4a0b4c95037d1f584bfb2 .
My results are:
```
//                                          BEFORE      AFTER
// loadMusicList                             129ms      112ms
// finishLoadingPlaylist (50 items list)    3227ms     1154ms
// clear playlist                           2119ms      147ms
```

This might not be enough improvement, but it's a start.

**Comment by mhkull** [comment]
Playlist 1 is 60 songs, playlist 2 is 135 songs - total songs in music directory is 2250.

**Comment by mpogue2** [comment]
Martin, It's probably the number of songs, I would guess...when you have a chance, check out the latest version in Dropbox.  It should be a LOT faster.  With 2250 songs, I'm not sure how fast we can make it.  Might require more substantial changes.

**Comment by mpogue2** [comment]
By the way, Dan, I already tried reversing the scan -- instead of "for each playlist item { look at each row }" I tried "for each row { if row path is in playlist }".  Didn't save much time, so I left the current algorithm.  It's order length(songTable) in either case, I think, just because we're touching each row of the songTable.  I'm open to other ideas.  2250 rows in the songTable is going to be tough any way we do it!

One possible idea: sort the songTable, sort the playList, and do a merge sort.  When all are merged, end the searching early.  Avoids having to go through all of the items every time, at the cost of a sort (which could be done outside the songTable itself, if it's faster).  Worst case is not improved, though.  Just brainstorming here...

**Comment by mpogue2** [comment]
It's possible that doing it the alternate way would be faster for very large songTables.  I'll try to figure out a way to create 2200 more songs in the Music Directory, to see if I can reproduce this problem.

**Comment by danlyke** [comment]
Are you turning off sorting and updating when dealing with the playlist?

    ui->songTable->setSortingEnabled(false);
    ui->songTable->hide();

    ... do your processing here ...

    ui->songTable->show();
    ui->songTable->setSortingEnabled(true);

Is what sped up the reload of song ages.

**Comment by mhkull** [comment]
Congrats Mike! Loads A LOT FASTER NOW! It is almost perfect (max. 3 seconds)!

**Comment by mhkull** [comment]
Congrats Dan as well ;-)

**Comment by mpogue2** [comment]
Dan, yes, the biggest win turned out to be the hide(), which I stole from your Ages code... :-)  I factored it into startLongSongTableOperation() and stopLongSongTableOperation(), which are also instrumented for measuring the songTable timing, when needed for debug.

Thanks for testing, Martin!  I'm going to close this for now.

**Comment by danlyke** [comment]
Cool. I'll probably wrap the {start,stop}LongSongTableOperation() in a
constructor/destructor object like the other semaphore stuff, just so
that we maintain exception safety.

**Comment by mpogue2** [comment]
Sounds good!
