### ISSUE TITLE
Bug: weird playlist state - could not add new items via shortcut keys or menu

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#146]
The Playlist menu to add songs was greyed out.  Shortcut keys didn't work (the keys got passed on and interpreted as volume, etc. keys).  I'm not sure how I got into this state, but I killed the app and restarted, and everything was fine again.

**Comment by mhkull** [comment]
With Alpha 4 I cannot save a new playlist anymore!

**Comment by mpogue2** [comment]
@mhkull Thanks much for the report!  I opened a bug for this (#173), and it will be fixed in the next release.  The problem was that you can save a new playlist, but you cannot read that playlist in again (you'll get an error).  If you're reporting a bug that is different from that, please let us know!!

**Comment by mpogue2** [comment]
I believe this one is fixed, as of Alpha 7 and Top-of-Tree in Master.  

Closing as "could not reproduce, but let's reopen if it happens again".
