### ISSUE TITLE
Duplicate numbers get discarded in playlist saves

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#147]
If you happen to use a duplicate number when creating a playlist, one of those songs gets dropped from the playlist. This is annoying.

In particular, I went through my music using a ranking from 1 to 5 for how comfortable I felt doing a particular tune at convention, saved that list off, and got 5 songs in my playlist. Would much rather have gotten a random order within each number.

**Comment by danlyke** [comment]
Solved in 9f26bcc60f095c99584bb7e88c2b85b2cb267a3c

**Comment by mpogue2** [comment]
That's an interesting way to use the # column....I never thought of that!
