### ISSUE TITLE
Bug: Fixed column layout in songTable should be persistent

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#151]
If the guesser is off, and you have a song like: "XXXX - YYYY - ZZZZ", it will guess that "XXXX - YYYY" is the type.  That will mess up the layout.

So, step 1) the guesser should be the default.
Step 2) when the user fixes the layout, the fix should persist.

**Comment by mpogue2** [comment]
See #153 for step 1.

**Comment by danlyke** [comment]
So is this the same as save and restore song column widths? Tim Schares has asked that the changes to the song column widths be persistent.

**Comment by mpogue2** [comment]
Yes, it's the same.  The bug 1 above also highlighted the fact that the column widths (when manually set) were not persistent yet.

**Comment by danlyke** [comment]
Ugh. Trying to figure out how to do this given the "resize column to contents" setting in MainWindow::adjustFontSizes().

**Comment by mpogue2** [comment]
Yeah.  I'm not sure how to reconcile these.  The resize column to contents is very useful, especially as something have variable width (like song titles).  But, there is also an expectation that the column sizes are persistent.

Perhaps we should use the "..." trick?  If a column is manually resized to smaller than the title will fit, then instead of going to 2 rows for that entry, the title becomes abbreviated, with "..." at the end.  And, we get rid of auto-resizing entirely, with this method.

As I recall, there's some Qt support for doing the "..." thing...I don't remember where I saw it though.

**Comment by mpogue2** [comment]
Closing in favor of #476, which is broader than just column layout.
