### ISSUE TITLE
Playlists should have paths and .mp3 extensions

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#160]
Playlists aren't really usable with other tools without path and mp3 information. Maybe we need some sort of option selection...

**Comment by mpogue2** [comment]
Playlists (both CSV and M3U formats) currently use absolute paths, and they also use extensions.  That's actually a plus and a minus:
Pros:
- easier matching up with songs in the musicDirectory
Cons:
- fragile.  When musicDirectory is moved, all playlists are invalid.  Requires fuzzy matching to fix.

I'm actually thinking that absolute pathnames should be changed to relative, to avoid the fragility.  But, then matching is harder, and it also breaks older (absolute) playlists.  

Renaming a music file will always cause problems with either absolute or relative playlist paths, as will changing the format of a file (e.g. MP3 --> M4A/AAC).

What's the use case you're trying to solve?  (Or, is maybe this on a branch that is not checked in yet?)

**Comment by mpogue2** [comment]
@danlyke I'm guessing here, but maybe it _looked_ like the paths and extensions weren't there because of bug #173?  They're back now!  :-)

**Comment by mpogue2** [comment]
I think this one was fixed, so closing.
