### ISSUE TITLE
Feature: Playlist > Print...

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#161]
Printing a playlist is a nice-to-have.  Closed #150 in favor of splitting out this issue.

**Comment by mhkull** [comment]
It is a must have in Europe - we have to provide lists of used music for each dance to get the (in Germany) GEMA coverage.

**Comment by danlyke** [comment]
This'd be a reason to implement the "what songs were played" feature...

**Comment by mpogue2** [comment]
Agreed.  I suppose we could just keep the entire list of what was played when in the DB, and provide some way to print it out. This is a little more than a Print Playlist function.  @mhkull What do you think?  Is Print Playlist enough to be compliant for GEMA?  Or do you really need Print Everything I Played (even if it was not on a playlist)?

**Comment by mhkull** [comment]
We need to provide a list of music PLAYED at the event. SqVIEW has a function for that called "TRACKING".

**Comment by mpogue2** [comment]
Let's track the "list of music played at an event" as part of #81.  I'll annotate that Issue as well.

**Comment by danlyke** [comment]
We already have everything that was played in the database, so, yeah,
this is a report...

**Comment by mpogue2** [comment]
Good point.  So, maybe this is a report-generator thing, different from #81?

@mhkull what does GEMA need in the way of tracking?  Do you generate a spreadsheet (e.g. CSV) and send it in periodically via postal mail to GEMA?  Or, is there someplace you can upload the list?  Or is it just archival (that is, you just need to keep records, but you don't have to send them in to anybody, or maybe you get audited periodically)?  

If it's an automated upload, then I could see a feature that wasn't a Print, but instead directly uploaded the required info.

**Comment by mhkull** [comment]
GEMA needs at least event, date, title of song, label, number, original artist if known.
Lists have to be send in within a very short period of days after the event. The list can be a simple word file, so csv is ok.
There is no upload yet.

**Comment by mpogue2** [comment]
@mhkull  Thanks!  Could you post here a sample of the CSV file that you send in?  This will help us to do the same (or better).  The Date, Title of Song, Label, Number are already saved in the database, if your files are named like "Label Label# - Song Title.mp3".  But, where to put the event name (e.g. in the CSV filename?  inside the CSV file?).  We don't have information on the artist (because it's not usually in the filename or in the file), but if that is optional, we should be OK, right?    If there is ID3 metadata (which many pop songs have, but most square dance songs do not), we could pull out the "Author" field (is that the right one?).

I'm envisioning something like an "Export GEMA CSV file..." (or whatever it is called) dialog , and you would type in the event name, the date (defaults to "today", or maybe a date range?  can you submit multiple dates in the same file?), and a CSV file would be saved with all that information in the right format.

**Comment by mhkull** [comment]
Sample Looks like:

Club: Offenburger SDC
Event: Christmas Party
Date: 2.12.2017
Place: Rammersweier
Time: 14:00 - 22:00 Uhr
Leader: Martin Kull, Max Mustermann, ...

Song Title, Label, Nr, Artist, etc.
Driving Home For Christmas, MM 251, Chris Rea
...

**Comment by mhkull** [comment]
Your idea of typing in the additional Info is exactly what it should look like.

The GEMA CSV File is sent by the Leaders (Caller, Cuer, Clogging Instructor, etc.) to the MC of the dance. The MC collects the info and submits it to the GEMA Committe of the EAASDC (The European Association of American Square Dance).

**Comment by mpogue2** [comment]
Simple Playlist printing was implemented in d592426c9cc2f1e69a8786fa67d78234d647ea16 .  Closing this one.
GEMA-compliant tracking (and printing of the what-was-played list) will be handled by #81 (even though much of the discussion of the use cases is here).
