### ISSUE TITLE
Feature: Cmd-S, Shift-Cmd-S should be state-aware Save/Save As...

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#187]
It's a pain in the butt to not have Cmd-S work for saving edited Lyrics.  But, this key sequence is also needed for other saves: saving playlists and SD sequences.  After using it the way it is for several days now, I am inclined to change it to a single state-aware Save/Save As...

That is, when you're on the Music tab, it's Save Playlist/Save Playlist As....  When you're on the Lyrics tab, it's Save Lyrics(Patter) and Save Lyrics(Patter) As...  And finally, when you're on the SD tab, it's Save Sequence As... (and Save Sequence is disabled).

I think we can use File > Save/Save As... for this, because we don't have a need to save music any more (that was there for future use for saving MP3 files with modified metadata/ID3 tags -- at this point, I don't think we're going to do that anytime soon).

Anybody have any thoughts/comments on this?

**Comment by danlyke** [comment]
I'm good with making it state-aware. And, yes, I think the visible tab is sufficient context.

**Comment by mpogue2** [comment]
OK, it's in.  f2dbd97ea85b0bbb8f3711e05739aec83ece2742 .
I left the Save Playlist item for now, for consistency with Load Playlist, but also File > Save Playlist works.  Do the Playlist Load functions now need to move to File > Load Playlist, etc.?  I'm not sure.  Let's try this for now, and see how it feels in actual use.
