### ISSUE TITLE
Bug: Blowin' in the Wind (lyrics matching, extra space)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#188]
1) "RB3015i - Blowing in the Wind (Instru.mp3"
should have matched
"RB3015V - Blowing in the Wind 2 (Called by Koji Harai).html"

Changing to "RB3015i - Blowing in the Wind (Instru).mp3" by adding a right parentheses allowed it to match.

2) Also, when it was parsed, the label field seemed to have an extra added space between the 1 and the 5.

**Comment by danlyke** [comment]
Okay, I either have to finish or give up on this rewrite of the song
list to use MVC so I can get back to the better song matcher...

**Comment by mpogue2** [comment]
No rush...we still have lots of time, Dan! :-)

**Comment by danlyke** [comment]
Okay, if 4 or more words match we call it a cuesheet match, even if that's less than half the average number of words in either the cuesheet name or the mp3 name.
