### ISSUE TITLE
Feature: Direct access to iTunes Playlists (Mac/Windows only)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#192]
SquareDesk cannot currently directly access iTunes playlist files.  

If the iTunes playlists were created via OPTION-DRAG of files from Finder, or the "Copy files to iTunes Media folder when adding to library" is OFF when a regular DRAG copy was done, then File > Library > Export Playlist... will create a playlist usable in SquareDesk.

However, it would be nice if there were a Playlist > Import iTunes Playlist... feature, that would know which playlists exists, and would be able to load them directly by name.  Note that the files still themselves need to exist in the MusicDir to be matched when the playlist is read in.

For bonus points, offer to copy any non-matching files into the MusicDir, e.g. to an "Imported" folder in MusicDir.  The user can then use Finder to move them to Patter, Singing, etc. as they prefer.

**Comment by mpogue2** [comment]
References that might be useful for this:
https://support.apple.com/en-us/HT201610
https://github.com/lorenzog/python_playground/blob/master/itunes-extracter/export_playlist.py
https://stackoverflow.com/questions/19187142/tell-itunes-to-open-a-m3u-playlist-file/19187220#19187220
https://forum.qt.io/topic/19217/read-itune-xml-library
https://www.xml.com/pub/a/2004/11/03/itunes.html

**Comment by mpogue2** [comment]
It seems that once you turn on the Advanced Preferences > Advanced > Share iTunes Library XML with other applications feature, iTunes automatically keeps an XML file up-to-date with all playlist information.

Mac OS X: ~/Music/iTunes Media/Music/
Windows (different for Win10 vs Win7 vs Win8): http://osxdaily.com/2013/02/16/itunes-library-location/

This should make it possible to offer a somewhat simpler alternative than what I was thinking about before:  A new menu option called Playlists > Load iTunes Playlist > (list of iTunes playlists).  When an iTunes playlist is selected for loading, we can load just those songs into the songTable, and display them.  

Song types would be the value of the "Genre" key.  BPM is also there as the "BPM" key.  Display Name (AKA Title) is there as the "Name" key.

This is less fragile than it might appear, because we can assume that iTunes is keeping the XML file up to date and consistent, and it's the user's job to maintain the type field manually.  We should not therefore need to copy the MP3 files into the Music Directory.  They just appear in our songTable list when (and only when?) an iTunes playlist is loaded.  (Perhaps they need a special color or maybe an "iTunes" tag automatically shown?)

To parse the "iTunes Music Library.xml" file, we can use QXmlSimpleReader with a QXmlDefaultHandler.  There should probably be a Filewatcher on that directory, so that when a change is made to the XML file, the list of playlists and their contents can be reloaded.  If a playlist that is loaded is changed out from under SquareDesk, we will therefore be notified, and we can update our currently-loaded playlist numbers and files.  I think this is the most automatic it can get.  Just make changes in iTunes, load the playlist in SquareDesk, and away you go.  Note that some special handling might be needed for the default.m3u file, which remembers the last playlist used -- we still want that to work.

Alternately, we could just automatically construct playlists from the "iTunes Music Library.xml" file whenever the XML file changes, and stick them into the MusicDir's playlist directory with a name like "iTunes: <playlist name>", and let people load from there.  That way, the normal playlist loading mechanism would work.  These playlists would be auto-regenerated whenever SquareDesk starts up, and whenever the XML file changes on disk.  

Either way, it could be confusing because playlist songs do not appear in the songTable until an iTunes playlist is loaded.  Perhaps it is better to just also load all iTunes playlists -- simple to do, but messes up the songTable?  Or all iTunes playlists that are tagged with (SDesk) -- that's non-obvious?

**Comment by mysticole928** [comment]
I just want to +1 to this feature.

**Comment by mpogue2** [comment]
There's more interest in this feature than I thought.  Here's my current thinking on this!

I'm thinking that maybe something like this would work:
- SquareDesk could read the playlist definitions, to get a "list of iTunes playlists", when SquareDesk starts
- A "file watcher" would watch that list when SquareDesk was open, so that if you make a change to the playlists using iTunes/Music, that SquareDesk could notice and reload the playlist list.
- Then, maybe there would be a menu option:  Playlist > Load iTunes Playlist > <list of your playlist names>.
- If you select one of those options, the main list of songs would switch to "playlist only" mode.  It would show all of your songs, and whatever information we have on them (preferred pitch, tempo, age of last playback, etc.), just like a regular playlist. 
- BUT, you would not be able to change the order at all (this is UNLIKE the current SquareDesk playlists).  If you want to change the order of an iTunes/Music playlist, you'd do it via iTunes/Music. 
- You could still filter using the search fields, but if a playlist is generally small, this isn't very useful.
- (Alternately, we could merge in those music files into the current list of songs, similar to what happens now when you plug in an external USB thumb drive, which merges the songs in).
- Note that if you MOVE your iTunes/Music songs, I'd probably lose track of their Pitch, Tempo, etc. because I currently look at the whole pathname to keep songs separate from each other.  Two songs with the same name in two separate folders is currently possible, and they are kept separate, because they have different pathnames.
- There would be no distinction between patter and singing calls.  So, the automatic coloring would not work (all colors would be black).  Automatic default loop ON for patter would not work (although you could set the Loop ON manually, and it would be remembered.)  Automatic break timer (if ON) would probably start at the end of all songs, not just singing calls as it does today.
- Embedded ID3 lyrics would work, I think, since I currently handle those.  Would be good to test that with your songs!

Something like that.  :-)

**Comment by mpogue2** [comment]
The problem with Catalina:
https://www.theverge.com/2019/10/7/20903391/apple-macos-catalina-itunes-dj-software-breaks-xml-file-support-removal-update

**Comment by mpogue2** [comment]
Possible workaround for Catalina, to save Library.xml to a canonical location under program control:  https://macscripter.net/viewtopic.php?id=25751

Clicking on menu items using AppleScript:  http://hints.macworld.com/article.php?story=20060921045743404

Using the ITLibrary framework to get access to the playlists (but, this appears to require signing the application, or else access may be denied):  https://developer.apple.com/documentation/ituneslibrary?language=objc

**Comment by mpogue2** [comment]
153a1cebea5c50285222d0af05744a9d568a6fab provides code to read in the Library.xml file exported by Apple Music.  If we require that this be stuck into the playlists folder, then FileWatcher will be able to pick it up and re-parse it, when the user re-exports from the Music app.  This is not great, because if the app were signed, we could do it programmatically, but I think this will do for now.

**Comment by mpogue2** [comment]
reference: https://macscripter.net/viewtopic.php?id=25751
interesting tool: https://pfiddlesoft.com/uibrowser/features.html

The script below will open the Catalina Music.app, and will export the Library.xml file to a developer-specified location (e.g. the Playlist folder).  This obviates the need to sign the SquareDesk application so that it can use an Objective C API to access the Library file.  That's probably the best approach, but it's a PITA to do.  In the short term, having a "Import Playlists from Apple Music..." menu item might be simpler.  Then, we can have Playlists > Apple Music > foo ;bar; baz; etc menu items.  Selecting one will go to Apple Playlist Mode, where no songs show up, except the ones from that Apple Playlist.  Editing the Playlist would be disabled.

-- This script exports the current Music Library.xml file to a developer-specified location.
-- Make sure that the file does NOT exist, otherwise this script will fail.
-- It would be good to give it a unique name, and stick it in the Playlists folder, so it
--  does not conflict with anything else.  e.g. "<MusicDir>/Playlists/AppleMusicLibrary.xml"
--
-- When complete, Square Desk will be brought back as the frontmost app.

activate application "Music"

tell application "System Events" to tell process "Music"
	-- activates Music application
	set frontmost to true
	
	-- tell it to save the library to a file		
	click menu item "Export Library…" of menu 1 of menu item "Library" of menu 1 of menu bar item "File" of menu bar 1
	-- name of every menu item of menu 1 of menu item "Library" of menu 1 of menu bar item "File" of menu bar 1
	
	-- wait until Save dialog appears
	repeat until exists window "Save"
		delay 0.5
	end repeat
	
	-- Enter the save <foldername>, no "/" at the end
	-- the first "/" triggers the foldername dialog
	keystroke "/Users/mpogue"
	keystroke return
	
	-- save file as <this name>
	delay 0.5
	keystroke "AppleMusicLibrary.xml"
	click button "Save" of window "Save"
	
	-- go back to SquareDesk
	tell application "System Events" to tell process "SquareDesk"
		set frontmost to true
	end tell
	
end tell

**Comment by mpogue2** [comment]
I don't think this makes sense anymore.  No existing users of SquareDesk use iTunes playlists.
