### ISSUE TITLE
Bug: Changing to Session/Day-of-week in Preferences fails to update songTable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#196]
From Rob B:
> [In Preferences,] Changed the default to day of week, ok’d it went back to program and the sessions hadn’t changed had to close down the prog re open then it displayed the day of week as I would expect. Isn’t normal window function when changing an option and OK’ing the window that the change would be immediate?

Yes, it is!  This is a bug for @danlyke !

**Comment by danlyke** [comment]
Sooooo... this is just the default on startup. Should we make the default change the current selection when we come back out of the preferences window? I guess we could do so only if it has changed...

**Comment by danlyke** [comment]
Fixed (well, okay, this behavior is implemented, I'm not sure it's a fix, but I'll concede the point) in 4d37367b2dfb8eae9645faffda5acadd672eaee1

**Comment by mpogue2** [comment]
Thanks, Dan!

**Comment by danlyke** [comment]
Whoops. Also 6a66e2e634b5ae9f55a99e01c3ccb5facf2ca2bd
