### ISSUE TITLE
Bug: songs with no matching cuesheet can't see new cuesheet

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#197]
To reproduce:
1) double-click load a file that does NOT have a cuesheet
2) unlock, edit, Save As...
3) Dropdown doesn't change to the new named .htm file
4) can't see the new named .htm file

You can modify existing cue sheets, so there's a painful workaround:

0) Let's say you are playing My File.mp3 ....
1) Take an existing .html file, and copy it.
2) Rename it like your file, with .htm at the end.  e.g. Rocky Top.htm --> My File.htm
3) Stick the file somewhere in your music directory, e.g. lyrics/My File.htm .
4) Restart the SquareDesk app.
5) Double click My File.mp3 to load it
6) It should change Lyrics to *Lyrics as the tab name.  You have a matching cuesheet!
7) Go to *Lyrics tab.  Dropdown will say "lyrics/My File.htm", but contents will be Rocky Top.
8) Unlock, Paste in your stuff, edit away.
9) Click Save As...and save it with a new name.
10) Dropdown will change to that new name, and it's saved on disk.

But, this is SUPER ANNOYING.

**Comment by danlyke** [comment]
This just worked fine for me.

Is the problem that whatever you're saving it as not matching in the potential file name scan?

**Comment by danlyke** [comment]
(Possibility is that we need to be more promiscuous about potential matches, and just let sorting keep things relevant, or that we need to be able to attach additional names to songs...)

**Comment by mpogue2** [comment]
Hmmm....I don't think we need to go that far...I think the problem is probably that we don't rescan after saving.  It might be as simple as adding the name (manually) to the pathStack, rescanning the pathStack, and then setting the dropdown to the just-saved name (if it's in the list), regardless of match score.  

If a user chooses to save with a name that will NOT be picked up, that's probably OK in my book.  If a user chooses to save with a "near matching" name, however, it should be picked up and added to the pathStack and made the default in the dropdown menu.

The workaround gets around this essentially by forcing a rescan (by quitting and restarting the app).

We can also encourage "good" behavior by defaulting the saved .htm filename to <basename>.htm, if the original file was <basename>.mp3 or .m4a .  I believe the current default is wrong, if the source is a template, so that just made the problem worse by encouraging a non-matching name, which then just won't be found, even if we rescan....

I think the fundamentals of the matching code are still good and correct!

**Comment by danlyke** [comment]
We're already adding the filename to pathStack (if it isn't already
there), and reloading the cue sheet list.

It works fine on my machine.

So there's something else weird going on here.

**Comment by mpogue2** [comment]
I'll try it again, and see if I can come up with a reproducible test case with better details...

**Comment by mpogue2** [comment]
You were right -- adding the filename to pathStack was working fine.  The problem turned out to be two-fold:  cuesheet2.css wasn't being loaded in for templates, and the default save directory was garbage.  So, I was accidentally trying to save the wrong text into the wrong place.  Sheesh.

Should be fixed on both Mac OS X and Windows with 13f30b3f843148c9f7ea1a17e233e10a787fa897.
