### ISSUE TITLE
Bug: Cursor over song position + scroll action on trackpad changes song position

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#200]
Scrolling of lyrics was desired, but cursor was accidentally over the songPosition slider on the Lyrics tab.  

Got there by clicking on Lyrics tab, then trying to scroll immediately, without moving the cursor to the Lyrics area.  Confusing when this happens, because song fast forward/rewinds quickly for no apparent reason.

I think perhaps we should ignore scroll actions for both songPosition sliders?

**Comment by danlyke** [comment]
Yeah, I've been thinking about the whole song position slider, in fact
the sliders in general: I think a click at a location on the slider
should go to that location, not jump in that direction (ie: getting a
single step out of the pitch or tempo sliders is a PITA).

And scrolling over the tab selection area is similarly annoying...

**Comment by mpogue2** [comment]
@danlyke -- On Mac OS X, clicking on a location on the slider DOES go to the clicked location. It does not just jump in that direction.  This might be a Linux-specific thing?  And, scrolling over the Tab area has no effect on Mac OS X.  Does it change tabs on Linux?  (If so, yes that would be annoying! :-)

I'm gonna take a look this afternoon at how to ignore wheel/touchpad scroll actions over all of the sliders.

**Comment by mpogue2** [comment]
Fixed by 0a795a633c9968d28cc49a616625ab8b5c596b53 .

This change disables use of the mouse wheel and trackpad-based scrolling on ALL MySliders.  I've also converted the volumeSlider to a MySlider.  All MySliders now have no-wheel-trackpad-scroll behavior by default.

I think this will prevent the problem that Regina had.  NOTE: it does mean that, like before, to scroll lyrics your cursor needs to be in the lyrics pane.  But, if you forget, you won't mess up the other settings now.

**Comment by danlyke** [comment]
On Sun, 13 Aug 2017 22:45:44 +0000 (UTC)
Mike Pogue <notifications@github.com> wrote:
> @danlyke -- On Mac OS X, clicking on a location on the slider DOES go
> to the clicked location. It does not just jump in that direction.
> This might be a Linux-specific thing?

If it is: ugh. On Linux, a click on the location on a slider does the
"page in that direction" behavior. Okay, that gives me a good place to
start looking.

> And, scrolling over the Tab
> area has no effect on Mac OS X.  Does it change tabs on Linux?  (If
> so, yes that would be annoying! :-)

Yes. it is quite annoying.

**Comment by mpogue2** [comment]
Now that I've just made all sliders into MySlider's, you could manually catch these events and make them do the right thing on Linux....  There's now an eventFilter there that could catch these!

**Comment by mpogue2** [comment]
@danlyke -- Or, this might do it: http://www.qtcentre.org/threads/33574-QSlider-direct-jump

**Comment by mpogue2** [comment]
@danlyke -- also here:  https://stackoverflow.com/questions/11132597/qslider-mouse-direct-jump

**Comment by mpogue2** [comment]
Also to fix your "scroll affects tab" problem on Linux, it might be possible to reuse the MySlider event filter, something like:

somewhere in MainWindow::MainWindow(), put this:

> ui->tabWidget->installEventFilter(ui->bassSlider);

Since the bassSlider is never destroyed, you're just reusing the code from that instance, which ignores the object pointer anyway.

**Comment by mpogue2** [comment]
Interestingly, Win32 does NOT work the way the Mac works.  So, this change would help both Linux and Windows.  I'm going to create a new Issue for this one.
