### ISSUE TITLE
Feature: if there's only one song shown in the songTable, Return could load that song

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#202]
Alternately, if there are just a couple of songs (<5?), maybe Return could load the first one?

I know when pulling up a new song for testing or for performance, it would be nice to be able to do it just from the keyboard, assuming the search terms were "unique enough" for some definition of that.

Then, ESC could clear the search.  Or, should it clear the search automatically?  Or should Return do something different from Shift-Return?

Some interesting possibilities here...

**Comment by mpogue2** [comment]
I'm not sure if this will work, but we could also redirect the UP/DOWN arrows to the songTable for moving the selection.  They would only be redirected when the focus was in a search field.  Then, the flow would look like this:  start the app (focus is in the title field), type a few characters (filters), hit up/down to select (optional, if the first one is the one you want), hit Return to load (moves focus out of the search fields), hit Space bar to play.  Maybe TAB gets you back into the search fields...IIRC, the tab order is already set up.

I like the idea of driving more of the interface without absolutely requiring the trackpad/mouse.  It's faster, when you're hunting real quick for the next song to play.

**Comment by danlyke** [comment]
Yes. along with enter loading that song.

**Comment by mpogue2** [comment]
I LOVE LOVE LOVE this feature.  It's even quicker to get to a song now.  I also noticed how many songs I have that have "road" in the title.  I sense a theme night in my future! :-)

Here is the commit: d4cc79c6e3f371cb6992f09a15a0575480bcfedf.

If you're in one of the search boxes, it will now select the first song in the filtered list.  If you hit Return/Enter, it will load the currently-selected song.  You can use Up/Down keys to move the selection, and then hit Enter when you're ready to load it.  Focus is cleared, so you can hit Space to start playing immediately.

There are probably some weird cases, so please submit bugs if it doesn't work the way your fingers expect.  Return/Enter/Up/Down are now "special" keys, so God knows what happens if you try to assign them to something with the new keycap code.  I tried to only make them special when the user was in a search box, so hopefully things will still work as-expected.

I do have one open UX issue, and I will open a new issue to track that one.  I'm not sure how to solve it.
