### ISSUE TITLE
Feature: clicking on a slider should Direct Jump there, rather than scrolling in that direction

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#203]
Mac OS X works as expected, Windows 10 and Linux do not.  This seems like it might be by design in Qt.  We should be able to make it consistent (the Mac OS X way) on all.

**Comment by mpogue2** [comment]
Copying comments in from a different issue (#200), which is now closed:
Now that I've just made all sliders into MySlider's, you could manually catch these events and make them do the right thing on Linux.... There's now an eventFilter there that could catch these!
Or, this might do it: http://www.qtcentre.org/threads/33574-QSlider-direct-jump
also here: https://stackoverflow.com/questions/11132597/qslider-mouse-direct-jump

**Comment by danlyke** [comment]
I think that second StackOverflow link, with the QProxyStyle answer
from  maxschlepzig and Micka, is the right way to go.

**Comment by danlyke** [comment]
If you could test ecdfcca2f17746940ba0875721bb84865d9bd8a8, this
applies the fix on Windows and Linux only, using the style hint method.

**Comment by mpogue2** [comment]
Git sez you haven't pushed it to GitHub yet...or at least, I don't see it yet!

**Comment by danlyke** [comment]
Sigh. Got it this time...

**Comment by mpogue2** [comment]
I fixed a minor compiler error, and also made the Volume slider into a click-to-move slider, too, as part of 2219f8d293cd3016dc6c4640bb0b6c3ba6aa375f .

Works quite nicely, thanks!
