### ISSUE TITLE
Bug: crashes if left sleeping for a long time

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#209]
I've seen this twice now on Mac OS X.  If I put the laptop into sleep for a long time (like days), and come back to it a couple days later, I get beach ball, and I have to force-quit the app.  Force quit says that PS and SDP are both not responding.  Crash report doesn't have any real pointers to anything with symbols.  

I don't know whether I left mics enabled for PS or not.  I have not checked for small memory leaks either yet.

**Comment by mpogue2** [comment]
It's very possible that Dan's new PS integration, where PS is killed when not actually in use, will make this go away.  It's part of #211.  Once #211 is in Master, I suggest we close this one, and reopen only if it's seen again.

**Comment by danlyke** [comment]
So shall I merge #211 into Master, or do you want to?

**Comment by mpogue2** [comment]
The SD in #211 isn't quite usable as a replacement for the existing SD yet, but I suppose it doesn't matter much.  We need to merge in #211 at some point, and then bring it up to the previous SD level before next release in any case, and that can be done in the integration branch or in the Master branch.  
Do you think we can get it to useable in the next couple of weeks?  I'd like to do the next Alpha release in November, if possible, with Taminations, reference tab, new SD, etc. but the new SD has not yet reached parity with the old SD (e.g. ?, square your set, etc..).

**Comment by danlyke** [comment]
I should have some time tomorrow, I'll try to figure out why '?' and
tab aren't working like they do in the old one, and move your clean-up
of voice input over to post-typing.

**Comment by mpogue2** [comment]
I think this one is fixed by Dan's changes.  Closing for now, and let's reopen if it's seen again.
