### ISSUE TITLE
Bug: When Timer Tab is enabled, T key toggles to Timer tab, rather than Lyrics tab

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#216]
Reported by Peter H.  Verified that this bug is there in the latest top-of-tree version.

**Comment by phoef** [comment]
Perhaps it is an idea to define one hotkey for a tab and not toggle between two tabs with one key. If you have one key for one tab it makes you independent of how many and which tabs are enabled?

**Comment by mpogue2** [comment]
Fixed by 2dc533ed2ab3611f645f58113f1ac4ee194741c5 .
@phoef, I think this is a good idea, so I'm fixing the T toggle action to work correctly in the short term, and I will also enter your suggestion as an separate enhancement.  I picked "T" and a toggle action because that's what SqView uses, and many callers may automatically reach for that key.
