### ISSUE TITLE
Feature: separate hotkeys to get to Music, Lyrics, Timers, etc instead of T=toggle Music/Lyrics

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#222]
PeterH suggested:  "Perhaps it is an idea to define one hotkey for a tab and not toggle between two tabs with one key. If you have one key for one tab it makes you independent of how many and which tabs are enabled?"

I just fixed the T key so that it works like SqView (#216), but I think Peter's idea would be a better way to do it in the long term.  So, opening an enhancement ticket for this idea.

**Comment by danlyke** [comment]
7c4603d3d0e9c8cc9c26b7c9a377582fb5678092 in the hotkeys branch adds a number of potential keyboard actions, one for each tab, which keys can be bound to. Focus is kind of an issue, but function keys work well no matter where the cursor currently is.

**Comment by mpogue2** [comment]
Dan implemented this, and it seems to work fine, so closing!
