### ISSUE TITLE
Feature: default and/or help text for hotkeys in preferences dialog

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#223]
Brought over as an enhancement from #82:
Mike: The Key column is pretty wide.  Could we use the space on the right for something else?  Some simple help text, maybe?
Dan: I like help text, I was also thinking maybe putting the default over there...

**Comment by danlyke** [comment]
Okay, I started to do this, and then realized that except for the unassigned key, I didn't have any better suggestion. Also, with the hotkeys branch and the 5 columns of possible keys, we have less space than before. Is this still valid?

**Comment by mpogue2** [comment]
See comments in #246.... I agree that we can close this one!
