### ISSUE TITLE
Feature: Allow for color change, but no sound at end of song warning, break timer, etc.

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#229]
Suggestion from Rob B.  Current default sounds are not good.  Similar feedback from Caller's Workshop was that the voice couldn't be heard -- they preferred the beep-beep-beep sound.
Should we default to a ding, like SqView does?

**Comment by danlyke** [comment]
Check soundfx/7.short_bell.mp3 . Recorded off of manually tapping my doorbell, processed a bit.

**Comment by mpogue2** [comment]
The feature called out here (no sound, just visual indicator) has already been implemented.
