### ISSUE TITLE
Bug: Exact cuesheet-to-mp3-filename matches should be the default on Lyrics tab

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#232]
Reported by Rob B, here's a simplified test case that shows the bug:

1) There are two music files in the "singing" folder:
    "The Rose.mp3"
    "The Rose of San Joachim.mp3"
2) There are two cuesheet files in the "lyrics" folder:
    "The Rose.html"
    "The Rose of San Joachim.html"
3) When we double click on "The Rose" in the Music tab, Lyrics are found (the Lyrics tab changes to "*Lyrics").
4) Go to the lyrics tab, and we see the cuesheet for "The Rose of San Joachim.html".
5) Near the top, it says something like "/lyrics/The Rose of San Joachim.html".

This is wrong, because there's an exact match available:  "The Rose.html" is an EXACT match.  And, "The Rose of San Joachim.html" is not an exact match.  

For the initial cuesheet choice, we should always choose an exact match over an inexact match.  (This is true, regardless of the Music Names setting in Preferences, I think).

**Comment by danlyke** [comment]
Huh. In line 3746 inside compareSortedWordListsForRelevance we are penalizing different length word lists, so this shouldn't happen...

I may need to figure out how best to implement a bunch of little test executables so that we can granularize some of this better.
