### ISSUE TITLE
Bug: new .plist is incompatible with old SquareDesk

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#252]
If you try running 0.8.3alpha1, and you make a Preferences change, you can no longer run 0.8.2alpha7, because it will crash when trying to bring up any menu item (including Cmd-, for Preferences).

I deleted /Users/<username>/Library/Preferences/com.zenstarstudio.squaredeskplay.plist, and the problem went away (but preferences were of course lost).

The plist file looks fine to me, when viewed in Xcode.  Q is assigned to Test Loop is the only real change.

**Comment by mpogue2** [comment]
Because I was mucking with Preferences around the Test Loop feature, I am suspecting that the current hotkeys code is not tolerant to hotkeys being added.  See also #251 .  If taking out the hotkeys code makes this one go away AND the crash too, then I will need to sit down with Dan to understand what I did wrong when I tried to extend for the new hotkey.

**Comment by mpogue2** [comment]
OK, I think that #251 was due to a null pointer dereference.  But, I did see the old 0.8.2alpha7 version crash repeatably, after the new 0.8.3alpha1 version was used.  And, the crash of the old one did stop when I deleted the .plist file.  So, I'm thinking now that this crash is different, and somehow related to the Test Loop code that I added.

**Comment by danlyke** [comment]
Is this still an issue?

**Comment by mpogue2** [comment]
Thanks for triaging!  
I haven't seen this in a while.  Let's close it.
