### ISSUE TITLE
Feature: Filewatcher should be throttled

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#254]
The FileWatcher can be triggered repeatedly, if there's a lot of activity going on due to Dropbox downloading a bunch of new songs (for example).  It should be throttled, so that it doesn't spaz out trying to repeatedly refill the songTable.

**Comment by mpogue2** [comment]
Filewatcher should probably also be disabled when downloading Lyrics from the Cloud.

**Comment by danlyke** [comment]
Yeah, it appears that Tim's issue came from a shared sync'd music
directory and the filewatcher...

**Comment by mpogue2** [comment]
Filewatcher is throttled, as of #661 (d355e85a9ee3f622c929140b3dcbb2e65eb6702c).
