### ISSUE TITLE
Bug: Tempo of 100% appears on startup as "100".  Double click gives "100%".

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#26]
This is not easy to fix, since it's stored as an int in the Sqlite3 DB.  
Could be a new column to indicate BPM vs not (which would be backward compatible).

**Comment by danlyke** [comment]
Probably could use a little more testing, but should be fixed in 5feba4c815f06ea1e71b1bd42744c4807347c24d by adding a "tempoIsPercent" flag to the database.

**Comment by mpogue2** [comment]
It doesn't work for older values that are already in the database (e.g. "100" still shows up).  But, double clicking changes it to "100%" AND it is correctly set to "100%" the next time the app is opened.
I think that's good enough -- new users won't ever see this problem.  Closing as FIXED.
