### ISSUE TITLE
Bug: dependencies of sdlib are not recompiled/relinked when sdlib source files are changed

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#260]
I haven't looked into it, but I've been using a workaround.  
You must do ALL of these things, or you won't get your new sdlib changes compiled in properly:
1) delete all of the .o's in sdlib
2) delete the .a in sdlib
3) touch a file in the test123 project like mainwindow.cpp to force a recompile of the executable
Then, Cmd-R to build and run it.

Of course, you could also do a FULL clean and rebuild each time, but that's a real hassle.  What should happen is that if I touch an sdlib file, the .o gets rebuilt (currently it does), the .a gets rebuilt (currently it does NOT), and the main executable should get relinked with the new .a (which currently it does not).

Since this is just Annoying and there's a workaround, I'm not marking it "Super Annoying". :-)

**Comment by mpogue2** [comment]
Fixed on Mac OS X and Windows by edcd5c6b36e767be6ad61be99baebff8fb4568da .
@danlyke, there's a placeholder there for Linux.  Please uncomment and check!  Simplest way to check it is to run QMake, make a minor change to the TRYING TO OPEN line in sdinit.cpp, and recompile. It should pick up the change automatically, because sdinit.cpp will be recompiled, the .a will be regenerated, and the main app will be relinked.  If not fixed, the minor change will not be seen until you manually removed sdlib's .o's, the .a, and also touch mainwindow.cpp .

**Comment by danlyke** [comment]
Okay, I moved that line out of the conditionals, and made it a "+=" rather than an "=" just in case. I'm not sure this is closed because it's not rebuilding the library, just re-linking.

**Comment by mpogue2** [comment]
It works fine on this end.  Making a change to sdinit.cpp forces a recompile, and rebuild of the .a, and a relink of the executable.  I'm going to close this one, thanks!

(If it doesn't do what you want on Linux, we can open up a Linux-specific Issue to address it...)

**Comment by mpogue2** [comment]
Fixed by e6f418a9e6a9e6739c8dcda6274d1a6d5364bcf5 .
