### ISSUE TITLE
Feature:  Add preference to allow backtick (`) as synonym for ESC on Mac OS X

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#267]
On the latest Macs with the Touch Bar (which is awesome, BTW), the ESC key is soft, that is, it's in the Touch Bar, rather than being a physical key.  It still works just fine, but it would be nice to allow a physical key that is in almost the same location to be a synonym for ESC.

That key is the backtick (it's just under the tilde).  This should probably be a Preference, but it should probably default to ON on Mac OS X.

**Comment by mpogue2** [comment]
Maybe even default to ON just on Mac OS X laptops with Touch Bar.

**Comment by mpogue2** [comment]
Is there any use of the backtick on any platform, really?

**Comment by danlyke** [comment]
I'm good with the backtick as a configurable synonym... I use backtick
in bash a lot, but I think that's not what you were asking...

**Comment by mpogue2** [comment]
Yeah, I just can't think of a reason within SDesk to use backtick.  It's not likely to be part of any title.  I use it in bash, too... :-)

**Comment by mpogue2** [comment]
From the Apple docs:  "There is no need, and no API, for your app to know whether or not there is a Touch Bar available. Whether your app is running on a machine that supports the Touch Bar or not, your app’s onscreen user interface (UI) appears and behaves the same way."

So, it appears that the recommended way to implement backtick == ESC support is to do it on all Mac OS X devices.  That works for me, so that's what I'll do....

**Comment by mpogue2** [comment]
Fixed by 596955bd751a01c7037cc7be0773e4fae9e075dc .  Let's see how this feels....
