### ISSUE TITLE
Feature: Go back to HERE in SD, as new right click context menu item

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#274]
In the Current Sequence window, I find myself really wanting a right-click-context-menu item to be able to UNDO TO HERE, because I want to try out different alternative getouts for right after THIS call.

I'm not sure how best to implement this, other than to issue a bunch of undo's under the covers.  Is there some easier way, maybe?

**Comment by mpogue2** [comment]
Hmmm...double-clicking on the little teeny diagram shows me that diagram in the main window, but it really doesn't take me back to that step.

**Comment by danlyke** [comment]
Yeah, I wanted to be able to zoom the figure. I think the way to do the
undo is to just keep track and call undo that many times. Lemme see
what I can throw in there...

Dan
