### ISSUE TITLE
Bug: "(any setup)" doesn't have much meaning in SD...

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#275]
I'm thinking that it would be better to say nothing, rather than say "(any setup)", when the setup is not recognized as a standard one...  I'll attach an example.
[sequence1.pdf](https://github.com/mpogue2/SquareDesk/files/1658748/sequence1.pdf)

**Comment by danlyke** [comment]
This is a term passed straight through from SD, but we can match it and remap it...

**Comment by mpogue2** [comment]
Sounds good...
