### ISSUE TITLE
Bug: Playlists with (commas, parens) as item #1 are not loaded

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#28]
I think this might affect only the first item in the playlist....
Failure was for a CSV playlist file.

**Comment by mpogue2** [comment]
Yeah, there's a split based on "," right now, so any songs that contain commas will not be handled properly in playlists.  What we need to do is double quote the song names, and escape any double quotes in the song names, and scan backward for the last comma (the last columns in CSV can never contain commas).  

This is low priority.

**Comment by mpogue2** [comment]
Fixed by 2a13413bcad44cc45755601f880790a96046e77e .  There's now a mini-CSV parser that works on a single line.  It is double-quote and double-double-quote aware.

**Comment by danlyke** [comment]
We should coalesce this with "splitCSV" in importdialog.cpp
