### ISSUE TITLE
Bug: Filewatcher triggered too frequently (Linux)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#284]
It seems to work fine on Mac OS X.  But, Tim S reports that the File Watcher is being triggered every few minutes on Linux, for some unknown reason.  And, because the songTable sort order is reset to default (#283), this is painful when a playlist is loaded, for example (because the playlist disappears from view).

**Comment by mpogue2** [comment]
Verified not a problem on Win10 either.  It looks like this one is Linux-specific, for some unknown reason...

**Comment by danlyke** [comment]
I think that closing #283 makes this a non-issue, so I'm gonna close it.
