### ISSUE TITLE
Feature: auto-save in Lyrics editor

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#288]
Pointed out by Regina S -- Auto-save should probably default to ON, so as to be conservative about data loss.  

Also, Auto-Save needs to be double-checked to make sure it works if the program is Quit.  The latter might be a bug, if it doesn't work (we thought we saw this fail to save, but we should check the code to be sure it wasn't an illusion).

**Comment by mpogue2** [comment]
OK, I think that auto-save on Exit works fine, at least it does in my testing.  So, this is mainly a request to make Auto-Save the default.

**Comment by mpogue2** [comment]
@danlyke What do you think?  I can see defaulting to Auto-Save ON.  Should it also be a persistent setting?  Or, should it re-default to ON for each new lyrics file that is loaded, or edited, or ???

**Comment by danlyke** [comment]
I like default to on. The closer we get to "it just works when I change
things, the better". I don't like toggling it on loading new files,
though.

**Comment by mpogue2** [comment]
Maybe, do we need an Auto-Save checkbox at all?  What if we **always** Auto-Saved, and if you didn't like your edits, you would do a "Revert Edits" (a menu item we already have).  We could even replace the Auto-Save checkbox with a Revert Edits button, that does the same thing, to make it more obvious.

**Comment by mpogue2** [comment]
Auto-save has been disabled, due to #325.  However, this Issue remains open, so we can figure out what to do.  Should we bring it back and fix it, or get rid of it entirely?

**Comment by mpogue2** [comment]
Regina suggested an interesting possibility:  Save when the lock is manually closed.
I suspect we'd want to have the Revert button handy if we do it that way.  Maybe don't need the Save button or the Save As... button then?

**Comment by mpogue2** [comment]
I'm going to resolve this as "will not fix".  The current scheme, where you Unlock, and then either Save or Save As... seems to work reasonably well.  Save/Save As acts as "close the lock" now.
