### ISSUE TITLE
Feature: move OUT button and time field to the RIGHT side

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#313]
Feature request from Regina S...I think she's right on this one! :-)
IN on the Left, and OUT on the right.  Easier to locate.

**Comment by mpogue2** [comment]
@danlyke Does this work for you?

**Comment by danlyke** [comment]
Yes.

**Comment by mpogue2** [comment]
Fixed by 3b80d60ffc6904f5389ce419466d088bde4e4248 .
I also moved the Test Loop button to the far right, to better balance the Start and End Loop buttons when in a loopable (non-singing call) song.
