### ISSUE TITLE
Bug: Sorting by Title no longer works

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#323]
@danlyke When tags went in, sorting on the Title field stopped working.  As I recall, there's a custom sort function that needs to be updated, since the tags are embedding something in the table other than text nowadays.

To reproduce: click on the title header....  This bug also affects the initial stable sort order, which is now just 2 columns instead of 3.

**Comment by danlyke** [comment]
Created an invisible table widget item that contains a copy of the text for sorting purposes. Gross, but it worked.
