### ISSUE TITLE
Feature: "Square your sets" via GUI should not require also typing "yes"

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#326]
Currently requires I type "YES" after typing "square your sets". 
But, it's not required to do the same from the VUI (which essentially types the "yes" for you under-the-covers...)

**Comment by danlyke** [comment]
Hmmm... so double-clicking on "square your sets" on the list should
erase the sequence without confirmation? I'm okay with doing this, I
just need to figure out how to distinguish between double-clicked text
and keyboard or voice text at that point...

**Comment by mpogue2** [comment]
I think of it like this: if I double-click on a call, it should do what I say, and "square your sets" is just like any regular call.  For the VUI implementation, I believe it just feeds the engine "abort this sequence" and then "y".  That could be a way to do it.

**Comment by mpogue2** [comment]
Nice!
