### ISSUE TITLE
Bug: 4-Bar-B is not parsed correctly

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#332]
Thanks to Peter H for reporting this bug!

I think we might want to special case 4-Bar-B, because a song like "Top of the World - 4-Bar-B 6084" is parsed as Label/Number = "B 6084", and Title = "Top of the World - 4-Bar".

In fact, since there aren't that many labels, maybe we should special case all of the known label names?

**Comment by danlyke** [comment]
I don't think it'd be a bad thing to special-case known label names, but it seems like there are different variations... At any rate, I got "Top of the World - 4-Bar-B 6084" parsing correctly.
