### ISSUE TITLE
Bug: Tags preferences show #RRGGBB instead of color (in default location)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#333]
See screenshot below...this is on top of tree.

![capturfiles-20180330_065832](https://user-images.githubusercontent.com/6316003/38158612-cb527430-344c-11e8-94f8-b31eccb3feb4.png)

**Comment by danlyke** [comment]
Ugh, yeah, all sorts of broken there... Hang on.

**Comment by danlyke** [comment]
Just submitted c2e80ea4c1ecb6ca2c5d9e5ed8cd5ba87aeb3fea  which also makes the buttons the same as the other color selection, eg: small and square. I'm not convinced either way on that issue.

**Comment by mpogue2** [comment]
@danlyke Did you push the commit?  I'm not seeing it here.

**Comment by danlyke** [comment]
Whoops. Pushed it now.
