### ISSUE TITLE
Bug: square thru, but on the <Nth> hand, <ANYTHING>

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#338]
On the Mac client, I can select the <Nth> hand but then can't add <ANYTHING>

**Comment by danlyke** [comment]
I was just able to make this work on Linux, it should be the same on
Mac...

  HEADS square thru 4
  square thru, but on the 3rd hand, [touch 1/4]

Which I got by

  heads start
  square thru 4
  square thru, but on the 3rAd hand,

And at this point the prompt changed to "SUBSIDIARY CALL", and I typed:

  touch 1/4

Maybe we either need to hint at how to use the underlying SD engine
better, or I need to have some state that recognizes <ANYTHING> and we
change behavior somehow for that?

**Comment by mysticole928** [comment]
Perhaps I did it wrong.

When I was prompted to enter the number of hands, I double-clicked on 3.  That action sent the command to /dev/null.

I'm on a different machine.  I'll download it here and try again.

Thanks!
________________________________

**Comment by mysticole928** [comment]
Dan,

If I type the command, it works.  If I'm prompted for the Nth hand and double-click on it, it doesn't.

Tab auto completion also stops working after the the number.

Thanks!

Stephen
________________________________

**Comment by danlyke** [comment]
Aha. Thanks, I don't click much, and I haven't gotten the tab vs ? Thing totally in hand. I'll take a look.

**Comment by danlyke** [comment]
Okay, it's not perfect, I don't think I'm figuring out how to just get the valid subsidiary calls in the list, but at least I'm prompting for it now. In revision fc58dd56a73a952f2445d4bcf9dfb8fb97b8584d

**Comment by danlyke** [comment]
@mysticole928 if you wouldn't mind looking at this again with a version built after today (just pushed some code from my flight home) and seeing if the behavior is acceptable now, I'd be grateful!

**Comment by mpogue2** [comment]
This is fixed now on Mac OS X Catalina, as of 0.9.4 (top of tree right now, so perhaps it was fixed earlier), so closing this issue.
