### ISSUE TITLE
Feature: Startup time is slow...

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#341]
This is true on older Mac laptops as well as Windows laptops.  I haven't done a performance pass looking at startup time in quite a while, so it's probably that time again!

**Comment by danlyke** [comment]
And in instrumenting things, I think I know exactly where my performance issue is coming from: Resorting after the song is marked played.

**Comment by mpogue2** [comment]
I have never had the SW become non-responsive for several seconds after pressing play.  I am totally good with adding PerfTimers, maybe with an #ifdef PERFDEBUG so we can turn on the timers only when debugging performance...

**Comment by mpogue2** [comment]
I believe that we've done a performance pass, and there's a splash screen that improves perceived startup time.  So, I'm going to close this one for now.
