### ISSUE TITLE
Bug: underscores instead of apostrophes in Ubuntu

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#347]
The highlighted underscores should be apostrophe's, I think!  Reported by @olldray ...thanks!
![ubuntu_bug_2](https://user-images.githubusercontent.com/6316003/39971490-ac386de4-56b0-11e8-89b1-913ec8657ac0.jpeg)

**Comment by danlyke** [comment]
I need to know what characters those are. I'm seeing the apostrophe in filenames just fine here, I suspect those are some Unicode or Windows-1252 monstrosity..

**Comment by mpogue2** [comment]
Good point -- I bet you're right.  But, any attempt by @olldray to try to copy and paste the filenames to you may result in a transcoding, destroying the evidence, if you will.  

You might have to give him a special build that puts the equivalent of "od -hc" into the debug log.  I don't think the debug log that I put in recently is enabled on Ubuntu, but you might want to do that, and then ask @olldray to run it, and post the debug.log file here.  I think the debug log is a useful technique for debugging weird problems like this.

**Comment by olldray** [comment]
It looks like the files on my computer have underbars rather than apostrophes, so, maybe no bug here
