### ISSUE TITLE
Bug: Flash calls don't work in Ubuntu

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#348]
Reported by @olldray ....
The Flash call menus are there, and they seem to work as expected, but we never see flash calls.  All yours, @danlyke !

**Comment by danlyke** [comment]
Ah, missing allcalls.csv... Trying to remember what the other resource bundle issue we fixed recently was.

**Comment by danlyke** [comment]
Yay for adding features by commenting out #ifdefs...
