### ISSUE TITLE
Feature: allow lyrics to be in a "lyrics" folder

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#35]
...instead of right next to the song itself.

**Comment by phoef** [comment]
Hi, if there is label and number in the filename, then it could be good, if label and number is the matching criterium and not the whole filenname ... in cases you have music in different versions (with/without harmony) ;-)

**Comment by mpogue2** [comment]
Good idea, I will open a new issue to track this one!

**Comment by danlyke** [comment]
So: continue with the current search mechanism, and then fall back to just looking in the music path for .{txt,html,htm} with similar heuristics? That way under the music path someone can have a "cuesheets" folder and put everything there?

**Comment by danlyke** [comment]
Okay, I have a potential patch which finds all cue sheets under the music directory, attempts to match them up and score them, and gives you a drop-down in the Lyrics tab to let you choose which you'd like to see there.

So far so good, except that I need to figure out how to distinguish them. Right now I'm looking at the filename and the last directory entry, and using that unless I've seen that before, in which case I use the full path.

![cuesheetdisplay](https://cloud.githubusercontent.com/assets/88919/24979047/a9123b7e-1f87-11e7-9cb0-e46afa833701.png)
![cuesheetselection](https://cloud.githubusercontent.com/assets/88919/24979052/b192d89e-1f87-11e7-999d-76d391eab79c.png)

(Yes, that little down arrow on the left side of the slider bar is a hide/reveal button for the fine tuning and the particular cue sheet selection.)

**Comment by mpogue2** [comment]
Cool...will the selection be saved in the database as the "preferred" match?  Does it do a "fuzzy" match, so that "Rollin' in my Sweet Baby's Arms (Japanese)", "Rollin' in my Sweet Baby's Arms (Fast instrumental)", "Rollin' in my Sweet Baby's Arms (called by Dan)" all are matches?

**Comment by danlyke** [comment]
Yes, the selection will be saved in the database as the preferred match.

The fuzzy matching thing is sending me down a rabbit hole of yak
shaving as I try to make the name matching stuff smarter (about to do
some machine learning on a name dataset to try to come up with an
optimal transformation strategy).

But, yes, that's exactly the plan.

**Comment by danlyke** [comment]
So I think we can close this, although I'm still addressing the other issues.
