### ISSUE TITLE
Bug: filtering with new restrictors problem

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#356]
I have to say, this feature is way cooler than I expected.  So good, that I'm thinking that we should get rid of the Preference to turn it off.  I think the key was that solitary dashes in the middle of a string that are part of a title just work as expected (not excluding anything).

These patterns work as expected:
#tag 
#tag -string
-string
title with - dash in it

This pattern does not work as expected:
string1 -string2

Example, pattern = "danc -moon":
showing:
    Dancing in Dublin
    Moondance
expected:
    Dancing in Dublin

**Comment by danlyke** [comment]
Yep, I think the problem is that the "-" still searches from the current search location. As of 8c67e89b5ae1f3763d599bdd869e5e6d8cb4ae6a exclude word ordering doesn't matter.

**Comment by danlyke** [comment]
Woops, re-opening 'cause the preference is still there and I need to spend a little more time to get that.

**Comment by danlyke** [comment]
Okay, deployed. I'm a little concerned that without the preference this isn't discoverable, so we need to figure out something on that front.
