### ISSUE TITLE
Features: UX enhancements to the SD page

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#357]
Couple of minor enhancements (some might be good ideas, some not-so-good, let me know what you think):

- instead of Control-Context Menu > Go back to here, we might just use Double click on the call itself to go back there.  It's a bit quicker this way.
- Control-Context Menu > Copy as HTML also only copies the highlighted ones, should it copy all of them by default?
- Another intuitive way to go backward would be Command-Z.  For newer users, hitting Cmd-Z several times would probably be where they end up, if they didn't think to look for a context menu.  Right now, Cmd-Z doesn't do anything here.
- After Context Menu > Go Back To Here, the focus should go back to the string entry field, I think.

**Comment by danlyke** [comment]
On Sun, 13 May 2018 16:02:16 -0700
Mike Pogue <notifications@github.com> wrote:
> Couple of minor enhancements (some might be good ideas, some
> not-so-good, let me know what you think):
> 
> - instead of Control-Context Menu > Go back to here, we might just
> use Double click on the call itself to go back there.  It's a bit
> quicker this way.

I rarely want to undo, but I more often want to go see the details of
what the previous FASR was. So if we go there, only after we have undo
and redo, and we still leave the whole sequence up until the user types
something that changes the sequence. 

> - Control-Context Menu > Copy as HTML also only copies the
> highlighted ones, should it copy all of them by default?

For my use cases, I'd rather have the copy only what's selected, but
I'm still pondering how this is going to integrate into the choreo
management.

> - Another intuitive way to go backward would be Command-Z.  For newer
> users, hitting Cmd-Z several times would probably be where they end
> up, if they didn't think to look for a context menu.  Right now,
> Cmd-Z doesn't do anything here.

Cmd-Z should definitely be wired up here.

> - After Context Menu > Go Back To Here, the focus should go back to
> the string entry field, I think.

Yes.

**Comment by danlyke** [comment]
Yeah, the more I think about copy, the more I want it to do just the selected elements, but the undo is in place and it's obvious that I need to add redo fairly soon...

**Comment by danlyke** [comment]
So maybe we can figure another way to do a select all? (i'm also kinda hating the document prefix and suffix for HTML copy)

**Comment by danlyke** [comment]
The changes to #351 in 58b826f6e7918fdc4e40008d9eddc441b962adcd make all of these things easily user configurable, and default to your preferred behavior. 

Another one  can close!
