### ISSUE TITLE
Feature: need a better sound for Long Tip Warning 

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#359]
Default is "Beep beep beep", like a digital alarm clock.  Better is something like the SqView sound, which is more like "bing".  Sound is in soundfx/long_tip.mp3 .

**Comment by danlyke** [comment]
Check soundfx/7.short_bell.mp3

**Comment by danlyke** [comment]
Check soundfx/7.short_bell.mp3 (feel free to move it around as useful).

**Comment by mpogue2** [comment]
I'm thinking we need something a bit longer, like SqView has.  Maybe the same sound repeated twice in a row, so that it's a bit more obvious?  I'll play with this in Audacity when I get a chance...but, I like it already!  Did you record this yourself?

**Comment by danlyke** [comment]
Yes. I'm looking around for something slightly lower pitched with more
sustain. I did a bunch of tweaking of that one to try to play with the
sustain... Might need to just spend more time in audacity.

**Comment by danlyke** [comment]
I like the lower pitch, but I need some more harmonics in my ding, and I think I'd like a sharper fall-off from the attack.

I may have to find some metal to go beat on...

**Comment by mpogue2** [comment]
I hear ya....I do like the mallet instruments for that sharp attack.  Vibraphone or xylophone might be good, but I think they might not be enough high frequency for you?

How about a glockenspiel (highest high freq content)?
https://www.youtube.com/watch?v=1XgdKTfy1Pw

Xylophone (more high freq):
https://www.youtube.com/watch?v=1XgdKTfy1Pw

Vibraphone (more mellow, less high frequency):
https://www.youtube.com/watch?v=i24N22RM-XM

**Comment by danlyke** [comment]
I was really thinking lower frequency gong sort of sound, I just want
more overtones and complexity than a straight sine wave.

That plink is what I got out of my doorbell, not necessarily what I
want...

**Comment by danlyke** [comment]
This may be too low. Audacity created, I can toss up the project file if you want, but this is a C3 with E3 and G3 harmonics, with the E3 flanged a little bit and the G3 having a longer sustain. Removes a little of the "computer beep" feeling,

[Bong_mp3.zip](https://github.com/mpogue2/SquareDesk/files/2112112/Bong_mp3.zip)

**Comment by mpogue2** [comment]
Interesting sound, although I don't think I would hear it while calling.  I think it needs to be something that will pierce thru any patter song...  In any case, we can have a selection of sounds that could be used!

**Comment by mpogue2** [comment]
I'm thinking that we should each put a new sound into the soundFX directory, and then users can choose which they prefer.  I made this sound 
[dingding.mp3.zip](https://github.com/mpogue2/SquareDesk/files/2116360/dingding.mp3.zip)
based on a Roland xylophone sound.  I think it will cut through most patter.

**Comment by mpogue2** [comment]
5b9db27bb86408c0cc1d0d648d218890f0a7b06a adds your new "short_bell" sound, and my new "ding_ding" sound.  It also now delivers these 2 new sounds in the app. If you want to replace the "short_bell" sound with something else, please continue to use slot 7 (e.g. 7.*.mp3"), but with a new name, and update the .pro file to deliver it on all platforms.  NOTE: slots > 6 are not bound to keys, but they are delivered with the app, and so can be selected as break or long_tip sounds.

**Comment by danlyke** [comment]
Sweet. My "short bell" is close enough for me, but I'll keep looking
for an improvement.

**Comment by mpogue2** [comment]
You might want to check how the new files are delivered on Linux.  I only changed the .pro file for Mac and Windows, so I'm not sure how they get delivered on Linux...

**Comment by mpogue2** [comment]
I'm going to close this one for now.  Let me know if we need to open another one for delivering files on Linux!
