### ISSUE TITLE
Feature: Support for a Bluetooth Remote Shutter keyfob

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#361]
It would be nice to be able to use one of those cheap Bluetooth keyfob devices to control SquareDesk, like this one:

https://www.amazon.com/gp/product/B00WFXWKY4

**Comment by mpogue2** [comment]
Initial support provided in: fcb4d5e2b5809ece248b175e15a88c35e899f196 .
Right now, this is on the BTtest branch.

**Here's what you need to do.**
1) Pair the device to your MacBook.
2) Install Karabiner-Elements (free: https://pqrs.org/osx/karabiner/)
3) In Karabiner-Elements, use the Event Viewer to figure out what each button does.
4) Then, use the Simple mapper to map |< to F18, >| to F19, and >|| to F20.  Do NOT remap the volume keys (we'll leave those to control system volume, which works great already!)
5) This commit maps those to SquareDesks's Previous Playlist, Next Playlist, and playButton, respectively.
6) Wonder in amazement, as you remotely control SquareDesk.

**Limitations:**
1) With the cheap keyfob above, the SHUTTER key just generates Volume Up.  There's no way to change that, AFAIK.  Limitation of the key fob itself.  Maybe it's different on other platforms.
But, you still have Vol Up/Down, Track Prev/Next, and Play/Pause.
2) You need to install Karabiner, because I didn't have an easy way to remap system key events on HID devices.  Yes, I did try.  Given that Karabiner is free, I am reluctant to put too much more time into doing it inside SquareDesk.

**Comment by mpogue2** [comment]
I just realized that I actually have an F18 and F19 on my Mac extended keyboard.  I can't move them higher than F20, because Karabiner doesn't support higher numbered function keys (even though Qt does support them).  

Ctrl-F20, Shift-F20, and F20, maybe?  (F20 doesn't not appear on the keyboard).  This makes it more error prone to setup, though.

Hmm....

**Comment by mpogue2** [comment]
Commit: 6cb2f03cf102e184674cbc3b49a28c85d34bd0dc adds a couple of things:

- Previous Song is now exposed in the Hotkeys tab of Preferences
- Defaults Previous Song to "J" or "F17" (these are both new shortcuts)
- Next Song adds "F18" in addition to the already there "K", and Play/Pause adds "F16" in addition to the already there " ", "P", and "Cmd-P".
- Modifies the Previous Song functionality:  if the play head was at zero, it has the previous behavior (go to previous song).  If the play head was NOT at zero (e.g. it was in the middle of playing, or it was stopped somewhere in the middle of the song), the song is stopped, and the play head is reset to zero.  (This makes the behavior more like other music players, and the remote function for Previous song is a bit more intuitive, I think...)

**The updated steps to use the BT remote:**
1) Pair the device to your MacBook.
2) Install Karabiner-Elements (free: https://pqrs.org/osx/karabiner/)
3) In Karabiner-Elements, use the Event Viewer to figure out what each button does.
4) Then, use the Simple mapper to map |< to F17, >| to F18, and >|| to F16. Do NOT remap the volume keys (we'll just let those control system volume, which works great already!)
5) If you are using default key mappings, go to Prefs > Hotkeys, and Reset to Defaults.  This will pick up F16, F17, and F18 as defaults.  If you are NOT using default key mappings, add F16 to Play/Pause, F17 to Previous Song, and F18 to Next Song.
6) Wonder in amazement, as you remotely control SquareDesk.

**Limitations:**
1) With the cheap keyfob above, the SHUTTER key just generates Volume Up. There's no way to change that, AFAIK. Limitation of the key fob itself. Maybe it's different on other platforms.
But, you still have Vol Up/Down, Track Prev/Next, and Play/Pause.
2) You need to install Karabiner, because I didn't have an easy way to remap system key events on HID devices. Yes, I did try. Given that Karabiner is free, I am reluctant to put too much more time into doing it inside SquareDesk.
3) The keyfob will automatically power down after a few minutes of inactivity.  To bring it back, just press any key (which will NOT be passed to SquareDesk), and then press keys as normal.

**Comment by danlyke** [comment]
Okay, I'm not sure what all has changed on my system config, but my remote keyfob thingy just started working. The volume only goes to the system controls (even though the border around the QKeySequenceEdit flashes when I click on the button), but the other 3 buttons are usable for whatever. I can see wanting to add some more customized actions for music seeking (eg: rather than just +/- 30 seconds, things like next/previous singing call figure...).

**Comment by mpogue2** [comment]
Cool!  I currently have the volume buttons connected to system volume on my Mac, since that seems to work really well (and is not a persistent volume change for the song, as would be the case if we connected the buttons to the SquareDesk volume control).

I have some ideas I'd like to explore around doing more, e.g. using some of the buttons to cycle through a verbal menu, and then using other buttons for up/down of the currently selected control.

Simple things, where a button is connected to a single function, can be done pretty easily just by exposing the control via a function key.  What I'm thinking about is something more complex, where several functions could be accessed using only a very small number of BT buttons, because most BT remotes only have a small number of buttons.
