### ISSUE TITLE
Feature: match lyrics by Label/Label#

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#37]
Hi, if there is label and number in the filename, then it could be good, if label and number is the matching criterium and not the whole filenname ... in cases you have music in different versions (with/without harmony) ;-)

**Comment by mpogue2** [comment]
That was a suggestion from Peter Höfelmeyer....

**Comment by danlyke** [comment]
Hmmm... Think I need to clean up our regular expressions some. I'm *so close* on this, but...

**Comment by danlyke** [comment]
Looks like this is working now. I created a "HH 5213 - Foo bar bax.mp3" and it picked up the "HH 5213 - After The Lovin'" cuesheet. This, of course, depends on our filename parsing stuff to get it right, but it's getting better...
