### ISSUE TITLE
Bug: Redo in SD is not discoverable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#374]
I could swear it was in there before, but there is currently no way to figure out that Redo (Shift-Cmd-Z) actually works (and it DOES work...)

**Comment by danlyke** [comment]
Closed in 3458868e8aa2d0cba41f43af1c0d2957848a7493

I left the menu option in there all the time, just disabled it when there's nothing on the redo stack, for better discoverability.
