### ISSUE TITLE
Bug: SD animation doesn't work at all, if parameters are wrong, and let's make this real!

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#394]
@danlyke I was bummed, because I could never get the "temporary and very experimental" animation to work on Mac OS X (or Win10).

Well, I finally just took the time to try a bunch of different parameters, and lo and behold, it actually works on both Mac OS X and WIn10.  And, it's kinda cool!  It always takes doll-like shortcuts, but that's part of its charm, I think... :-)

So, I think we need to make some decisions here.  I actually like the feature!  
If you do, too, let's:
1) make it non-experimental
2) create an SD tab in Preferences for its parameters (I can see other controls coming here in the 
future, maybe? e.g. 3D view, doll colors, printing control, etc.)
3) make it a bit more robust for users, like provide sliders for the tunables that only allow me to set valid values, etc.  (That would close this bug, which is that it silently doesn't work, if the parameters are wrong.)
4) the default values should work really well.  I had 0.8, 150 for some reason, and that silently does nothing.  With 0.1 and 150ms, it works reasonably well.  There might be better ones, but 0.8 seems to be the culprit here (I'm not sure why -- I didn't root cause it).
5) Let's put some short inline help text to help users understand how the tunables work.

If you are not happy with the feature, then I think we should hide the controls for it (or maybe move them to a branch) until we have something that you do like. :-)

My personal opinion is that I'm in favor of "graduating" this temporary feature to a real feature, if you are!  It's not the same as integrating in Taminations animation, but that's a REALLY big job, and I think this is quite nice to have in the mean time.

**Comment by danlyke** [comment]
I think it's a great intermediate step, and most of the controls will
be useful for full-on Taminations integration.

**Comment by mpogue2** [comment]
Get rid of the magic numbers and the "very experimental" part. Replace with a dropdown with slow/medium/fast, or a slider to control the speed of animation.

**Comment by danlyke** [comment]
Okay, gave it an "Off/Slow/Medium/Fast" combo, still on the experimental page, in 3f7788f38b9b9e926602ef5b19cb7095cbae8d27

**Comment by mpogue2** [comment]
I like it!
