### ISSUE TITLE
Question: Up/down doesn't change row when focus is in the songTable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#401]
Instead, the volume changes.  Should it work this way?

**Comment by danlyke** [comment]
Ewww. I think that's a bug.

**Comment by mpogue2** [comment]
Up/down is a shortcut for (per-song) Volume up/down right now, but I almost always use the main laptop volume for overall volume.  I almost never set per-song volumes.  However, see #243 for Replay Gain.  In that case, we really DO want per-song volumes, with the default volume (or default volume indicator) set by Replay Gain on a per-song basis.

So, I'm not sure what to do with this one.  I think up/down when focus is in the songTable should move the selection up/down, but will that mess up people who use up/.down to mean "change volume"?

**Comment by danlyke** [comment]
I've got the opposite problem, my new laptop has system volume up/down chorded (fn+f11/f12), so I've been using the per-song volume like the system volume, and have been thinking about some way to allow that sort of behavior...

But, yeah, I'd like better keyboard navigation of the song table.

**Comment by mpogue2** [comment]
Ooh, chorded volume control seems annoying...
I am super fond of using BetterTouchTool on Mac with the Touch Bar.  Works really well, now that I've customized and color coded the Tempo, Pitch, and Volume controls to there.  I don't ever use the keyboard shortcuts nowadays.  And, the other callers around here using SquareDesk are all using the keyboard volume control for volume, not the per-song volume key shortcuts, near as I can tell.

I'm thinking that we should poll existing users to figure if anybody is using per-song volume from the keyboard.  If not, then we can reassign those keys to navigation when in the song table.

**Comment by danlyke** [comment]
Yeah, I mapped F11 and F12 to volume so I have 'em unchorded (except
not per song and all that), so I'm totally open to remapping the up and
down arrows...

But I think we're gonna have to do that revisioning thing, 'cause we've
saved the existing keymappings...

Dan

**Comment by mpogue2** [comment]
My latest Mac laptop does not have Touch Bar.  Reassigning anything other than UP ARROW to Volume Up doesn't work (as per the bug I just submitted).  Even when Vol Down is reassigned, the DOWN ARROW is not flowing through to selecting rows in the songTable (that will probably take some work).

I'm inclined to just change the default for Volume Up/Down to something else (e.g. F11/F12, like you did), and not worry about backward compatibility with existing key-mappings.  It's cheaper to just force our handful of users to re-do the mappings here.

**Comment by mpogue2** [comment]
This was fixed a while back.  UP/DOWN ARROWs change the selection in the songTable.  Closing.
