### ISSUE TITLE
Feature:  Make slider handle bigger

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#407]
From Regina S: To make it easier to see and to grab, make the slider handle bigger.

**Comment by danlyke** [comment]
Given that all of the sliders are click to a location, I'm not sure I understand the intent.

**Comment by mpogue2** [comment]
It's not just grabbing it, it's also being able to easily see where it is, e.g. on the Lyrics tab.

**Comment by mpogue2** [comment]
As part of #543, I changed the style of the sliders, and the handles are all slightly bigger now.  Closing this one as Fixed.
