### ISSUE TITLE
Bug: Return to screen loses keys

### ISSUE THREAD

**Issue by mhkull** [mpogue2/SquareDesk#41]
Sorry - I do not know how to put it. My observation was:

When I use SquareDesk I look at my lessen plan in a pdf program. I swipe with 3 fingers between the two full screen windows and scroll thru the pdf with 2 fingers going up and down. At the end of the patter I return to SquareDesk to end the music. But the focus is on "TYPE"Selection field. I must click on a piece of music first to regain keyboard control and press space to end music.

**Comment by mpogue2** [comment]
I see what you mean.  This can occur under two circumstances:
1) I return to SDP using Cmd-Tab.  Then the Type Search field has focus. 
2) I return to SDP by clicking near one of the search fields.  That search field will get focus.

By the way, there's a workaround:  if you ever get stuck in a Search field, hit the ESC key.  This will stop music and exit the cursor from all search fields.

**Comment by mhkull** [comment]
ESC key does the job. Problem solved! Thank you!

**Comment by mpogue2** [comment]
Leaving this bug open, because it still should not be changing focus to a search field when the window regains focus (e.g. via Cmd-TAB).

**Comment by mpogue2** [comment]
This was tricky to fix, but it is fixed by cab9dded8497e232b3cc649245df657920a1343b .
Now, ESC will PAUSE the music, it will clear search fields (#88), and if you go to another window and come back, focus will NOT be moved to one of the search fields.  If you click on a search field, it will get focus, and if you then go to another window and come back, focus will correctly be where you left it.

**Comment by danlyke** [comment]
Initialized oldFocusWindow so that this fix didn't crash on Linux. I suspect it would have crashed sometimes on Mac and Windows too, we should be careful about initializations, probably go through and list all of the MainWindow members in the constructor...

**Comment by danlyke** [comment]
Oh, that fix is a7e79aa5952d44f24666e75dfedaec78429cca28

**Comment by mpogue2** [comment]
Good catch!
