### ISSUE TITLE
Bug:  Save Playlist CSV files in file chooser are greyed out

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#410]
You can still click on them, but they are greyed out, suggesting that they cannot be clicked on.

**Comment by danlyke** [comment]
For reference, this doesn't seem to be the behavior on Linux (I resized the save window to make this image smaller, but otherwise it's untouched):
![squaredesksavecsv](https://user-images.githubusercontent.com/88919/45004785-490ebc80-afa4-11e8-933b-dec83b78bbb5.png)

**Comment by mpogue2** [comment]
You know, in looking at other Mac apps, they ALL grey out the existing files on a Save As... see below for what the SquareDesk Save Playlist As dialog looks like...

So, I am inclined to close this one as "that's the way Mac OS X does it".

![save_as_greyed_out](https://user-images.githubusercontent.com/6316003/45004883-174a2580-afa5-11e8-962b-e2c89c1b3149.png)

**Comment by mpogue2** [comment]
Yep, that's just the way all Mac applications work in the Save As dialog.  Closing as "will not change".
