### ISSUE TITLE
Bug: Pass and Roll doesn't work in SD

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#420]
Bug: reported by Rick J
Set to A2 dance program, square thru 4, step to a wave, pass and roll appears in the list, double click 
it, and it won't do it.

**Comment by danlyke** [comment]
Ah. I had threatened to re-start the SD process on level change, I may
have to do that now.

**Comment by mpogue2** [comment]
Fixed by ad384e6f7fc229d47015030816bd8680d5c3ad4a .

@danlyke : neither menu item seems to have any effect right now.  See #427.
