### ISSUE TITLE
Bug: In Dance Programs tab, when sorted by Name and item is checked, the completion date is not added to the correct row.

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#423]
Found by Rick J.

**Comment by rickjarvis** [comment]
Did some checking alternating between SquareDesk and a browser for SquareDesk.sqlite3 and found what appeared to be redundant rows in the db although when I tried deleting in the browser got error message about record not found. Also, when dance program sorted by name, checking a row puts check in that row but date in some other row. Then looking at the db, that other row is a new record and going back into SquareDesk shows that other row checked. Looks like record identification for update is just off when sorted by name. Not sure about the apparent duplicate records.

**Comment by mpogue2** [comment]
Yep.  In 
`void MainWindow::tableWidgetCallList_checkboxStateChanged(int row, int state)
`, when sorted by name, clicking on the first item (item 0) actually changes the date for row 38 (the row where that item was originally, but is not right now).

The bug is also there when sorted by Completed Date or Timing.

@danlyke I'm gonna leave this one to you, since this is your code! :-)

Nice catch, @rickjarvis , and welcome to GitHub!

**Comment by danlyke** [comment]
Oh that's super freakin' annoying: When the table is sorted the row this is called with isn't the row returned by item? In fact, I can't figure out what the row passed to that function is at all. Ugh.

**Comment by danlyke** [comment]
Okay, I think 87e7d935f7dde7be1572c45aecd90e462cee259e fixes this.
