### ISSUE TITLE
Can't download Windows .EXE file from GitHub

### ISSUE THREAD

**Issue by aglesser** [mpogue2/SquareDesk#43]
I get a 404 error on GitHub when I click on any of the file links. 
"This is not the web page you are looking for."
How can I download the beta version for Windows?

**Comment by mpogue2** [comment]
Ah...I broke the links when I uploaded the source code...  So I re-uploaded the binaries, and I updated the [squaredesk.net](http://squaredesk.net) links to use the new locations.  Sorry for the inconvenience!

**Comment by mpogue2** [comment]
Closing, since the links were fixed.
