### ISSUE TITLE
Bug: Redo in SD is broken

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#440]
Mac OS X (I haven't tried other platforms).

**Comment by danlyke** [comment]
Yeah, I've got to do a little reworking of the state machine that tracks
user input and maps that to what actually gets recorded as steps.

If you have specific sequences where this fails (because I think the
general case was kinda working for a while), that'd probably be helpful.

**Comment by mpogue2** [comment]
Heads start
square thru 4
swing thru
Undo
Redo

I think it's redoing the square thru 4, and it should have re-done the swing thru.
