### ISSUE TITLE
Bug: SD crash at app shutdown time

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#445]
On Mac OS X (Mojave), do this:
1) start app
2) go to SD tab
3) double click Heads Start
4) Cmd-Z to UNDO
5) Exit the app, via clicking on the red circle.
6) Crashes, with this crash report:

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x0000000109e0993e QBasicMutex::unlockInternal() + 14
1   com.yourcompany.SquareDesk    	0x0000000103b53e3e SDThread::~SDThread() + 46
2   com.yourcompany.SquareDesk    	0x0000000103b53f8e SDThread::~SDThread() + 14
3   org.qt-project.QtCore         	0x0000000109ff96fb QObjectPrivate::deleteChildren() + 203
4   org.qt-project.QtWidgets      	0x000000010a96380d QWidget::~QWidget() + 1037
5   com.yourcompany.SquareDesk    	0x0000000103ac5d04 MainWindow::~MainWindow() + 2772
6   com.yourcompany.SquareDesk    	0x0000000103a949dd main + 973
7   libdyld.dylib                 	0x00007fff5a4a2085 start + 1

**Comment by mpogue2** [comment]
@danlyke My guess is that this probably crashes on Linux, too.  Do you have Mac OS X build capability now?

**Comment by danlyke** [comment]
Hanging on exit on Linux. Clearly there's an internal state I'm not seeing correctly...
