### ISSUE TITLE
Bug: filters not working

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#468]
Reported by Peter H:

https://www.dropbox.com/s/tv45bf3gj83zlye/Bildschirmaufnahme%202019-01-14%20um%2006.54.06.mov?dl=0

When the filter is "hearts", we see titles containing "hearts" at the top, but everything else is still displayed, too!

**Comment by mpogue2** [comment]
This does not happen on 0.9.2alpha12b.  Maybe it is locale-dependent?

**Comment by danlyke** [comment]
I'd bet this is the thousand song problem.

**Comment by mpogue2** [comment]
Peter has tried it on 0.9.2alpha7b, and it works properly on that version.  So, it is not ONLY a locale problem (if it is related to locale at all).  This fact also suggests that it is not the 1000 song problem either.  I will provide Peter with a bunch of versions, and he has offered to try them out to narrow down when this bug was introduced!

**Comment by mpogue2** [comment]
I gave Peter H access to the DMG's via Dropbox for 0.9.2alpha8b, 9, 10, and 11 (the 4 releases between 0.9.2alpha7b which passes and 0.9.2alpha12 which fails.

**Comment by mpogue2** [comment]
Peter reports:
8b = ok
from 9 to 12 = bug

**Comment by danlyke** [comment]
Hmm... It'd be nice if our build procedure was a little more obvious about
sticking version numbers in the commit log...

**Comment by mpogue2** [comment]
Here is the gitkraken view, showing the tags (as far as I know, these are all pushed to the mainline GitHub instance)...

<img width="730" alt="gitkrackenview" src="https://user-images.githubusercontent.com/6316003/52098001-01578580-2582-11e9-9f9e-8a80991cb97a.png">

**Comment by mpogue2** [comment]
@phoef Thanks!  Yes, I had suspected that it was dependent on the German locale.  But, you have demonstrated that it is NOT sensitive to locale, but it IS sensitive to how many songs you have.  That's exactly what @danlyke suspected.  I think this narrows it down a bit, and maybe suggests that we should go backwards to a previous version of the Qt code we are using (unless this is a known bug that has already been fixed.  I do hate to go backwards, because that code is no longer being improved or supported by Qt.)

**Comment by phoef** [comment]
If you knew it was a temporary problem then I could live with limiting the number of my files to 1000 oe still use 8b. So you don't have to go backwards. 

But in the medium term, I think it's not what you want. Mmmmh....

**Comment by mpogue2** [comment]
It looks like the Qt bug report says that it was fixed in 5.11.3 .  The comments suggest using QSortFilterProxyModel instead of the QTableWidget directly, and that's the fix that @danlyke has been threatening... :-). I'll take a look at what it would take to upgrade to 5.11.3 or later, where this is supposedly fixed.

**Comment by mpogue2** [comment]
5.12.1 was just released, too, with a bunch more bug fixes.  We have been fairly conservative with upgrading, but it might be time to bite the bullet.

**Comment by mpogue2** [comment]
OK, here's what I found after trying 30GB of different Qt installations... (!)

Qt5.9.3 does not have the 1000 file problem.
Qt5.9.4 does not have the 1000 file problem, but it has a major songTable column layout problem.
Qt5.9.5, 5.9.6, 5.9.7 all have the 1000 file problem.
Qt5.11.3 and 5.12.1 both do NOT have the 1000 file problem, but all the slider grooves are offset, and songTable headers go bold when you click inside the songTable.  

While the slider groove problem and the songTable header bold problem could probably be worked around with some additional work, I think it's far simpler just to go back to Qt5.9.3, at least for now.

I am also not 100% sure that the later releases are slower.  They FEEL slower on first inspection, but after going back and forth a few times, I'm no longer convinced that they are a lot slower than the Qt5.9.* series.  If there is indeed a slowdown, going back to Qt5.9.3 will also avoid that, until Qt5.12.1 matures a bit more.  It also avoids the songTable header going bold problem, which is just annoying.

So, at least for now, I'll drop back on Mac and Windows to Qt5.9.3, and we'll live with it for a while longer.   

An alternative would be to figure out what change was made from 5.9.4 -> 5.9.5, and undo that change in 5.9.7 .  I leave that as an exercise for the reader.

**Comment by mpogue2** [comment]
As a side note: the slider grooves are also offset in the latest QtCreator/Qt Designer view, which is Qt5.12-based, but when the app is compiled and run using that version of QtCreator, but specifying Qt5.9.3 as the Kit, the app itself has correct groove spacing when it runs.  I'll have to try this on Windows at some point, to see whether QtCreator/Designer has incorrect groove spacing on Windows.

**Comment by mpogue2** [comment]
@phoef I've dropped a SquareDesk version (0.9.2alpha13) into Dropbox just for you!  It fixes the problem on my machine -- could you verify that it fixes the problem on your machine as well?  
Thanks!  If it is fixed, I will release it to everybody else.  This version drops back to Qt5.9.3, which seems to do the trick, without any other ill effects.

**Comment by phoef** [comment]
In the meantime, the file has arrived in my dropbox. 
Test was successful :-)

**Comment by mpogue2** [comment]
@phoef Thanks for testing this!  I'm going to close this one as "fixed by going back to Qt 5.9.3".
