### ISSUE TITLE
Bug: In SD, Allemande Left does not work

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#478]
This A1 singing call sequence:

Heads Pass Thru Separate Around 1 to a Line
Touch 1/4
Transfer the Column
1/4 Thru <-- Not currently available... Hinge and Centers Trade
Recycle
Dixie Grand
Allemand Left <-- This does nothing.
Swing Corner (Short promenade)

**Comment by danlyke** [comment]
Hmmm.... I can't get Allemande Left or Left Allemande to do anything
in SD, either... It's in sd_calls.txt, so it should be there.

**Comment by mpogue2** [comment]
Both "1/4 thru" and "quarter thru" work for me, in the sequence shown above!  I tested both with level (SD > Dance Program) set to A1.

Near as I can tell, "Allemande left" is not supported in SD, so SquareDesk does not support it either at this time.  (Sorry!)

**Comment by mpogue2** [comment]
BTW, I also tried the Tamination sequencer.  I couldn't get it to do Separate around 1 to a line (so I did cloverleaf, peel off, u turn back).  I could not get it to do Dixie Grand at all.
