### ISSUE TITLE
Feature: Separate List for Singers

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#479]
Create a separate tab for patter music and for singers.  
Or, 1 tab with two lists... patter on the left, singers on the right.

**Comment by danlyke** [comment]
GIven that the tab right now is linked to the music (and this can work
for patter songs as well), what would you like this to do?

(I'd like to have a split page on the lyrics tab, where we can pull in
choreo snippets from the long-delayed choreo manager...)

**Comment by mpogue2** [comment]
I think he's asking it to work more like SquareDesk...I'd rather not do that, but instead I'd prefer to implement #222, which provides hotkeys to get to singers more quickly.  Right now, you have to go to the type search field and type "sing" (or "s") to get just singing calls.

**Comment by mysticole928** [comment]
Usually, when I do a dance, I pick from a list of possible songs.  Depending on how the night goes, I might need something faster or slower.  Having a single list for all my music doesn't really work for me.   It's one of the reasons I don't really use iTunes for music.

Having two lists, one for patter and one for singers would be great. 

Another option would be be to have a single list but in two columns based on tags.  I use mp3 tags on my music and am working on a python script to edit the tags based on file names.

I think the current de facto naming convention is stupid.  I have never sorted music by label.  (Even back in the day when I used records.)  Using filenames for sorting is suboptimal.  So, I'm working on a system that will update the tag data for square dancing music and make the name irrelevant.

**Comment by danlyke** [comment]
So two notes here:

First, I put my music in Patter and Singer folders, and have Ctrl-T to
toggle search between those. So, yes, in essence I have two lists.
There may be some enhancements we can do with that.

when I have the time and energy to get to the separate song model
code, I want to set up virtual folders, so you can just unzip all your
music in a file tree and right click to assign to singer, vocal,
patter, or whatever.

**Comment by mpogue2** [comment]
Yep, we have the toggle, which allows two lists to share the same physical space on the screen (which in turn allows for bigger fonts, a big issue for many callers).  Sorry to hear that this doesn't work for you.  I do actually search by label, when I am searching for something where I know the label and not the title (e.g. "I think that song was on Riverboat", or "what songs do I have on Cheyenne?").  I'm interested in the ID3 idea, but most music producers that I'm aware of use filename to indicate title, and most do not use the ID3 tags.  I know of one caller who spends quite a bit of time hand-editing ID3 tags, but most in my experience don't want to take the time to get them right.  Let us know how your ID3 experiment goes!

**Comment by danlyke** [comment]
Yeah, when I'm searching for patter that isn't one of my go-toes, I use
label: Riverboat or Royal for things to move the floor, Rawhide for
teaching...

**Comment by mpogue2** [comment]
I'm going to close this, since we have what I think is an equivalent that uses less screen real estate.  Note that to enable this feature, you do need to edit the Hotkeys preference to actually set a preferred keystroke to do this.  

I went in and set Toggle Songs Filter to be ^T, and it does what Dan described:  it toggles directly between patter and singing call lists.  To show all songs in the list again, use ESC, which clears out the search fields.

Perhaps we could default this to ^T (or Cmd-T), to save the preferences editing step.  If so, please let us know!
