### ISSUE TITLE
Feature: import/export pitch/tempo/etc to TSV/CSV

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#48]
Suggested by Bill van Melle.  He wants to be able to import his per-song settings from his current setup.  CSV/TSV is a great way to do that.  We should make it all the settings we have that are on a per-song basis.

I'm thinking File > Import Settings and File > Export Settings, and then in the dialog allow choosing CSV or TSV.

**Comment by mpogue2** [comment]
Could we get away with exact matching on the .mp3 filenames for import?

**Comment by danlyke** [comment]
Hmmm.... Go for exact match first, and then fall back if we can't find it?

**Comment by mpogue2** [comment]
I think it's very, very likely that the filenames will match exactly.  So, we probably don't have to do fuzzy matching.  Can you think of a scenario where the filename of the file itself wouldn't match the files we need to match to?  But, I'm just not 100% sure on this.

Do you have Bill van Melle's email address?  I bet he would give us his TSV file and an "ls -1" to play with matching...

**Comment by danlyke** [comment]
Lay Bill's email address on me (via back-channel) and I'll figure out
what he needs.

**Comment by mpogue2** [comment]
Done.

**Comment by danlyke** [comment]
Ugh, little bit of an issue: I was saving loop points in the database as relative to the whole song, rather than absolute. I have a strategy for fixing this, but am also having to restructure some of the song settings stuff for the new import...

It does mean that we won't be able to export start and end points from songs currently in the database until those songs are played again.

**Comment by mpogue2** [comment]
Works for me.  Hey, this is a Beta, and some limitations are expected...

**Comment by danlyke** [comment]
First pass in the "importexport" branch. Need some better smarter matching on the import, and I don't handle commas in comma separated stuff (ie: it's just a split on the ',', not looking for quoted strings or anything fancier... And there's some debug I should pull out.

**Comment by danlyke** [comment]
This puts loop values in the intro and outro, which I think means we're gonna dual purpose those for loop. Haven't gotten there yet.

**Comment by mpogue2** [comment]
OK, I just fixed a couple of minor bugs:
- floor() requires math.h
- two pathnames and two lyric pathnames were being exported each time (missing breaks)
- pathnames (which can contain commas, and some of my songs do) must be double-quoted

**Comment by mpogue2** [comment]
Overall the export seems to work pretty well!  I think you went WAY beyond the call of duty though! :-)  Example: I don't think most callers need to be able to reorder columns on the fly.  That's easy to do in Excel, if needed. So, I'd suggest something simpler:  Export could output to CSV or TSV through a standard Save dialog (with 2 types in the dropdown: CSV, TSV), and should always export everything we know, in a format that we just pick (the one you picked as default is excellent!).  In this case, all the fancy dialog stuff would go away, and we'd be left with just a standard Save dialog call (like saving a Playlist).  I think it would work fine for almost all callers...What do you think?

**Comment by danlyke** [comment]
On double quotes: Damn, I was hoping I could get away without having to
write a real import parser. This means that split(",") is not
acceptable.

Okay, gotta do that.

**Comment by danlyke** [comment]
I'm okay with reducing this to a simple save. I'm not a market sample
here, so I don't know how people are actually gonna use it.

**Comment by mpogue2** [comment]
Libqxt?

**Comment by danlyke** [comment]
It looked to me like libqxt had been abandoned, and I didn't want to impose another compilation problem...

**Comment by mpogue2** [comment]
https://github.com/ben-strasser/fast-cpp-csv-parser

Maybe?  I am not adverse to slurping in a package to do so, as long as it is gpl too...

**Comment by danlyke** [comment]
Okay 411bb457585492ab883bf58dd6ddb0be4325c8eb does quoted strings on the CSV import stuff, leaves the TSV intact. I haven't yet trimmed the export stuff (should be easy, just haven't gotten there)

**Comment by mpogue2** [comment]
Current top of tree: e0b3cd248c968ea1c19ead6bf181f3b6143211ed  has a bug where intro/outro are not correct for many patter songs.  They all seem like duplicates, like it's picking up the same values over and over....  I'm attaching a sample CSV file, even though I know this is a work-in-progress, in case it helps!

[test5.csv.zip](https://github.com/mpogue2/SquareDesk/files/1049359/test5.csv.zip)

**Comment by danlyke** [comment]
Haven't fought the bug above yet, but it could be the problem where if we don't know how long the song is, we can't output an M:SS.## value, so the export really isn't valid until those songs have been played again and we've stored the length.

b79adf88fdcfd8d99153d60c7d107e4d13418241 changes the export to a file save dialog, goes comma separated if .csv, tab separated for everything else. I'm pushing this one a little bit because it'd be nice to get the better file attributes saving and loading stuff working because I think it'll help us with our "sometimes we get weird volumes" problem.

**Comment by danlyke** [comment]
I believe the intro/outro thing is fixed. Any objections to closing this one?

**Comment by mpogue2** [comment]
Let's close this one.  Did you want to refactor to use MainWindow::parseCSV() everywhere (or alternately, to get rid of parseCSV and use your splitCSV() function everywhere from importdialog.cpp?
I'm agnostic as to which is better -- I haven't really looked at each of them in detail. I'll open a new Issue for that task.
