### ISSUE TITLE
Feature: Add Start new sequence in SD

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#482]
In SD, I don't see a way to start a new sequence.  Right-clicking on the output screen lets me go back to the first step.  However, it doesn't let me go back to the static square.

I have to quit the program and start it again.

**Comment by mpogue2** [comment]
Try "Square your sets".  SD doesn't support this -- we added it as an alias for "abort this sequence, Y", which is the normal SD way.

**Comment by mpogue2** [comment]
I think you're right -- even though we have extended the UI to understand "Square Your Sets" when typed in or spoken (VUI), it's still hard to know how to get back to Static Square.  The normal SD way is not obvious.  e9fd817d1cc813f7d4dcfc16692b84da981f2f57 adds a "Square Your Set" item to the contextual (right-click popup) menu in the SD sequence window.

**Comment by mpogue2** [comment]
And, thanks for the suggestion!

**Comment by mpogue2** [comment]
See also #495.
