### ISSUE TITLE
Bug: In SD, "Cross" is missing from A1

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#483]
From a static square:

Heads Touch 1/4 and Cross

Cross is not in the list of available calls and it does not work if you just type it.

**Comment by mysticole928** [comment]
<excuse>Learning as I go.</excuse>

Looked in the SD Output screen.

I tried a number of random things.  One of them was, from a Static Square, Head Boys Cross.  That worked even though it wasn't in the list of available calls.

Looking at the SD Output: 

Heads start, Touch 1/4 

If I say Center Boys Cross, I get:

Can't do this call:
head boys cross
Some person (1B, for example) can't execute their part of
this call.

1B is looking diagonally at 3B.  They can do the call.  

(Center Boys Cross has the same error.)  

After firing up a Windows VM, I checked SD and it won't let me do it either.  So this is probably not your bug to fix.

**Comment by mpogue2** [comment]
Try:  Heads Start, Head Boys Cross.
Works for me!
SD is peculiar in this regard.  You have to start with heads/sides start, or just as they are.  Check out the SD manual, which provides some help on this...

**Comment by mpogue2** [comment]
And, this also works:
Heads start
touch 1/4
centers boys cross (note the s on centers, that specifies the "who")
SD is quirky, but it is free and open source. :-)

**Comment by mpogue2** [comment]
This really should be translated by us:

"Heads Touch 1/4 and cross" --> heads start; touch 1/4; centers boys cross
