### ISSUE TITLE
Feature request: Customize the SD screen

### ISSUE THREAD

**Issue by mysticole928** [mpogue2/SquareDesk#484]
I would like the ability to have the command entry on the right side of the screen and the commands on the left.

Also, in the "Current Sequence" view, I'd like to be able to have a larger view of the dancers.  It looks as if the aesthetic is about having an 8x8 matrix.  That's nice and all but It makes viewing the historical output challenging.

The SD output is a little better (not much) for viewing.  However, as it's simply the standard out, it can be challenging to follow.

**Comment by danlyke** [comment]
Hmmm... Let me diddle about with sliders, this may be possible. I've done the resizing the view thing in #512, so this would be basically swapping the left and right frame in the new slider. I'd also like to view the checkers in the Current Sequence tab larger...

**Comment by danlyke** [comment]
Gotcha your larger view of the dancers in #512, just pushed an option in the Experimental tab under preferences to flip sides of the two panes.

**Comment by mpogue2** [comment]
I think this is a very nice addition.  Rather than an experimental preference, I think it should graduate to the SD menu (maybe something like [checkmark] SD > Checkers on left-hand side, with default to not-checked?)
