### ISSUE TITLE
Feature/documentation: document how to get mics working on Mojave

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#491]
If you accidentally say "no" to grant permission to SquareDesk to use the microphone, then it's hard to re-enable the microphone.  Need to document how to do this in detail.  As I recall, it's not obvious.

**Comment by mpogue2** [comment]
Mac OS X only.

**Comment by rickjarvis** [comment]
Mike,

Found how to delete permissions. From Terminal:
rm -rf ~/Library/Application\ Support/com.apple.TCC

Kind of annoying to remove all permissions, and I found I had to disable System Integrity Protection and then sudo to remove the files.

Unfortunately, while other apps asked for permission to use mic (including Audacity) and got added to the permission list for the mic, SquareDesk did not ask and is still not listed. I can enable/disable mic input in SquareDesk and see the status change in text message bottom right of window, but still missing something to get SquareDesk added to the list.

Hope this helps a bit. Thanks - Rick

BTW, I don’t see how to turn on animation in SD. Is that available on the Mac?

+++++++++++++++++++++++++++++++++++
Rick Jarvis, 864-650-1080, jpjrvs@gmail.com

**Comment by mpogue2** [comment]
@rickjarvis That helps, thanks...I am still not sure why a permission request is not shown to the user...this is weird, and Googling hasn't given me an answer yet!

Animation will be much easier to turn on now that Dan has made some changes to address #394 and #466.  This will be available in the next published version!

**Comment by mpogue2** [comment]
I'm on Catalina now, and I can't get mics enabled.  It seems that lots of people are having this problem on the internet, and there is no solution yet.  It has been reported that app signing and notarization does NOT fix this.  

By the way, the new Catalina way to do this is:  "tccutil reset Microphone".
It deletes all the permissions.  But, there's still no way for SquareDesk to ASK FOR the permission.

**Comment by mpogue2** [comment]
See #538.

**Comment by mpogue2** [comment]
Moot, now that PocketSphinx voice input has been removed.
