### ISSUE TITLE
Bug: "Heads Promenade while the others ...." does not work

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#496]
in SD, if I type in "Heads Promenade" and the click on "Heads promenade while the others <>", and then I type "Roll away", it actually does a Heads Roll away, rather than what I asked.

**Comment by danlyke** [comment]
Interesting. I need to do away with the first tab and start to do a lot of '?' and letting the SD engine give me results

**Comment by mpogue2** [comment]
Two problems:  "promenade" was being transformed to "proboysade".  LOL.
And, "halfway" was being transformed to "1/2way".  LOLOL. 
Fixed by: 054c013c6e4ee77dea669ce23a3c84d50845d28b .
