### ISSUE TITLE
Bug: need to restart the SD thread when the program level changes

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#498]
e.g. Mainstream -> Plus

As per Dan: " I need to be restarting the thread on program changes anyway, 'cause SD sets some things up differently on different programs, so that's a slightly longer thing."

**Comment by mpogue2** [comment]
See a94f90f76d3b1b8cc264f605b404bc1dd859f076 .

**Comment by danlyke** [comment]
Got this one!
