### ISSUE TITLE
Feature: Auto-bring up lyrics on Play (if lyrics present)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#5]

**Comment by danlyke** [comment]
Pushed in 79d236e5d8cadbfc16522d71da9d529ff70afa06. but:

1. Do we want this as a preference?

2. This patch currently only switches over to the lyrics if it's the first time the song has been played (ie: if you switched back and hit stop or pause, we don't switch). Is this what you envisioned?

**Comment by mpogue2** [comment]
Yes I think this should be a preference.  Do you agree?

I hadn't thought it all the way thru, but I think switching the first time makes sense!

**Comment by danlyke** [comment]
Do we need to start another tab on the preferences dialog (small
screens are still a thing, but I haven't checked to see how much we're
pushing my netbook yet...), or squeeze it on the current one?

**Comment by mpogue2** [comment]
Let's go the simple way.  I am attempting to pull in a change from the 
danlyke branch, that gets rid of the Lyrics tab preference.
I am trying to fix rebase problems, but when it's in, that will make room.

I agree that eventually we'll want to change this, but for now I think 
we should just use the space that we have now.

**Comment by danlyke** [comment]
Okay, I've pushed a version with a checkbox in the preferences to the "master" branch as c211f497e6af2d1752ac7270cf46aab8800629fd . It defaults to "off", which I think is wrong for discoverability.

**Comment by danlyke** [comment]
Also, you should probably work your readability and layout magic on it...

**Comment by mpogue2** [comment]
Will do!

**Comment by mpogue2** [comment]
It looks really good to me (and it works -- cool!).  I tweaked a couple of words to clarify what the Preference does, but otherwise, I think it's Most Excellent.  Word tweak: eeff9636c6ef9b29cac0c5215c5ced402a3ca2ad  Let me know if you are OK with the wording...

**Comment by mpogue2** [comment]
One more comment:  I think it's fine to leave it "off" as default.  When first starting the program, and adding music, I think people will try playing music first, then will try looking at lyrics second. During that first phase, I think it should be off.  Then, when they see the Lyrics (and realize that the choices are remembered), they may want to turn it "on".  So, I think that argues for off-by-default, unless we get some feedback otherwise....

**Comment by danlyke** [comment]
I like your wording (I couldn't figure out how to make that control not
move the music types around when I made it longer, whence my truncated
wording).

Yay! Another feature down!

**Comment by mpogue2** [comment]
Yay, thanks! 
By the way, the secret to stopping the field moves was to make the new field bigger horizontally (manually), so that it spans more columns... Select, then drag the right hand handle...

**Comment by mpogue2** [comment]
OK, the final tweak to this was eeff9636c6ef9b29cac0c5215c5ced402a3ca2ad .
Thanks, Dan, for putting in this feature!  Closing as FIXED.
