### ISSUE TITLE
Bug: Clear Formatting in Lyrics editor should preserve the cursor

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#500]
Today: Select some text, hit Clear Formatting, and the text is no longer selected.
Should be: same text stays selected

**Comment by danlyke** [comment]
Closed in 76ca9d80f522d569edae54337dd6782d051f1576, except that we may want to clear selection and maintain the cursor, 'cause it's not immediately clear that anything's happened now, and it's not like you want the whole selection cleared. Play with it...
