### ISSUE TITLE
Bug: Editing and Saving Lyrics should not reorder the songTable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#504]
Save or Save As... Lyrics cannot possibly change the songTable ordering, because new MP3's cannot be created.

Now, we DO need to rescan for lyrics, so the possibly new lyrics file (in the case of Save As only) gets into the pathStack, but that should NOT require re-ordering the songTable.

This is a PITA when editing lyrics and there is a playlist in effect, because I keep losing the ordering by playlist.

**Comment by danlyke** [comment]
Yes, we're browsing the same scanning list, and it'd be worth keeping
those two lists separate.

**Comment by mpogue2** [comment]
This is related to saving (and restoring) the sort order.  But, the simpler and more correct version of a fix would I think be just adding the new Lyrics page (if Save As... is done to save as a new name) to the internal pathStack, rather than forcing a complete reload (which is what caused the resorting).  That was a quick and dirty hack (I'll take responsibility for that!), but I think it should be done correctly going forward...Erasum TechnicalDebtum!  (Aw...that didn't work...Im going to have to fix it for real...)

**Comment by mpogue2** [comment]
Fixed by 6f79b68f6be9028a1646c9892b555820d0fbbefc .
