### ISSUE TITLE
Feature: Girls/Boys OOO indicators in SD

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#507]
Just like we now have group/station indicators, add two new indicators for Boys and Girls in/out of sequence.  That will dovetail nicely with Bob Elling's system, and it's also for people (like Rich Reel) who go by in/out of sequence rather than couple 1 + 4.

**Comment by mpogue2** [comment]
Added via e6be8edba35aee3b6910e54af22f8489c8ef7c75.  Merged branch to mainline via e494a3b470d1fd7491933f288bad36582a57b82b.

**Comment by danlyke** [comment]
Looks like this is still in the `showOrder` branch?
