### ISSUE TITLE
Bug: SD resolves seem to be at challenge level

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#508]
Resolves at Plus level should not include Wheel Fan Thru's, Travel Thru, etc.

**Comment by danlyke** [comment]
Aha! My thread restart is obviously not setting the level in
the SD engine correctly...

**Comment by danlyke** [comment]
Closed with #498

**Comment by danlyke** [comment]
Looks like this can happen even in sdtty. Might have something to do
with the 'reconcile point'? If I do some basic plus sequence, type
'resolve', then 'raise reconcile point', I get all sorts of weirdness.

So if this is happening on the first few resolves, then then the
'reconcile point', whatever that is, isn't being initialized correctly.

I also think we need to add a better UI to resolves than SD has.
Something that automatically runs through some of the options and
presents them...
