### ISSUE TITLE
Bug: I can type "pass and roll" in (and it works), even though I am at Plus level in Dance Program 

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#511]
The A calls don't show up to click on, but if I type them in, they definitely work.  Is that the way that SD works?

**Comment by danlyke** [comment]
No, this is part of the getting the thread restart right (which I still
haven't done). I got the thread restarting, but on startup it should be
loading a specific level. It's still loading everything, and we're
restricting in the UI only.

**Comment by mpogue2** [comment]
Ah, OK...it's a work in progress then...I'll take the "?" off of "bug?"...thanks!

**Comment by danlyke** [comment]
closed with 498
