### ISSUE TITLE
Bug: Redo is broken

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#520]
In latest mainline/master, Redo does not work (tested on Mac OS, but I suspect it's similar on all platforms).  
Test case:
- Square your sets
- Heads start
- square thru 4
- swing thru
- undo (undoes the Swing Thru)
- Redo (Redoes the square thru 4, and it should redo the Swing Thru)

Also:
- Square your sets
- Heads start
- Square Thru 4
- Swing Thru
- Undo (undoes SQ4)
- Undo (undoes Swing Thru)
- Redo (Redoes BOTH the Sq4 and the Swing thru)

Could be an off-by-one error?

**Comment by danlyke** [comment]
Sigh. Thanks.

**Comment by mpogue2** [comment]
Might be related to this, Undo is not quite right, when going back to the start state:

- Square your sets
- Heads start <-- point A
- Square thru 4. <-- point B
- Swing thru
- undo
- undo
Screen shows result of point B, but should be result of point A.

**Comment by danlyke** [comment]
I thought I just fixed that one. I need to revisit this a bit to prep
for saving sequences off, I think I know what I'm doing on the flight
home on Wednesday...

**Comment by mpogue2** [comment]
Same as #440?

**Comment by danlyke** [comment]
Sure looks like the same as #440.

**Comment by danlyke** [comment]
Working way way better now, but I'm not gonna close this one yet because there's stuff around resolves and such that probably need more work.
