### ISSUE TITLE
Bug: Resolve is currently broken (doesn't show all calls in resolve call sequence)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#521]
Resolves are currently broken on mainline/master.  (They used to work, I don't know when this changed!)

Test case:
- Square your Sets
- Square thru 4
- Swing Thru
- resolve
Got: "right and left grand" in the resolve area, but just HEADS square thru 4 + swing thru in the list.   

Peeking at the SD Output, the resolver inserted an Acey Deucey, and then RLG is the right resolve.  But, the Acey Deucey used to appear in the Current Sequence list (IIRC) and now it doesn't.  I don't know when it changed.

**Comment by danlyke** [comment]
Thanks. I'll take a look, 'cause I was just starting to open this up...

**Comment by mpogue2** [comment]
Reported again and fixed as part of #774.  Closing.
