### ISSUE TITLE
Bug: Copy (Cmd-C) should work, even when lyrics are not open for editing

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#529]
Right now, the Lyrics need to be Open for Editing, in order for Copy to work.

**Comment by danlyke** [comment]
Hmmm... Wonder if we can attach a shortcut to that page so that Cmd-C also works correctly on the SD tab.

**Comment by mpogue2** [comment]
Fixed by 7b08dc88172e362b258abe3c9a785288046e3d96 .  @danlyke If you would like Cmd-C to work on the SD tab, I think this code shows the way (although because it's a special HTMLo or Special Formatted Text copy operation, and not a call to copy() on a QTextWidget, the code might be quite a bit more complex).
