### ISSUE TITLE
Bug: 0.9.3 crash on playback (one Catalina machine)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#532]
Rob B can't run on his Catalina laptop.  Crashes every time he tries to play a song.  I have no problems at all on my Catalina laptop.

I have removed 0.9.3 from Dropbox, until this is resolved.

**Comment by mpogue2** [comment]
I am in the process of binary searching the problem commit, with Rob B's help.  I will tag each commit as we go, e.g. "test_1", etc.

**Comment by danlyke** [comment]
You know about `git bisect`, right?

**Comment by mpogue2** [comment]
Results so far:
test_1, test_2: PASSED
test_3, test_4: FAILED
test_5, test_6: FAILED
So currently, problem is between test_2 and test_5.  It's definitely a bug that I inserted! :-)

**Comment by mpogue2** [comment]
I am suspecting 814023d13732ae340d1c9223658af0951dfd27f1, AND something that is specific to the way Rob B names files (which would explain why I never see this problem) but I don't see anything obviously wrong with this code.  I think it's unlikely to be any of the other 3 changes (two of them are sequence order for SD, which Rob B is not using, and the third is code that AFAIK only comes into play when doing a Save or Save Lyrics, which Rob B is not doing.

**Comment by mpogue2** [comment]
test_7 (6f79b68f6be9028a1646c9892b555820d0fbbefc) failed, which is weird.  There are only 3 changes left between test_2 (5898954896a0ce62608095c7a660a14223d87d60) and test_7, and they all seem like they wouldn't be executed at all in this case!

**Comment by mpogue2** [comment]
test_8 (d02bf1eed88d125d030aef45d5d80ab8e383f68a) fails, and test 9 (53870466ef935628f8ea0910bbdb6a5308522aac) succeeded.  The symptom is the same -- crashes the whole app when the second song is loaded via double-click.  I have no idea why the sequence code has an effect there.

**Comment by mpogue2** [comment]
Test10 fixed minor problem, FAILED.  Test_11 removed a bunch of code, FAILED.  Next test will remove yet more code, to see if we can get to PASS.

**Comment by mpogue2** [comment]
Test_12 also failed.

**Comment by mpogue2** [comment]
test_13 passed.  I don't know the exact cause, but the use of pointers and references, mixed with both std strings and QStrings is suspect.  

To that end, I am rewriting all of the Order stuff, and while I'm there, I am rewriting the Group-ness stuff, to not use any pointers or references, the functions will now just set member variables in MainWindow.  Much simpler, and hopefully this will fix the problem.

RobB isn't back until end of January, so we won't know until then whether this has fixed it.  But, I'll be able to test the latest version before he gets back, so it should be a "yes/no" thing when he can test it.  I still cannot duplicate the problem on my machine.  I have the same version of Catalina that he does.

Rewrite: 256400f9474fc158c5a2ea6805414f4d7fce8b38

And now, we wait.

**Comment by mpogue2** [comment]
I have provided Rob B with a test_14 version via Dropbox.  When he gets back, we hopefully will be able to close this one!

**Comment by mpogue2** [comment]
test_14 crashed.  That was the rewritten version.  Still crashes in the same way.
I provided Rob with a test_20, which is built in DEBUG mode.  Also, in looking at the previous stack trace provided by Rob, it looks like it died in QProcess::kill(), which is only called in two places.  One is to kill SD itself when the program ends, and the other is to kill the Replay Gain process, if it is running.  

I suspect that the SD process kill() is correct (because Rob is not using SD), but the other thing I think Rob *is* doing is using Replay Gain, which I do not use.  So, I've asked him to try turning off Replay Gain, with the DEBUG build, and let's see if we get any new information.  His symptom is that SquareDesk always dies only on the SECOND song load, which could be when we try to kill the old replay gain process (because the pointer is non-zero, because we used it on the first song).  I'm not at all sure why that would be related to the SD changes that I rewrote, but maybe it's some sort of initialization thing, as code is moved around in memory.

Even with ReplayGain ON for me, I have not been able to reproduce this problem on my Catalina laptop (same Catalina build as Rob, too).

I am not happy with the performance of replayGain, so one solution (if this is the problem) would be to remove it, rather than fixing the kill().

**Comment by mpogue2** [comment]
Debug version is test_20 (I restarted numbering at 20 for this new series of investigations).

**Comment by mpogue2** [comment]
OK, debug version 20 (which basically just turned -g at compile time) did NOT crash, no matter the settings of Replay Gain.  So, it seems that we might have a compiler optimization error, that shows up only in Release mode.  Or, it's a positional error, where changing the length of code blocks makes a difference to what gets clobbered by some memory access, which is then triggered way later..

I have asked Rob to tell me a) how many songs he has (in case that matters), and b) to send the stack trace from version 14 (to make sure that it is still crashing, at the same place, which was on kill().  I'm not sure whether it's the Replay Gain kill(), or if it's just a kill() that's called when the process seg faults. 

I hate bugs like this!

**Comment by mpogue2** [comment]
BTW, Rob does NOT normally run with Replay Gain on, so the kill code should never have been executed.  Since there is no failure in DEBUG mode, I'm not sure which kill() is being called.
Maybe I can put in an explicit crash at that kill() point?

**Comment by mpogue2** [comment]
OK, now version 14 is no longer crashing.  Weird.  Still tracking down.

**Comment by mpogue2** [comment]
OK, I know what's happening.
When ReplayGain succeeds, that value is saved in the sqlite DB, and ReplayGain is not run on the file a second time.  But, the pointer mp3gain was also NOT initialized to nullptr.  So, when it happened to be zero, everything was fine, the ReplayGain process was started, it finished, and the pointer was then set to zero.  But, if it was NOT zero, we would try to kill() the existing mp3gain process (because we're going to start up a new one).  Because the pointer was non-zero, code thought is was valid, and dereferenced it, thus CRASH.

Apparently, the change to the SD code for displaying B/G in/out of order moved code around so that the uninitialized mp3gain pointer went from defaulting to zero to defaulting to non-zero.

To make things even worse, when I rewrote the SD code that I suspected, it still failed on Rob's machine.  So, I made a DEBUG version of that same code, so that I could get a better stack trace.   That code not only succeeded, but it set the ReplayGain value in the sqlite DB.  So, when Rob went BACK to the original failing version, it NO LONGER FAILED, because ReplayGain was already figured out, so the ReplayGain function wasn't called at all.  So, moving things around in memory caused things to succeed, which then covered up the original problem with version 0.9.3 (the uninitialized variable for the ReplayGain process pointer).

So, confusion ruled the day.

I just happened to have added a new song in my Patter directory, and I just happened to use version 0.9.3 to play it.  It crashed instantly and repeatedly.  But, then when I tried the test_20 version (debug, rewritten), it succeeded (!!).  Then, going back to version 0.9.3 then SUCCEEDED.  Ah hah!  I was able to reproduce that test case by duplicating the new song, and trying the original 0.9.3 (crash), then test_20 (fine), then original 0.9.3 again (fine!!).  If I started with test_20 (fine), then original 0.9.3 would not ever fail on that song.  But, if I duplicated the song, then the original 0.9.3 would fail.

Interestingly, while test_20 DEBUG worked fine the RELEASE version crashed.  BUT, it gave me a stack trace this time (unlike on Rob's system), which pointed directly at ReplayGain_dB as the last call before kill().  So, we're definitely dying inside that function, when we try to kill() the existing process.

Code inspection showed this:
`    if (mp3gain != nullptr) {
        qDebug() << "ERROR: an mp3gain process was running...killing the old one.";
        mp3gain->kill();  // kill any running instance, before starting another one
    }`

So, mp3gain pointer must have been non-null, which should have been impossible at program start.  Manually checking showed that mp3gain was never manually initialized, and I was counting  on the compiler to set all fields to zero.  That was true SOME of the time, but the SD code caused that to be false.

Added initialization in the constructor, tested it with a brand new song, no crash.  Removed that code, tested with a brand new song, CRASH.  So, the test is definitive, and all observed behavior is now explained:

- Rob's crashes were probably because he was testing with new songs
- My lack of crashes was probably because I was testing with old songs, that had ReplayGain already (and also, I had ReplayGain turned off -- but turning it on had no effect, because the songs already had ReplayGain in the DB)
- DEBUG version didn't crash, because code expanded.
- 0.9.3 RELEASE version crashed, because code was different in memory from previous versions.
- Once the DEBUG version was run, we had no more crashes on THAT song, because it succeeded once, and that was stored in the DB.

Q.E.D.

**Comment by mpogue2** [comment]
f0b625f35ef7c5adac85069ec94053ad04f01014 is the fix for this.  I also removed an unnecessary ";" while I was right there, to eliminate a compiler warning about empty statements.

**Comment by danlyke** [comment]
There are some days when I think "maybe we should rewrite all this in Rust.
Or JavaScript."

**Comment by mpogue2** [comment]
@danlyke LOL.
Closing, since it's fixed now.  WOW what a PITA to track down.  Live and learn!
