### ISSUE TITLE
Bug: build is broken, due to missing files

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#548]
ad03dc272884bc7fa06a91cd028a78f904cbe93b added two files, sdformationutils.{c, h}, and they are not checked in.  So, the build fails.  

I can't just comment out those #include lines, because it looks like code has moved from mainwindow_sd.cpp to the sdformationutils.c file.

**Comment by danlyke** [comment]
Doh. Sorry. Checked in.

**Comment by mpogue2** [comment]
Thanks!
