### ISSUE TITLE
Feature: incorporate sqView lyrics DB

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#55]
We have permission from Thomas Bernhed to incorporate the SqView Lyrics DB into SDP.

Two things:
1) Lyrics matching should be fuzzy, so that almost all cue sheets can be found
2) Remember to fix the other problems around apostrophe, et.al.
3) Remember to fix the umlaut problem with German lyrics.  

The problem is, as I recall, that Qt expects the database to be UTF-8, and the SqView database is Win-1252.  Data is lost in the conversion, so special techniques need to be applied here to get these imported correctly.

**Comment by danlyke** [comment]
I'm sure we can override Qt's default character set. What I'd like to avoid is pulling in libiconv for the character set conversion... But I think we can hard-code a Win-1252 to UTF-8 table if we can get it to not munge the database inputs.

**Comment by mpogue2** [comment]
As I recall, the problem is that the translation to Win-1252 actually loses data, and it's impossible to go back.  IIRC, it translates two different characters to the same byte.  Can't undo that easily (maybe in context of every possible German word, it might be possible to do it, but not one character at a time).

**Comment by danlyke** [comment]
Looking at the cuesheet database, specifically `sqlite3 sqview.db` and typing `.schema cuesheet` and 
`select * from cuesheet limit 20;`, it looks like basically it's got "label" which is the label abbreviation, a space, and the song number, "title", which is the song title, "labeltitle" which is those two joined with " - ", and a path to the cuesheet filename. Which is named like "labeltitle".

So if our label and title parsing capability is up to snuff, using the database is superfluous.

There might be information in the database that'd be useful for migration, like last time songs were played and such, but I don't think there's anything there that'll help us with cuesheets.

**Comment by mpogue2** [comment]
DMM appears to be using unpacked crushers from squareview...do those song titles match?  Also, let's check for the umlaut problem in the German ones...

**Comment by mpogue2** [comment]
Hmmm...in the SqView DB, the umlauts are encoded incorrectly, but they are correct in the HTML file.
Example: "GP 944 - Zieh Die Schuh Aus.html"

**Comment by danlyke** [comment]
I'm clearly missing something. It looks to me like the database is in
pretty good shape, but the cuesheets are screwed up.

The file name is:

GP 944 - Zieh Die Schuh Aus.html 

The entry in the database is:

$ sqlite3 ~/Downloads/sqview.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from cuesheet where labeltitle like 'GP 944%';
GP 944|Zieh die Schuh aus|GP 944 - Zieh die Schuh
aus|HTML|C:\SqView\Text\GP 944 - Zieh die Schuh aus.html
sqlite> 

The cuesheet itself appears to be Windows encoded, the "&auml;" is
represented as <E4>, lynx displays it as:

Ich bin ein sammler, ein jger - Ein guter ernhrer

Firefox figures out the character encoding:

Ich bin ein sammler, ein jäger - Ein guter ernährer

**Comment by mhkull** [comment]
Firefox is correct - Greetings from Baden-Baden, Germany

**Comment by danlyke** [comment]
But Lynx is also correct: The HTML 5 specification states that the default is UTF-8 encoded, and a solo E4 byte is not a valid UTF-8 encoding. Dropping the invalid character is correct. :grinning: 

The problem is that up through HTML 4 it was reasonable to assume ISO-8859-1 (aka "Latin1") character encoding, although the document should specify encoding, but in modern HTML the spec explicitly states the default is UTF-8.

I guess I'm asking for a little clarification: Is the complaint about the SqView database, or the cuesheets?

Because I'm looking at the database and not finding the problem. But I do see that we need to load the cuesheet, look for things that might be ISO-8859-1 that are invalid UTF-8, and assume the document is the former (and maybe look for HTML <head><meta...> character specification too).

I just don't know if that's this issue or not.

**Comment by danlyke** [comment]
Okay, so with the new cuesheet matching in 0c19655630ede27396235dfe424728df4b64c2a8 which fixes #86 , how far off are we on this?

**Comment by mpogue2** [comment]
I take back the suggestion to use the DB now that the raw cuesheets are available!  They do not have the umlaut problem.  So this mutates into "include the sqview cuesheets", or provide a way to auto download them...

**Comment by danlyke** [comment]
So do we need some sort of "rsync" like capability? A way to scan an archive on our website, see what cue sheets are missing from the user's machine, and sync?

This might be something that needs to set on hold until we can get the smart cuesheets thing worked out... which I'm thinking about.

**Comment by mpogue2** [comment]
Maybe...the cue sheets are pretty large, so it would be nice to have a "sync latest cue sheets" item, and a "new cue sheets are available" indicator.  That way the download of cue sheets might be done separately.  Could be rsync, or something similar...

**Comment by danlyke** [comment]
So actually: I think what we want is a "find cuesheets for songs I
have". That way my computer doesn't have to have 20k cuesheets lying
around waiting for a match-up.

**Comment by mpogue2** [comment]
Yep maybe so.  Although that's the way others do it!  :-). Internet fetch would be nice.

**Comment by mpogue2** [comment]
OK, I'm gonna close this one, since we have downloadable ZIP files of sqView cuesheets now.  I'll open a new one for "find cuesheets for songs I have", kind of a "sync" operation.  That would reduce the cuesheet footprint on disk by a lot, and it's also better than keeping the packed ZIP file around.
