### ISSUE TITLE
Feature: random colors (with and without numbers)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#585]
Time to make it even harder to resolve. :-)

Members of the Caller's Study Group would like random colors, so we can practice resolving without the help that colors gives us.  I'm adding that with and without numbers (even harder!).  Maybe someday we need to have an option for not using gender markers either (rounded edge squares, anybody?)....

Am choosing a color-blind-friendly palette, too.

Oh, and every time I select Random, it scrambles the colors.

**Comment by danlyke** [comment]
This seems like even more reason to integrate Taminations and ask Brad to
do it :-D

**Comment by mpogue2** [comment]
Yeah, I'd love to get onto Taminations.  In the mean time, I really like being able to make small changes like this quickly!  My Caller Study Group uses SD in SquareDesk every week, and the SD customizations that we've done are super effective.

This one was committed as 172fb60c6e0bc508d7cbe6056d71bcfae2f61bca .
