### ISSUE TITLE
Bug: Update copyrights for 2021

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#593]
I have a script that does this somewhere.

**Comment by danlyke** [comment]
perl -npi.bak -e s/2020/2021/g *.{cpp,h}

**Comment by mpogue2** [comment]
That would have been a bit too aggressive (the sequence '2020' occurs in a lot of the SD files)...

On Mac, I used this instead, which is a bit more qualified, and can be used from the root source directory:
`find -E . -regex ".*\.(cpp|h)" -exec sed -i '' 's/2020 Mike Pogue/2021 Mike Pogue/g' {} \; -print`

Fixed by: 1e083233b5f3df10d0abba360497f626740e249b

I also turned off compilation of html-tidy, which is actually compiled outside of QtCreator, and the lib is manually copied to SquareDesk-DEV/local/lib for linking.  That problem cropped up when I recompiled after making the copyright changes.

**Comment by mpogue2** [comment]
Ooops.  Forgot to update the splash screen.
Here's how to do it:
1. Use Affinity Designer ($50) to open the .afdesign file in test123/graphics.
2. Change the date by editing the text field.
3. Export to SplashScreen1.png, 320x240 pixels.
4. Check both files in.
5. ...
6. Profit!

Fixed by: 9a1f2950bf4623e5f077a1e1c7702209e25bee28
