### ISSUE TITLE
M1: figure out how to get kfr checked into our tree

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#618]

**Comment by mpogue2** [comment]
Until we can figure out why I can't commit this code here, I stuck a ZIP file into the tree.
a6dd4fff0149b1bae8289b80296bede9ddb3145e
The kfr/ directory should be at the same level as test123/ .

**Comment by mpogue2** [comment]
@danlyke Could you help me understand why I can't just commit this entire directory to the flexibleAudio branch?  I think it has something to do with it being a "submodule", but I don't know how to get rid of that.

**Comment by danlyke** [comment]
If you don't wanna go the whole submodule route, you'll have to remove the
.git directory from within that folder...

**Comment by mpogue2** [comment]
Hmmm...I tried that.  I think that git thinks the the repo is the remote kfr repo, rather than mine.  Or, maybe it's at the wrong level of the tree?  Not sure how to fix this.

**Comment by danlyke** [comment]
Unless something has changed in the SquareDesk/.git directory,  the only
way it'd know about the kfr repo is if  .../kfr/.git still exists.

**Comment by mpogue2** [comment]
OK, I tried something different.  
First, in 3835a446f51b8c0fb1ecb6fd5b6254c5a6cda300, I removed the kfr directory, to get it deleted from git.
Second, in 9dcabbb1ed211192ca08ef1ab17ad2345c24b3ea, I added back the entire kfr directory.  Git could see it, and I just committed the whole thing.  This seems to have worked.

Now, on the X86 side, I did a git clone of a later version.  So, there's probably a third step here, to git clone the latest kfr, and then check THAT in as an update.  Then, we can delete the build products of kfr, so that when we compile on both sides, we won't disturb git.

What a pain.  But, I did want to get the source code in there for sure this time, rather than allowing it to be outside the build process.

**Comment by mpogue2** [comment]
Nope, didn't work.  GitHub shows it as an arrow on a folder, that can't be clicked on to look inside.
Gitkraken still thinks I committed 759 files.  So, where are they?

**Comment by danlyke** [comment]
A place for a git submodule?
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by mpogue2** [comment]
OK, it WAS a submodule, and that appears to have been the problem.  I'm not quite sure what I did, but it is NO LONGER a submodule, and the kfr code looks like it's there, along with the binaries that I checked in, too (lib subdirectory).  Closing this one as FIXED.
