### ISSUE TITLE
Cleanup: Consider using #pragma once rather than standard .h header #ifdef guards

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#622]
We already have a bunch in #pragma once's in there.  Do we have support on all platforms?  It's simpler.

**Comment by danlyke** [comment]
So long as we remember the stuff that proxies the various settings attributes back and forth that involves including those particular files multiple times, in different `#define` contexts

**Comment by mpogue2** [comment]
Oooh, good point.  I forgot about that!

**Comment by mpogue2** [comment]
What @danlyke said.  Closing this one to get it off the list.
