### ISSUE TITLE
Bug: filter then backspace causes selected item to highlighted white on white instead of white on dark blue

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#630]
White on white.
To replicated:
1. Select first item in song table
2. create a filter that does NOT contain first item
3. hit backspace to erase the filter one char at a time
4. when you get to NO filter, the colors are messed up, and the highlighted item has the WHITE TEXT from highlight, 
but is missing the BLUE background.

**Comment by mpogue2** [comment]
This bug DOES exist on the Qt6.3 FlexibleAudio branch on M1.

**Comment by mpogue2** [comment]
This white-on-white thing has been a bug in Qt for a while now.
But, I bet that we can manually set the color of the text when this happens, to work around it.  It's just annoying.

**Comment by mpogue2** [comment]
It seems to be related to which row is selected, when we filter and then stop filtering.  Whatever row was selected (highlighted in blue background with white letters) puts the background back to the NON-selected color, but the color of the letters remains white (SELECTED color).

This is still a problem with Qt6.4.1 .  Maybe we can work around it by reselecting a row whenever the filter changes?

**Comment by mpogue2** [comment]
OK, the root cause of this bug is this code in filterMusic(), not really a bug in Qt (although this could be considered a limitation of the existing Qt implementation):

```
    if (rowsVisible > 0 && rowsVisible != initialRowCount && firstVisibleRow != -1) {
        ui->songTable->selectRow(firstVisibleRow);
    } else {
        ui->songTable->clearSelection();
    }
```

Here's what this does:
- User selects a row A (it highlights)
- User changes Type, Label, or Title filters to something that would NOT show the selected row.
- This code changes the selection to the first row in the set of rows that IS shown (let's call it "row B", which highlights).  Navigation with UP/DOWN arrows is possible in this filtered view.
- User deletes characters from the filter, or presses Clear Search.

Now the question is "what SHOULD happen?".

1. Ideally, Row A highlights again.  But, that implies that we remember the selections as the filter changes, and we put the selections back as the filter gets simpler.  This is painful.
2. We could remember the highlight with NO filters, and restore just that, when we detect that all the filters are gone.  If there are filters, we could start out with first visible row selected, IF AND ONLY IF the selected row with no filters is NOT currently visible.

If we comment out this code shown above, the white-on-white problem goes away.  BUT, then when we delete filter characters, we don't get Row A highlighted again AND we don't get UP/DOWN arrow behavior at all on the filtered results either, because Row B isn't highlighted either (Row B would have to be manually clicked on by the User).

**Comment by mpogue2** [comment]
Option 2 isn't great either, because of this use case:

- User does filter.
- User clicks on Row B.
- User adds to the filter.  Row B selection is forgotten.

**Comment by mpogue2** [comment]
3. When filter changes (in any way), IF selected row is not visible, change selection to first visible row, ELSE leave selection alone.
I think this is probably closest to what is expected.
ADV: Can always use UP/DOWN arrows to change selection, regardless of filter.
ADV: No white-on-white problem.
ADV: selection is persistent, as long as it still is visible in the songTable.  
ADV: Changes to selection in a filtered view persist into the unfiltered view.  (not currently the case!)
DIS: filter then unfilter doesn't restore previous selection (but I suspect that this "restore" behavior is not really expected).

**Comment by mpogue2** [comment]
After playing with it for a while, Option 3 does not feel like it's correct.

What feels (most) right is Option 4:

4. When the filter changes (in any way), If there are any visible rows in the table, select the first visible row.

ADV: Can always use UP/DOWN arrows to change selection, regardless of filter.
ADV: No white-on-white problem.
DIS: filter then unfilter doesn't restore previous selection (but I suspect that this "restore" behavior is not really expected).
DIS: selection is not persistent from filtered to unfiltered (but that's also not how it works today, so this is really not expected)

**Comment by mpogue2** [comment]
4 (continued). 
- When Clear Search is pressed, title search field should get focus.  
- When ENTER/RETURN is pressed, after the song is loaded, focus should be restored to what it was before (rather than clearing focus).  Generally this means either a search field, or the songTable will have focus.
- When PLAY is clicked, focus should not go to nothing (current implementation), it should go to the songTable.  When STOP is clicked, focus will be restored to what it was when PLAY was clicked.  UP/DOWN arrows are now active during playback, because songTable has focus.  Keys like P and period are NOT swallowed, not because there is NO focus, but because focus is NOT one of the search fields.

**Comment by mpogue2** [comment]
OK, this was a complicated problem, with a complicated fix.

There was a race condition between several things all at once:
- loadMusicList was getting called multiple times, once explicitly, and then again by the "Tags are on" checkbox, and then yet again by Box.net detecting a lock.txt file change, and putting its own locks in every subdirectory (and then deleting them).  So, we were getting between one (correct) and three (bad) songTable loads at EVERY startup.
- And, every time the musicList was reloaded, there was a race condition where the setting of the color of the first item in the table (the selected item) was either correct (set to white) or incorrect (NOT set to white, so just the default color for that song type).
- There was focusChanged code, designed to reinstate the "nothing has focus" when you go to another app, and come back to SquareDesk.  This code did NOT always work correctly.  And, it is no longer needed now, because I fixed:
- When hitting ENTER/RETURN to load a song (now allowed BOTH when the cursor is in a search field AND when the songTable has focus), sometimes the title field didn't regain focus, and neither did the songTable, so UP/DOWN arrows would suddenly stop working, until the user manually clicks on something.
- And, there was a songTable stylesheet that dealt with selected rows, BUT we are using QLabels for the Title fields of each row (so we can do Tags), and those used a manually-set stylesheet on each one when the selection status changed, BUT that was racing with all the other things.

I think I fixed all of that, BUT this becomes a major change now:
- The songTable now uses EXPLICIT SPANs to control the color of titles in the title column, rather than stylesheets on the QLabels.  That means that text in the QLabel now contains ONE or MORE spans: one for the title, and zero to many for the tags.
- But, because the FormatTitlePlusTags function also deals with converting (for example) ampersand to ampersand a m p semicolon and back again, I used a stupid hack to stick in the new explicit span, so that I didn't have to modify FormatTitlePlusTags (which would have had to know about whether the item was selected or not, as well as the foreground color).
- That hack unfortunately was needed in 3 places, not one, because editing of tags also sets their text.
- BUT, the hack was somewhat simpler for editing of tags (two functions), because at that point we know that the text MUST be white (the text highlight color), because we can only edit tags on rows that are already selected.
- While I was there, I got rid of the extra loadMusicList() due to enabled tags (removing the initial explicit call to loadMusicList(), which preserves the loadMusicList() when Tags are turned off and on), AND the extra loadMusicList() initiated by Box.net scanning over directories.  The latter was done by giving box.net 2 seconds at startup to scan, before turning on the FileWatcher.  This should make the initial load faster!
- I made sure that the explicit spans were removed from the "search for titles", too.  So, typing "span" into the titleSearch box actually filters correctly, rather than leaving everything visible (because there's a span on every single title now).  This requires a bit more tag removal than was there before, but it's just one extra line of code.

In my testing:
- the first item in the songTable now always has the right color.
- ENTER/RETURN works correctly everywhere now.
- The focus when music is playing is now the songTable (not "nothing"), and it's restored properly when playback stops AND when going to a different app and coming back.
- white-on-white highlighting doesn't happen anymore
- after a loadMusicList, the first item in the list is always highlighted and the titleSearch field has focus, enabling UP/DOWN arrows without clicking anything.

Sorry for the added complexity, but I think in this case it was necessary.

Commit:d94f456bbb745a17d74abc84e48d92ef883c0198

**Comment by mpogue2** [comment]
I couldn't leave in that horrible string hack.  Removed by: 24bb91b188b6f456a008bbb0a4ba61d663512918 .

**Comment by mpogue2** [comment]
Closing, since I think this is now working fine.

**Comment by mpogue2** [comment]
I've seen this problem occur with the latest top-of-tree.  It's rare, but it still happens.

**Comment by danlyke** [comment]
Speaking of white on white, dark mode on Linux is kinda funky, so there's
some other font color stuff needs to get worked out, and moving the default
color to be the system font color would be nice.

**Comment by mpogue2** [comment]
@danlyke I'll open a separate Issue to track Dark Mode, since that's probably a bigger set of changes...

**Comment by mpogue2** [comment]
This problem is back now in the 1.0.5 release.
