### ISSUE TITLE
Feature: Hot key to "Peek @ lyrics for next song"

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#646]
Here's my use case:  I am calling patter, and I want to teach the singing call figure.  But, I can't switch the the singing call Lyrics page, because that involves loading the singing call, which will stop the current patter music.  What I really want is to be able to "peek" at the singing call that is next in the songTable (generally next on the Playlist).  Then, hit that key again to get back to the main playback tab.  I would use this almost every tip that has a singing call in it!

**Comment by mpogue2** [comment]
Regina likes this idea, too.

I think auto-scroll needs to be auto-disabled, if a cuesheet is brought up this way while patter is playing.

**Comment by sharmanr** [comment]
Suppose we introduce a new button in the lyrics tab that toggles a "sticky" state.  It is initially off and we can turn it on when a singing call is selected and its lyrics are shown.
Now we select a patter song;  if the sticky state is on we don't search for lyrics/sequences for this patter song but re-display the last shown lyrics (the one for the last selected singing call).
When the state is on and a different singing song is selected we should search for its lyrics (as happens now).  Should the sticky state be left on or cleared?  In either case, the new button should reflect its state.   Originally I had thought it should be cleared, but now I think keeping its state would generally be more useful.

**Comment by sharmanr** [comment]
Just to clarify, I had intended just before selecting the patter to select the music song to make the lyrics "active";  then select the patter.  That's why I had called it "last shown".  If you're really well organized the next in the playlist would be fine.  The last couple of weeks when calling I had to change things at the last moment so the original playlist wasn't what actually happened!

**Comment by mpogue2** [comment]
Hmmm.....yes, I definitely change the order or which singer I will use on-the-fly, too.

I would like to retain the "make it as automatic as possible", if we can, but I can see where we might want to override that directly at tip time, and that override should be simple-to-do.

Maybe something like this would work?
- Get rid of Patter cuesheets.  The tab would always be called "Lyrics" going forward.  Nobody was using the patter cuesheets anyway (there are so few, and they can be viewed in a browser, and card readers are going to use the SD tab going forward anyway, hopefully).
- Default is that "if you're in a playlist, and the song AFTER the currently-loaded song is not a patter song, then the Lyrics tab will be loaded automatically with that cuesheet".
- AND, maybe there's a Right-Click context menu option called something like "Load Cuesheet", which would override the automatic load, and would load the Lyrics tab with THAT cuesheet.

Then, the use case action would be something like this:
1. Load the patter, as normal.
2. If in a playlist, and it's followed by a singer, AND you DO want to do that singer next, then GO TO STEP 4.
3. Otherwise, right click on the singer you want to do next in the songTable, and select "Load Cuesheet".  That cuesheet will be loaded, and a "*" appears on the Lyrics tab name (indicating that there is a cuesheet there).
4. Start playback (with Cmd-P or Period or Play button), as normal.
5. When you want to view the cuesheet, press "T", as normal.  "T" will toggle back to the Music Player tab, too.

ADV: no preference needed!
   Default is fully automatic.
DIS: less discoverable (because the cuesheet override is in a context menu, which isn't obvious)

@sharmanr How about something like that, perhaps?  Thoughts?

**Comment by sharmanr** [comment]
Excellent!  I think you have covered all bases here.  
One minor correction:
**If you're in a patter song and** in a playlist, and the song AFTER the currently-loaded ... etc
(You wouldn't want to do this if you were in a singer and the next in the playlist was a singer!)

**Comment by mpogue2** [comment]
@sharmanr Good point, nice catch! :-)

**Comment by mpogue2** [comment]
I believe this one is already implemented, so closing!
