### ISSUE TITLE
Bug: ordering of searching for lyrics

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#65]
Prior to ffe6aa9a0d0578c78d685dd733fd9f59793dde6a, the search order used to be: 
1) File system (right next to the file)
2) USL section (Unsynchronized lyrics section in the MP3 file)

Currently it's:
1) File system (anywhere in the music directory), scored by relevance

Instead, I think the priorities might want to be:
1) File system (right next to the file) -- Why? intentionally overrides the internal USL section
2) USL section (Unsynchronized lyrics section in the MP3 file) -- Why? specified by the Music Producer, OR the user actually edited in the Lyrics using e.g. iTunes.  One of our main users does this.
3) File system (in the Lyrics subdirectory), scored by relevance -- Why?  This is the backstop for files that don't have an internal USL, and where the user hasn't intentionally stuck one in the same directory to override the USL.  For example, people can get many cuesheets from the DMM folks, and they would stick them in here to use them.
4) sqview.db (built-in DB) -- Why?  This is the backstop of the backstop.  We have permission to use this now.

**Comment by mpogue2** [comment]
See also #35, #55, #63.  This search ordering might address all of these at once.

**Comment by mpogue2** [comment]
I will send you what David Dvorak sent me for testing, which has embedded lyrics...

**Comment by danlyke** [comment]
I just pushed a change which *should* load the lyrics, but I'm not sure because not only do I not have a lyrics MP3 file, the Linux version doesn't load the lyrics. It looks like only taglib v1 is packaged for Ubuntu, and that doesn't have some of the include files that are referenced in the lyric loading code.

**Comment by danlyke** [comment]
Oh and: I thought I made the scoring prioritize the cuesheet next to the file, and now it should prioritize the file itself if it actually has lyrics.

So if this is working now (again, can't test 'cause Linux) then maybe we close this and open a "make embedded lyrics work on Linux" issue.

**Comment by mpogue2** [comment]
I'll give it a try!

**Comment by mpogue2** [comment]
OK, if the MP3 file has lyrics in it, it shows up at the top of the drop down list correctly.  And, if I select it in the list, the correct (embedded) lyrics show up.  However, the item that is checked in the list is the **second** item in the list, which is one of the .html files that was also found.  It should have been the USL section, which was item 1 on the list.

**Comment by mpogue2** [comment]
OK, when I switch to a second singing call that has a lyrics .html file right next to the song, the correct lyrics (from that file) show up, but the dropdown list still includes all the files pulled up by the PREVIOUS song.  And, that second one (from song # 1) is still checked, even though the correct lyrics for song # 2 are showing, and the correct item is lower on the list.  See screenshot below (I hope I embedded the screenshot correctly!)....
<img width="1280" alt="screenshot 2017-04-22 14 17 07" src="https://cloud.githubusercontent.com/assets/6316003/25308331/6d0f7132-2766-11e7-95c9-3e40cfc9dfd6.png">

**Comment by mpogue2** [comment]
Note: I just pushed the merge from the danlyke branch to Master anyway, because the lack of the tag lib header files makes it hard to test your branch.  You must have those header files on your Linux system still around from a separate install...

**Comment by mpogue2** [comment]
One more thought:  I think if there are several choices, and the top scoring cue sheet is not right, or I prefer a different one, and I change my choice in the dropdown, that choice should ideally be persistent in the db.

**Comment by danlyke** [comment]
On Sat, 22 Apr 2017 15:03:54 -0700
Mike Pogue <notifications@github.com> wrote:
> One more thought:  I think if there are several choices, and the top
> scoring cue sheet is not right, or I prefer a different one, and I
> change my choice in the dropdown, that choice should ideally be
> persistent in the db.

Yes, that should be the case now. If it's not, then I've got yet
another bug...

Dan

**Comment by danlyke** [comment]
Fixed and pushed the cuesheet not correctly clearing with d3269cdf3d143c28c40c958b16e4f96bac7157ea

**Comment by danlyke** [comment]
And on my computer... it appears to be correctly remembering which cuesheet was last used, even if that isn't the top scorer.

**Comment by mpogue2** [comment]
OK, here's what I found:
1) dropdown is properly cleared now!  Thanks!
2) If I select something in the dropdown and then QUIT, it does NOT remember what I selected.
3) I really would like the disclosure triangle setting in the lyrics tab to be persistent, that is, if I open it and quit the app, it should be open again when I come back into the app and go to the Lyrics tab.

**Comment by mpogue2** [comment]
#3 is really a new feature request...so, I'll split it out into its own Issue.

**Comment by danlyke** [comment]
Argh. Mine is remembering it.

It should be in the "last_cuesheet" field in your database, if that's
any help...

**Comment by mpogue2** [comment]
Lemme check.

**Comment by mpogue2** [comment]
No, it's not remembering the choice, if I make a non-default choice, and then quit.
The DB entry is NOT being set when I quit the app.  It *is* being set if I switch to another song (that has lyrics) and then switch back, without quitting the app.

**Comment by mpogue2** [comment]
Oh, and another bug popped up:  If I load Tennessee River (that has cue sheet right next to it in the singing directory), lyrics tab is correct.  Then if I load King of the Road (Instrumental) which does not have matching lyrics (the Lyrics tab name does NOT have  *), the Tennessee River lyrics still show up in the Lyrics tab.  It's not being cleared out on load of a new song.

There's probably also a reason why C 303 - King of the Road (Instrumental) is not matching any cue sheets...Oh yeah, it's because the cue sheets are:
./lyrics/SqViewCueSheets-9-30-16 Text/C 0303 - King Of The Road.html
and the song is 
./singing/C 303 - King Of The Road (Instrumental).mp3 .  Extra zero, and something additional in parens...

**Comment by danlyke** [comment]
Aha! Okay, this means there's other stuff likely not getting remembered.

**Comment by danlyke** [comment]
Fixed in 51fc9ed538a20cd8553063655990983b7668a8a5 , saving song state when the app is closed, not just on song changes.
