### ISSUE TITLE
Bug: "Square your sets" should be allowed in text form, too.

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#66]
Right now, you can say "Square your sets" via voice input, but you can't say the same thing via the command line.  Internally, voice input of "Square your sets" gets turned into "<ctrl-U>; <ESC>; Abort this sequence; Y" which always brings you back to a squared set (even if in the middle of typing something).  But, via the command line, SD doesn't understand this.

This is an SD modification, and in general I've been resisting making too many changes to SD, but I think this is one that people might expect to be there.  I've already been asked about this today...  TODO: Ask Bill A why this wasn't done in SD before?

**Comment by mpogue2** [comment]
I think this is an Enhancement, so removing the Bug Label.

**Comment by danlyke** [comment]
7c78e31f34d80e65425a12805d6bde71fb1c34d7 fixes this.
