### ISSUE TITLE
Bug: Saving Lyrics should not wake up the Filewatcher

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#667]
It takes a while, AND it messes up the current sort order of the songTable.  Annoying.

**Comment by danlyke** [comment]
Related, I think some of the performance issues we were seeing on Windows was the filewatcher kicking off for database writes.

**Comment by mpogue2** [comment]
Fixed by turning off the Lyrics FileWatcher for now.  See #659.
