### ISSUE TITLE
Bug: aliases with the same basename as the original will make the song unplayable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#67]
To reproduce:
1) Put an MP3 file, "foo.mp3" into the singing call directory.
2) Make an alias of it, and put the alias into the "patter" directory.  Typical thing for people to do.
3) Rename the alias from "foo.mp3 alias" to "foo.mp3".  Now it will be detected as a normal MP3 file, and will show up in the songTable.
4) Unfortunately, attempting to play the song as patter will now make impossible to play either the patter or the singing call version of the song.  Everything looks like it is playing, but nothing comes out of the speaker.  Only solution is to delete the entries in the DB.
5) Workaround: When the alias is created, it must have a different basename.  e.g. "singing/foo.mp3" must be something other than "patter/foo.mp3", e.g. "patter/foo 2.mp3" would be fine, and everything works as expected.

This one is nasty, because it requires a manual database operation to make the base file playable again.

**Comment by danlyke** [comment]
We are apparently doing the wrong thing with symlinks: In my Patter directory:

`ln -s ../Singing/You\ Wear\ It\ Well\ -\ ACME-103.mp3 ./`

gives be two "Singing" entries for "You Wear It Well".

Hard links do the right thing.

**Comment by mpogue2** [comment]
I just did a Make Alias on Mac OS X, which is probably a soft link...I don't know whether there's a GUI way to make hard links.

**Comment by danlyke** [comment]
Take a look at b949e669a817053d60ca949cfa16df7523acfd9a

The notion here is that "canonicalPath()" resolves all the symlinks, where "path()" doesn't, so the latter leaves the symlink there in a place where we can use it for type. I think this works, but it'd be nice to have someone else think a little bit about possible issues with it, and test it on Windows & Mac.

**Comment by mpogue2** [comment]
Verified fixed on Mac OS X.  Now that it works, I'd like to eliminate the required step of deleting the " alias" at the end of the alias name (Mac OS X).  I'll open a new ticket for this, since it is a new feature request, not a bug.
Nice fix, thanks!!

**Comment by mpogue2** [comment]
I spoke too soon.  I'll open a new bug on the weird behavior, since the original bug "is not playable" has been fixed.
