### ISSUE TITLE
Feature: Loop (vs not loop) should be a persistent setting

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#70]
Loop setting right now is this:
if (type == patter) then Loop
else no Loop
This would be a fine default value, but if I change it, it should remember the change in the Sqlite3 DB.

**Comment by danlyke** [comment]
I have a patch for this that I haven't pushed yet in the importexport branch (because that reworked how song settings got set), but I'm not sure how I feel about it yet: I think I want my patter music to always default to looping. Otherwise it's one more thing I have to set when I start my music...

**Comment by mpogue2** [comment]
I would have agreed until I bought riverboat patter.  They are designed to NOT need looping since they are longer. How about default is that patter loops, unless manually turned off by the user?

We might also want to extend to:
Don't loop, loop once, and loop forever.  Three states.  Or 0 is no loop, 1 is one loop, etc, and -1 is forever.  Internally.  We can still have a tri state loop to start...

**Comment by mpogue2** [comment]
Importexport branch is now merged...did you decide to take out the persistence of Loop?

Here's another possibility:  
right now: default to if (patter && songLength < 5min) then LOOP else NO LOOP
if user changes it, then the user's preference wins, and it persists.

This algorithm works for all my Riverboat patters, which are all >5:00 in length.

or, is that too confusing that some patters are auto-looped and some are not?

**Comment by mpogue2** [comment]
I'm thinking that the best algorithm is the last one above (that I think will work for both of us?):
if (not_ever_changed && patter && songLength < 5 minutes) then default to LOOP else default to NO LOOP;
If user ever changes the setting, the user's new preference for that song wins, and it persists in the DB.

Dan, if you point me at what needs to change, I might take a whack at this one.  I really could have used it at last Saturday evening's hoedown...  Or, if you have time to look at it, that would be great...

**Comment by danlyke** [comment]
Database is...

Add the setting to the SongSetting class and the table (ie: copy and
paste tempo or something).

Set it appropriately in mainwindow.cpp, I think it's
"saveSongSettings(..)".

Reload it in mainwindow.cpp!

**Comment by mpogue2** [comment]
OK, working on this now...

**Comment by mpogue2** [comment]
It was a lot easier to NOT look at whether the user had changed it or not in this session.  I think the user experience is identical either way, although the DB does get updated now even when the user didn't change the setting manually. I think that's fine.

What I implemented was:
if patter, then Loop defaults to on, at first load time;
After that, Loop setting is remembered.  

So, if you have a Riverboat patter record that is 5 or 6 minutes long, it will default to Loop ON, and just hit L to turn it off, and it will be remembered for that song thereafter.

Thanks for the tips, @danlyke !  It was amazingly straightforward to add a new per-song field to the DB, and use it.

Commit: d352dfb84e9fe0353707bf122704d413d810cf09 .
