### ISSUE TITLE
Reminder: In Jan 2023 need to update the copyright dates

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#726]
I have a simple script to do this in the source code.  I should also post that script here for future reference.
Remember to update the splash screen, too.

**Comment by danlyke** [comment]
perl -npi.bak -e s/2022/2023/g *.cpp *.h

**Comment by mpogue2** [comment]
Fixed a few days early by bcd44c8a33257f00ef1ac51db8e88894b22f7afd .

Note that I needed to use a slightly different line, because some copyright dates were missed last year:
`perl -npi -e "s/202[0-9] Mike Pogue/2023 Mike Pogue/g" *.cpp *.h`
