### ISSUE TITLE
SSD "Dance Programs" does not show Recycle properly

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#735]
If you select the "Dance Programs" tab, then select "SSD" from the dropdown list, at the bottom instead of "Recycle (from a wave only) with a timing of 4, it shows two lines: "Recycle 2" and "from a wave only)".

Patch supplied.

<img width="901" alt="ssd-recycle" src="https://user-images.githubusercontent.com/76225465/204155771-3b5afd35-18ee-41d2-a9b4-b6ad6a0c2c85.png">
[Patch-ssd.txt](https://github.com/mpogue2/SquareDesk/files/10099052/Patch-ssd.txt)

**Comment by danlyke** [comment]
I *think* those files are copied into the "reference" directory, so it
might take an active action to refresh them...

**Comment by sharmanr** [comment]
I thought so and changed them but they get overwritten in danceprograms.cpp ;  hence the patch.
Richard

**Comment by danlyke** [comment]
Aha. We should clarify the semantics around *that*...

**Comment by mpogue2** [comment]
Patch applied, as of 8912e9a90baad4b3ed999a0828f04fae6a984040 .

**Comment by mpogue2** [comment]
If this fix works for you, feel free to close this Issue.  (If you can't, let me know, and I'll close it...). Thanks again!

**Comment by sharmanr** [comment]
Looks good!
