### ISSUE TITLE
Editing cuesheets that have <table> can cause extra blank lines to appear

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#738]
When editing the lyrics extra lines are sometimes inserted if there is a table in the html.

On a 2-column cue-sheet if you remove a blank line after the title, then when you save it the empty line reappears.  In fact, on some cuesheets  if you do "Unlock for editing" then (without any change) "Save" a few times the "Opener" line gets moved further and further down the page.

The problem is that Qt's editor seems to like to put in extra `<P>` and  `</p>` codes.  Routine postProcessHTMLtoSemanticHTML has code to handle that by replacing `<P>`SOMETHING`</p>` with SOMETHING`<BR/>` which usually works fine.

However, sometimes this the original `/p` (that the editor puts in) occurs just before a `<table>` and since html will start a newline for a table, then the additional `<BR>` (or the un-replaced `</p>`) causes an extra newline.

The attached patch removes `<BR/>`s that occur immediately before `<table>`. (Actually, before "`<t[ard]`" because the same thing can happen with `<tr>` or `<td>`.)
[lyricsedit.patch.txt](https://github.com/mpogue2/SquareDesk/files/10204819/lyricsedit.patch.txt)

**Comment by mpogue2** [comment]
@sharmanr I'm happy to take this change, but could you kindly post an example of a file that exhibits this behavior, so that I can test the patch after applying?  Thanks!

**Comment by sharmanr** [comment]
I created a Dropbox directory and put one cue-sheet there, but when I put a link to it here it doesn't seem to work.
So I will attach the file here.  I had to add ".txt" for github to accept it.
[GWR 144 - Get Down.html.txt](https://github.com/mpogue2/SquareDesk/files/10211665/GWR.144.-.Get.Down.html.txt)

**Comment by mpogue2** [comment]
@sharmanr I was able to download the file and test the change.  Looks good to me!  Thanks!
