### ISSUE TITLE
Feature:  Flashcard files to specify calls

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#748]
Here is a suggested extension to flashcards.  As well as selecting calls by level it allows arbritrary calls to be entered.

A new menu entry allows a flashcards file to be prompted for,  see screen shot.  Lines are read from this file and are added to any other calls specified by levels.
![screenshot](https://user-images.githubusercontent.com/76225465/210290528-3ed788ee-af96-478a-a93b-630c5f94b4eb.png)

As well as just calls, it could be used to prompt for particular cases, e.g. specific formations or arragements,  such as
- Same Sex Slide Thru
- Half Sashayed Right and Left Thru

Lines beginning with a ‘#’ are ignored.  This allows the file to be initialized with untaught calls being commented out and then being uncommented as they are taught.

In this implementation,  just as the checked Flash Call Levels are persistent, so is the state of the “Select a flashcards file” and the selected file if there is one.  As a result of this, if a flashcard file was in effect when SquareDesk was last running, when restarting this file will be read.

When the option is turned off,  the directory is remembered and used as the initial directory shown in the file dialogue.

If the option is on, and the Cancel option to the File Chooser is given, the option is turned off.
[Patch-flashfile.txt](https://github.com/mpogue2/SquareDesk/files/10333991/Patch-flashfile.txt)

**Comment by mpogue2** [comment]
Looks good to me!  I will just comment out the qDebug() statements, so as to not lengthen the debug.log (unless they are needed for debug in the future, in which case we can put these back in).

The file format is like this:

```
mpogue@Mikes-MacBook-Pro test % cat Mike_Flash_Calls.txt
Cast A Bronze Sculpture
Chain Overreaction
Clover and Kiss Me
Cross Clover and Kiss Me Again
```
And the result looks like this:

![image](https://user-images.githubusercontent.com/6316003/210304166-10cdd9d2-7686-4d12-8ebd-00b9f7e7b4fe.png)

**Comment by mpogue2** [comment]
Committed: 224a5415720a06e6fd295ffc0d4a3e2ab5010664, so please test!  If it looks good, please close this ticket.

**Comment by sharmanr** [comment]
Built and tested, no problems.
I should have mentioned a couple of things when using it:
- if a file is selected,  then to change to a different file you need to uncheck then re-check the "Select a flashcards file".
- if the "Select a flash cards file" entry in the "Flash Calls Levels" menu is set,  then any other change to that menu (e.g. adding or removing a level) won't ask again for the file, but it will be re-read.  So if the file is changed it can be rescanned by simply checking then unchecking a level
