### ISSUE TITLE
Feature: click to go to that spot in an SD sequence

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#76]
It would be nice to be able to click on an item in the sequence pane, and have the renderView show the position at that point.

**Comment by danlyke** [comment]
Might be time to port my "feed SD sequences back into SD" code from
Perl into C++/Qt...

**Comment by mpogue2** [comment]
Yes!  Would you be willing to check it in somewhere, until we get to it?
The alternative is to look at what you did, and modify SD itself to be self-consuming.

**Comment by danlyke** [comment]
https://github.com/danlyke/square_dance_tools/blob/master/rewrite_for_sd.pl

**Comment by mpogue2** [comment]
Yep, I think we can close this.  There are some minor UX enhancements I'd love to see, but I'll open a separate Issue to discuss whether those would be useful....
