### ISSUE TITLE
Editing lyrics:  adding copy/paste to mouse menu,  unable to select line by triple clicking

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#762]
Being able to edit the lyrics in SquareDesk is marvellous!   Very handy.

I missed having the copy/paste/cut available on the right button;  I kept trying to copy and paste that way but was greeted just by the “Reveal in Finder”.  I found it easy to add the extra items, see enclosed patch.

(The only problem with the patch that I’m aware of is that any pasted text is sometimes small and needs to be fixed by the “Clear Formatting”, “Lyrics” or other similar buttons.  With my M1 MacBook Air this is not a problem, with my M2 mini it is;  both are running Macos 13.2.1.  Strange.)

The other minor annoyance I have with editing lyrics is it is hard to select a whole line.  Double clicking selects words,  but triple clicking selects everything not just the line.  Is this intentional?  Can it be changed to select the current line?

[copy-paste.patch.txt](https://github.com/mpogue2/SquareDesk/files/10829779/copy-paste.patch.txt)

**Comment by mpogue2** [comment]
- I like the idea of copy/cut/paste on the Right button menu.  I am used to use Cmd-C/V though, so not having it was not something I even thought of! :-)
- pasted text sometimes small = we are using a built-in Qt HTML editor here, but "tricking it" into making semantic edits (e.g. title, author, lyrics).  This was NOT a simple thing to do, and the fonts sometimes gets messed up.  This happens most often when editing a cuesheet that was not started in SquareDesk.  There are many, many HTML tags that will mess up the editing process.  I don't know if this applied to your test case here though...
- Triple click not working as expected is #240 .  I believe this is because "triple click" in an HTML editor means "select paragraph", whereas "triple click" in a normal line-oriented editor means "select line".  This could probably be fixed by modifying (or subclassing?) the HTML editor code, but I was never motivated enough to do so (it's probably not a simple fix -- you could look to see if you find something that I could not!).... :-)

**Comment by mpogue2** [comment]
I haven't tried the patch yet, but just from inspection I have a couple comments/suggestions/questions:

- Normal order on Mac's is "Cut, Copy, Paste" I think (screenshot from Sublime Text 4)... 
![image](https://user-images.githubusercontent.com/6316003/221328292-3723d0d3-d766-4f21-b37a-98d1d2389ea4.png)
- Maybe a separator would be good, too?  

So if we go with Sublime Text 4 order, so "Cut/Copy/Paste/------/Reveal In Finder"?  Would that work for you?

**Comment by sharmanr** [comment]
That sounds good with me!

**Comment by sharmanr** [comment]
OK, here's a revised patch that has your suggested reordering and an item to select a line and separators.
Like so:
<img width="340" alt="new-menu" src="https://user-images.githubusercontent.com/76225465/221341635-4b823028-74b8-4a7d-81ed-796ab9fae828.png">

To select multiple lines, go to the first line, right click and select the "Select Line" menu item,  then while holding SHIFT down move the cursor down and keep it to the right, thus selecting multiple lines.

[reorder-and-select-line.patch.txt](https://github.com/mpogue2/SquareDesk/files/10830400/reorder-and-select-line.patch.txt)

**Comment by mpogue2** [comment]
I like that "Select Line" solution!  And the SHIFT-click afterwards is also very nice!

Commit on mainline: a024620515caf9a6f0667905b40d5d1df98a24a1

Cut/copy/paste are now available as context menu (right click) items in the lyrics editor.  In addition, Select Line, which as the name suggests will select the entire current line that the cursor is on, is available in the context menu.  Courtesy of @sharmanr - thanks!

@sharmanr -- Please close this ticket, if this commit looks good to you!

**Comment by mpogue2** [comment]
Just a thought -- I never thought of doing a Select Line in a context menu.  Are there other Select's that should be there?  
- Like "Select Section" (or "Select Figure"? -- not sure what the right name is here), which looks backwards to the previous HEADER line, and selects from there until just before the next blank line?  I frequently make a Figure 1, and then duplicate it for Figure 2, and then duplicate Figs 1/2 to make Figs 3/4 (while changing Heads to Sides manually).  
- Could also have a "Paste and Swap HEADS/SIDES" to do that second duplication?
- Or, I do already have an Auto-formatting menu item in there, that might do the job, too.  e.g. If it finds a Figure 1, dup to make Fig 2, dup again swapping heads and sides to make Fig 3, and dup again to make Fig 4.  And, if OPENER is found, but MIDDLE BREAK and CLOSER are not, dup the OPENER to make them, as needed.

Just blue skying here... if you like these ideas, we could close this ticket, and open a new ticket for them as a future thing to think about....None of these is critical, just time-saving if you edit a lot of cuesheets.

**Comment by sharmanr** [comment]
I like the idea of selecting a figure.  I haven't been using autoscroll but have been using 2-column and so often take a cue-sheet and move a figure from the bottom to the right-hand side for example.
I see there is a routine called on_actionAuto_format_Lyrics_triggered but it never seems to get called.
As you say, I think closing this ticket then creating a new ticket for further ideas is good.

**Comment by sharmanr** [comment]
Sorry,  I tried to close it but I can’t;  it only lets me comment!

**Comment by mpogue2** [comment]
Looks like it thinks you closed it a couple of hours ago, so it won't let you close an already-closed ticket! :-)
