### ISSUE TITLE
Feature: "Select Section" in Lyrics

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#763]
Just a thought, now that we have "Select Line" in the Context Menu in Lyrics editor. 
Are there other Select's that should be there?

Like "Select Section" (or "Select Figure"? -- not sure what the right name is here), which looks backwards to the previous HEADER line, and selects from there until just before the next blank line? I frequently make a Figure 1, and then duplicate it for Figure 2, and then duplicate Figs 1/2 to make Figs 3/4 (while changing Heads to Sides manually).
Could also have a "Paste and Swap HEADS/SIDES" to do that second duplication?

Or, I do already have an Auto-formatting menu item in there, that might do the job, too. e.g. If it finds a Figure 1, dup to make Fig 2, dup again swapping heads and sides to make Fig 3, and dup again to make Fig 4. And, if OPENER is found, but MIDDLE BREAK and CLOSER are not, dup the OPENER to make them, as needed.

**Comment by mpogue2** [comment]
From @sharmanr: "I like the idea of selecting a figure. I haven't been using autoscroll but have been using 2-column and so often take a cue-sheet and move a figure from the bottom to the right-hand side for example.
I see there is a routine called on_actionAuto_format_Lyrics_triggered but it never seems to get called."

on_actionAuto_format_Lyrics_triggered() is called only when the user selects Lyrics > Auto-format Lyrics.
It does some formatting (e.g. HEADER) that I do a lot when creating a new cuesheet.

After thinking about it more, I think it would be better to have "Select Section", rather than overloading the Auto-formatter.  I think it's more general.

**Comment by mpogue2** [comment]
Commit:  edf1feed08283ff4cf5f7679537653d108fffa7e 

Additional right button actions are:
  Select Section
  Swap Heads and Sides within Selection
(The latter appear only if there is a selection.)

**Comment by sharmanr** [comment]
I was careful to match "heads" and "sides" and not other words containing, but I hadn't thought that just "head" or "side" should be swapped.   But just now I came across "Head couples right and thru" and of course that failed to swap!  So I think the regexp should be allow head or heads,  i.e.
`"\\b(heads?|sides?)\\b"`

**Comment by mpogue2** [comment]
Looks like this was fixed by 27e447e0fce2b1a0b1857be3c33ac517486b43c0 , so closing.
