### ISSUE TITLE
Feature: use a nice graphical button for |<< and >>| buttons

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#77]
Using a Text button was supposed to be a placeholder until I got around to doing real graphics for it.  It looks especially weird in the Linux screenshot.  We can do better!  I suspect there are plenty of free images for this function out there, and one probably matches the square and play button look.

**Comment by mhkull** [comment]
And please work on free configurable key assignments

**Comment by mpogue2** [comment]
I'm going to make a separate Feature for that one!

**Comment by mpogue2** [comment]
Qt already had nice graphical images for these 2 functions built-in.  I just had to set the images on those buttons, and voila!  Fixed by 38b5019d6c31d8247412032ba0a1582e10a86f7f .
