### ISSUE TITLE
Bug: App crashes when you do "!" as the first character typed into a new sequence in SD

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#775]
So, this bug has been there for a while, but @sharmanr hit it pretty easily when he tried typing "!".
The root cause is that:
- With no input yet, typing "!" gives "! completion" where the first item on the list is "exit from the program"
- When we try to look up what the dance_program is that is associated with that "call", an uninitialized variable is used as the index of an array.
- BOOM goes the dynamite.

But, in the course of fixing this, I noticed that:
- "! completion" and "? completion" generate "exit from the program" as the first legal thing a user can type.  
- While this is true for sdtty, it is useless (and dangerous) for users to type this in, or double click on this in the "? completion" pane, because
- it causes app crash down the line when the next call is typed in.
- BOOM again.

I fixed both of these so:
- if nLastOne is negative, ignore it, AND
- if user types or double clicks on "exit from the program", ignore it, AND
- don't allow "exit from the program" to be shown in the "? completion" pane in the first place.

**Comment by mpogue2** [comment]
FIXED by: 94361d54bfcc96940cdb6c06ed4c87250dbe1e1e .

**Comment by sharmanr** [comment]
Who would have thought 1 character would cause so much work!

**Comment by mpogue2** [comment]
@sharmanr Who would have thought that a crashing bug like this would have gone this long without being noticed?  And then you come along, and find it instantly!! Nice work! :-)

**Comment by mpogue2** [comment]
Appears to have stayed fixed, so closing.
