### ISSUE TITLE
Double check that these are fixed

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#782]
Bugs reported against 0.9.5 by Gero, that should be checked:
- letters of active tab disappear (white-on-white)

![image](https://user-images.githubusercontent.com/6316003/227335901-6b27a153-965f-43f5-94b4-f79a3896c5e9.png)

- patter loop: tiny break in the music (test this)
Features that I think are already implemented:
- looper: Add an overall time counter/stopwatch showing the time elapsed since the music was started. For example after three loops the counter is at 7:23.

**Comment by mpogue2** [comment]
Testing "tiny break in the music":

With the current top-of-tree version (f8297b599b3eb34fc0a296c841ec9ce9993232d8), I jumped back from a 200Hz section (precisely aligned to the sample) to a 100Hz section (precisely aligned to the sample), and the splice at loop time was sample-accurate.  Here's a picture:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/6316003/227335269-8f8450bb-6de6-460b-b159-9185a9fe7e27.png">

**Comment by mpogue2** [comment]
Testing "letters of active tab disappear":

Here's what I see with current top-of-tree:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6316003/227336221-08efead5-c72a-4380-9737-f6d2ba4de78f.png">

This was a long-standing Qt bug, and since we've upgraded to later versions of Qt since the 0.9.5 release, this bug has been fixed.

**Comment by mpogue2** [comment]
Regarding "overall time counter/stopwatch...":

That feature was implemented a while ago, although it might not be documented well.
Once the music is started, the big timer numbers (see picture below) reflect "Time in tip", and they continue to count, even though the music may be paused.  If the music is stopped entirely (by pressing the STOP button, or pressing the PERIOD key), the Time-In-Tip will go back to zero automatically.

<img width="454" alt="Screenshot 2023-03-23 at 12 58 42 PM" src="https://user-images.githubusercontent.com/6316003/227339123-a59894fd-9500-42ff-9f22-baa4b21ee63c.png">

**Comment by Gero5** [comment]
Regarding "overall time counter/stopwatch...":

For that "patter timer" has to be active in the preferences. From the way it is described there "patter timer after x minutes of patter, visual indicator" I was expecting just a visual indicator only  not a time counter. 
Now I know. :-)
It is quite useful for most callers, I guess. Maybe you want to activate it by default?

**Comment by mpogue2** [comment]
I think it would indeed be good to make "Patter Timer ON" the default.  The pull down menu is supposed to refer to what happens after the patter timer expires: either a) an audible indicator (which I use), or b) a visual indicator only (no audible sound is played).

**Comment by Gero5** [comment]
I tested this with v1.0.4

- letters of active tab disappear (white-on-white)
fixed.

- patter loop: tiny break in the music (test this)
fixed/much better

- looper: Add an overall time counter/stopwatch 
works.
