### ISSUE TITLE
Feature: 24-hour clock

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#784]
From Gero:
- clock: add a 24 hrs time format option for the clock

Should this be automatic, and follow the system's setting for 12 vs 24-hr clock?
Or, should it be a new Preference?

**Comment by mpogue2** [comment]
Nevermind...I found a way to make it work automatically based on the system time setting, so I'm going to go with that for now....  I tested it on a US MacBook in both 12-hour and 24-hour modes, and I think it works!

Commit 4215af6114120932f21b84428bd2ad967128a367

**Comment by Gero5** [comment]
follow the system's setting for the clock would be fine

**Comment by mpogue2** [comment]
Let me know whether the 1.0.4 version fixes this, and I'll then close this ticket.  Thanks!

**Comment by Gero5** [comment]
Well morning hours are looking good. For a reliable feedback I guess I have
to wait until it is afternoon here. 😉😀




Am Mo., 27. März 2023 um 04:06 Uhr schrieb Mike Pogue <
***@***.***>:

**Comment by mpogue2** [comment]
I'm glad it works in Germany, too! :-) Closing as fixed...
