### ISSUE TITLE
Percent instead bpm in Tempo column

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#789]
See screenshot - or is this a feature?
![image](https://user-images.githubusercontent.com/128936259/227809684-1254c1bc-8964-416c-900f-6f1efe646fda.png)
Square Desk 0.9.5 MacOs Ventura Intel

**Comment by mpogue2** [comment]
It's a feature -- it means that we could not automatically detect the BPM, so percentage is the best we can do.

**Comment by mpogue2** [comment]
I should also say that v1.0.4 is somewhat better at BPM detection than version 0.9.5 .  So, please try this same file with the new version.  If that doesn't work, I'd love to get a copy of the MP3 file so I can debug this here!

**Comment by Gero5** [comment]
The song has a rather epic slow intro mainly just piano in the first 45 seconds. after that a strong beat comes in. Admittedly it is not as easy to detect the beat automatically.

**Comment by mpogue2** [comment]
Thanks for the report!  Closing this one, as of v1.0.4 .
