### ISSUE TITLE
Feature: waveform display in song position slider

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#79]
It would be nice to make the slider bigger (but it shouldn't take up any more space overall), and then stick a waveform in there.  

Future idea.

**Comment by mpogue2** [comment]
Here's an example of what I mean, from Anytune.
What I like:  it spans the entire horizontal distance, it doesn't take up a whole lot of space.  It allows for direct drag/drop of the markers (for patter, singing calls), easily can see where sections start/end in the waveform.
<img width="1096" alt="anytune_screenshot" src="https://cloud.githubusercontent.com/assets/6316003/25568541/c189c3c6-2db9-11e7-9ab1-026faffceb3e.png">

**Comment by mhkull** [comment]
Maybe you can open a seperate "edit window" when loops are to be set.

**Comment by mpogue2** [comment]
Here's an example from Cross DJ.  They did a nice job with this, I think.
![crossdj_screenshot](https://user-images.githubusercontent.com/6316003/29105358-94460412-7c81-11e7-87f7-e05ff6c7d17d.png)

**Comment by mpogue2** [comment]
Cross DJ also has nice UX for setting the loop points to be exactly N beats apart (N=4,8,16,32,64).
And, they have a FF/REWIND mode that also jumps in powers of two beats.  Nice idea.

**Comment by danlyke** [comment]
I've thrown a quick initial attempt at this in waveformdisplay_79. I'm not convinced I'm on the right track, and I'm sure that on anything but Linux it scribbles all over the controls...

**Comment by danlyke** [comment]
This is just using the volume sampled roughly per pixel,  but I don't think it ends up being a reasonable trade-off vs load-time for what limited value it gives, and probably needs to be something smarter about actual values. Also would probably help if we had ways to zoom, and then we're starting to talk about actual editing software...

![squaredeskwaveform](https://user-images.githubusercontent.com/88919/42428850-bb5c009a-82ea-11e8-8d67-8d5d85e1cbd4.png)

**Comment by mpogue2** [comment]
I pushed a couple of minor changes: color to black on Mac OS X, so that it's visible (the blue was not visible at all, really), and I shifted it one slider offset to the right to get it to align better with the actual slider song position.  It's still off towards the end of a song, by my reckoning (using a test tone), but I think this is close enough now to play with it.  I'm not sure it's worth the extra load delay, but it's kinda fun to play with... I suggest we keep playing with it for a while...

**Comment by mpogue2** [comment]
This one is now working and visible to users.  Closing this one.
