### ISSUE TITLE
Bug: Audio list: Vanishing Title 

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#795]
Audio List: after klicking on the patter for making it ready to play the title vanished. it reappeared after I clicked on the line
![Bildschirm­foto 2023-03-27 um 10 54 09](https://user-images.githubusercontent.com/128936259/227893795-fdb62f9a-d688-44b4-b5e4-45466e0a41f3.jpg)

after click on the line
![Bildschirm­foto 2023-03-27 um 10 54 20](https://user-images.githubusercontent.com/128936259/227893721-403157b5-faed-453b-ac27-b41f0125f336.jpg)

I renamed a three audio files and deleted one audio in the finder before that. So maybe there is a correlation with updating the list. 

v 1.0.4 MacOs Ventura Intel

**Comment by mpogue2** [comment]
I believe this is a dup of #630.  This has been a difficult bug to track down, because the library we are using (called "Qt") does some things under the covers that we can't always see.  I thought I had fixed it, but although it happens less, it still happens occasionally.  And, it is annoying!

**Comment by mpogue2** [comment]
I'll probably close this ticket, if I can't find any differences between #630 and this one.
Thanks for the nice pictures!

**Comment by Gero5** [comment]
It is probably the same and it has to do with the highlighting.

**Comment by mpogue2** [comment]
OK, I'll close this one, and use the origin #630 for this highlighting problem.  Thanks for reporting!
