### ISSUE TITLE
Audio file list jumps to the patter section without reason

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#797]
When I start a sining call sometime SquareDesk audio list  jumps to the patter section in the audio file list for no reason I can see.
But I am editing my files a lot at the moment. Might be that the list just goes to the top after reloading for updates.

**Comment by mpogue2** [comment]
Yes, it reloads everything, to handle the case where you have done a Save As, and that new name either matches or doesn't match the currently-loaded MP3 file.  The dropdown menu on the Lyrics page is then updated to include that new name (or not).

**Comment by Gero5** [comment]
Ok then there is a reason. you can close this issue.

**Comment by mpogue2** [comment]
Closing

**Comment by mpogue2** [comment]
See also #845, which was a Ventura-specific problem.  This is now fixed in top-of-tree.
