### ISSUE TITLE
Bug: "It's So Easy" can't be found when typing in the apostrophe

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#816]
"Its So Easy" matches the song "FT 158 - It's So Easy", but "It's So Easy" does not.
That's unexpected.

**Comment by Gero5** [comment]
Apostrophe is a special character. Do you have an escape logic for that in the search like adding a backslash before it?

**Comment by Gero5** [comment]
as it seems everybody uses their own kind of apostrophe. maybe because of the fact that I have another language set up here some look kind of strange (from the lyrics pool). in the three following file names another character than the standard apostrophe is used:
![Bildschirm­foto 2023-04-05 um 17 48 46](https://user-images.githubusercontent.com/128936259/230135173-4f519c2f-4876-4d11-b9ad-fcccace9ca6c.jpg)
![Bildschirm­foto 2023-04-05 um 17 46 56](https://user-images.githubusercontent.com/128936259/230135259-6544d1a4-281d-4cbc-bf8d-4c99c05770f7.jpg)
![Bildschirm­foto 2023-04-05 um 17 47 39](https://user-images.githubusercontent.com/128936259/230135276-7514904e-0aae-4580-a277-742f8ea3fc61.jpg)

where others meet international standards:

![Bildschirm­foto 2023-04-05 um 17 47 56](https://user-images.githubusercontent.com/128936259/230135302-fd9e8d76-cbd2-43c7-aca1-56a3618ece6f.jpg)

**Comment by danlyke** [comment]
Do we need to use libiconv to do an ASCII flattening of everything?

That feels kinda aggressive, on the other hand punting it to users to do
the right thing for their locale also feels weird.

**Comment by Gero5** [comment]
can the apostrophe be replaced by a one character wild card in the search string?

**Comment by danlyke** [comment]
I think that what I did at some point was break the search string into
words, and search for each word appearing somewhere after the previous
word. With special handling for tags. Which means that a solution might be
to do a word break on any non-alphanumeric characters, and break between
alpha and numbers.Message ID: <mpogue2/SquareDesk/issues/816/1497900431@
github.com>

>

**Comment by mpogue2** [comment]
I think the algorithm that you describe, @danlyke, is probably the root cause of the problem that I experienced.

My guess is that what @Gero5 is describing is something different.  This could be the use of 7-bit ASCII encodings.  It could be typos, too.  Whether a wild card would work or not would need to be investigated.

To that end:  could you copy/paste those strings into this ticket?  That might or might not work (it works, if it looks the same as those screenshots you posted above, I think...). If not, we might need to make a special version of SquareDesk for you to test, that does the equivalent of "od -hc" on those filenames.  OR, if you have command line, doing something like 
`ls -1 *So Easy* | od -hc`  would be useful for figuring this out (and same for the other couple of examples you provided screenshots for).  Thanks!

**Comment by mpogue2** [comment]
Oh one more thing, @danlyke.  Encoding conversion would only be possible if the source encoding were known for certain.  In my experience, that's essentially impossible to know when it's in a filename, OR when it's in a 7-bit ASCII plain text file, etc..  

It's also a PITA for us to support all possible encodings, when the far simpler solution is "look through your filenames, and anything that's doesn't look right in SquareDesk, rename the file".  The "Show in Finder" context menu item is a good way to get to the weird filename quickly.

**Comment by danlyke** [comment]
Seems totally reasonable to me! I'm at work and not thinking about that
code right now, but it may be as easy as changing a whitespace match like
@"\\s" (I don't remember if we used the regex engine for that) with @"\\W".

**Comment by mpogue2** [comment]
@danlyke Ah...That function already uses "\\W+", and that means not "[a-zA-Z0-9_]".  
So, I'm thinking maybe change "\\W+" to "[^a-zA-Z0-9_']+" or maybe even "[^a-zA-Z0-9_'`]+" to include
both single quote (most common quote in "it's") and single backquote (most common incorrectly-used quote).

If I get a chance, I'll give that a try, and see what happens!
Thanks for the quick reply!

**Comment by danlyke** [comment]
Yeah, it's possible that there's character set locale issues with
whatever that \W is doing.. every time I get into the meta state of
regular expressions, or Unicode stuff, my brain goes boom.

**Comment by mpogue2** [comment]
Fixed by

Single quote was basically used as a **delimiter** for matching purposes.  Now it's a **normal matched** character.  We'll see if this is OK -- might want to make it an **ignored** character at some point (e.g. so that "it's" matches "its" and "it's"?
