### ISSUE TITLE
Bug: Pitch is not saved per song

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#817]
the manual promises: 'Pitch is saved on a per-song basis.' When I change the pitch to a song it is not remembered. when I click on the same song the pitch is set back to zero.
Surprisingly it saves the pitch when the tempo is changed. then both values are changed the next time I play the song.
v 1.0.4 Mac Intel

**Comment by mpogue2** [comment]
Closing.  Please reopen, if this occurs again, or if you have a reproducible test case!  Thanks!
