### ISSUE TITLE
Bug: Lyric search is not limited to the given folder

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#822]
When there are several folders starting with 'lyrics' like 'lyrics_old', 'lyrics_lib' SquareDesk is searching all folders for lyric files. It should be limited to the 'lyrics' folder.
![Bildschirmfoto 2023-04-15 um 10 52 59](https://user-images.githubusercontent.com/128936259/232203020-8ad0ae30-ba65-43f4-b14b-d6429cf1c4bd.jpg)

... or is it a feature? it seems to me that it is searching **any** folder below the SqaureDesk directory for lyrics no matter what the name is. Therefore it is not that easy to exclude a folder from the lyric search if you want to keep in that directory.

**Comment by mpogue2** [comment]
It's intentional.  Some people like to put cuesheets into the same folder as the music itself.  Music can be put into folders with any names, not just the default names.

**Comment by Gero5** [comment]
OK. I will move the unwanted lyrics files elsewhere.

**Comment by mpogue2** [comment]
Closing.
