### ISSUE TITLE
Feature: Option for auto-show the lyrics tab when start playing a Singing

### ISSUE THREAD

**Issue by phoef** [mpogue2/SquareDesk#83]
Or alternatively a key shortcut to switch the tabs.

**Comment by mpogue2** [comment]
This is a good idea...maybe both are good ideas!

**Comment by mpogue2** [comment]
This option is in, as of c211f497e6af2d1752ac7270cf46aab8800629fd and eeff9636c6ef9b29cac0c5215c5ced402a3ca2ad .  It's a new setting in Preferences, that looks like "Behavior: [X] Switch to Lyrics tab on first play (when lyrics are available)".  It switches only once at initial playback time (e.g. you press SPACE BAR to play the song.)  If you want to switch back, that's a manual operation.  The keyboard shortcut idea is still an open item.
