### ISSUE TITLE
Bug: title and label are scrambled

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#84]
C 121A - Excelorator Special (patter).mp3
in "best guess" mode is parsed as:
Label = "C 121"
Title = "Excelorator Special (patter) A"

Not quite correct...

**Comment by danlyke** [comment]
I'm not sure how to represent this... the "A" isn't really part of
the number (especially not when we're trying to match cue sheets),
putting it out on the end of the name seems as good as anything...

**Comment by mpogue2** [comment]
I think it is part of the label identifier (e.g. C 121A really is the ID of that song), and the match for cue sheets should be a little more fuzzy to compensate...

**Comment by danlyke** [comment]
Okay, I've got a bit of thinking on how to do some of this better, I'll
take a look.

**Comment by danlyke** [comment]
Fixed in 8729fc2b41a91bec08573f5a5f4e95f274134be0 . I've got some bigger stronger better changes I want to do at some point, but this takes care of the immediate issue.
