### ISSUE TITLE
Bug: On Ventura, loading a new file causes a reload of the songTable

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#845]
On Mac OS Ventura, it turns out that accessing a file for the first time (e.g. when SquareDesk loads it) causes it to be tagged with the extended attribute "com.apple.provenance".  This is a new attribute, and not documented yet, but it seems to mean something like "I've asked Apple about this file, and it's OK to remove the quarantine attribute".

But, the file watcher is waking up and reloading the entire songTable because of this (on Mac OS Ventura only).

Note: this happens only when a file is "new" and has never been played before.  So, it's a one-time songTable reload when this happens, but it's still annoying.

Discovered and extensively investigated by @sharmanr (thanks!)

**Possible solutions we considered:**
1. ignore changes for N seconds after load, since it's the load (rather than the play, for example) that is causing the extended attribute change on the file.
2. manual button (or menu item or whatever) for update -- works, but not as good as option a)
3. defer the file watcher until some time later.

Richard and I both think that a) is the best solution to this, because it minimizes the time when the file watcher is disabled, and it doesn't defer the songTable reload (it avoids it entirely).  This also allows us to workaround the problem (which I'll open a ticket on) wherein the FileWatcher causes the whole songTable to be reloaded, and the current view position within the table and the current selection are lost.

**Comment by mpogue2** [comment]
Fixed by 683745db7fbe104cc6fb6c6eb39f555027d3d2e2 .

On Mac OS Ventura, the extended attribute "com.apple.provenance" is set on some systems when SquareDesk loads a file.  This causes a reload of the songTable, which is annoying.  This change disables the FileWatcher for 5 seconds after an audio file is loaded.

NOTE to @sharmanr: I have been unable to get my laptop to make files with "com.apple.provenance" set by any SquareDesk action.  But, your system does this every time!  Could you kindly check this commit, and close this bug when it solves the problem on your machine?  I've tested it as far as I can on my system (it does indeed stop songTable reload for 5 seconds after an audio file is loaded on my machine, and that's as far as I can go...)

**Comment by sharmanr** [comment]
Yes, it works fine.  I tried several songs where xattr did not show the attributes, played them with SquareDesk,  the music list did not redisplay, and I confirmed with xattr afterwards that the com.apple.provenance had been added.
