### ISSUE TITLE
SD: Adding title to an existing card adds this title to all succeeding ones

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#852]
I opened up a dance created a week or so back before titles were there and edited the first card putting a title there.  This title then appeared on subsequent ones.  I put a different title on card 2 and then it appeared on cards 3 and so on.

**Comment by mpogue2** [comment]
Nice catch!  Fixed by 980aa38c3db7224ad36b252017e03cd050ea4484 .
