### ISSUE TITLE
Bug: cue sheet matching (several misc bugs)

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#86]
./SqViewCueSheets-9-30-16 Text/C 0306 - The Devil Went Down To Georgia.html
should be on the lyrics list for:
CH 306LK - Devil Went Down To Georgia

It's not an exact match, but there should be a way that it's in the dropdown list.

**Comment by mpogue2** [comment]
SIR 705b - Papa Was A Rollin Stone (Instrumental).mp3
also does not parse out the Label correctly.
Label: ""
Title: "SIR 705b - Papa Was A Rollin Stone (Instrumental)"

**Comment by danlyke** [comment]
Fixed in 0c19655630ede27396235dfe424728df4b64c2a8

**Comment by mpogue2** [comment]
Second bug mentioned was fixed on Mac OS X.  I will open a new bug for the first one, which is not fixed yet.
