### ISSUE TITLE
Feature: No Cancel Button on Edit Lyrics

### ISSUE THREAD

**Issue by boltoth** [mpogue2/SquareDesk#887]
On an Mac with the beta version of the SW V0.9.5(Qt5.9.3)
I don't see a way to cancel edits to Lyrics.
All i see is "Save" and "Save As"

Would be nice to have a "Cancel" button

**Comment by mpogue2** [comment]
In the Lyrics menu, try "Revert Edits".  That will cancel all the edits.

**Comment by mpogue2** [comment]
"Revert Edits" Button implemented in: 4fa5a2ead2d46746db28df1c65d0266d56bf2ff0 .

**Comment by mpogue2** [comment]
I believe this is fixed, so closing.
