### ISSUE TITLE
Bug: Tab Headings are white if active

### ISSUE THREAD

**Issue by boltoth** [mpogue2/SquareDesk#888]
On and M1 Mac 
With the beta version of the SW V0.9.5(Qt5.9.3)

The major tabls "Music Player", "Lyrics", ...
When that tab is active the tab header for that tab is all white.

Oddly if the window is not active (another application is selected) the active tab header shows up as expected.

Thanks
![Blank Tab](https://github.com/mpogue2/SquareDesk/assets/17104584/d59a4365-deeb-459c-bf03-be35fbc8573d)

**Comment by mpogue2** [comment]
This one is fixed in later versions of SquareDesk, i.e. v1.0.4 (see also #782 ).
V1.0.5 is being tested now.  Let me know if you would like to try it (it has a lot of new code, and so there are bugs that I am fixing as they are discovered)!

**Comment by mpogue2** [comment]
Closing as fixed.  Let's reopen if this happens again!
