### ISSUE TITLE
Feature: Auto scroll Cuesheet hot key

### ISSUE THREAD

**Issue by boltoth** [mpogue2/SquareDesk#889]
Feature request.
It would be great if Autoscroll on and off was a Hot key

Fighting with the Autoscroll while you are calling is challenging.

**Comment by mpogue2** [comment]
This is implemented now in the source code by commit: d0799ca004a93aa1cf76571da25e371b2fde697a .
You can set it to whatever you want -- I'm not currently providing a default key assignment.  I suggest using "A".
If that is a popular choice, I will make it the default.

**Comment by mpogue2** [comment]
This was a good suggestion, thanks!

**Comment by boltoth** [comment]
Thank you for all your prompt reply’s.

I enjoyed your software quite a bit.

Thanks again.
Tom Bolton

**Comment by mpogue2** [comment]
Closing as fixed.
