### ISSUE TITLE
Bug: Cuesheet Tab is called lyrics in the menu

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#895]
mInor issue: the tab for cue sheets is called "Cuesheet" on the tab. the corresponding section in the menu is Called "lyrics". This is IMO inconsistent. Same names would be better.

**Comment by mpogue2** [comment]
@Gero5 Thanks for finding this!  This actually used the old term "lyrics" in a couple of places, which are now fixed.

Fixed as of: ed6c90303ff21fa39ce20da0482fedab1cbe0785 .

**Comment by mpogue2** [comment]
Closing as fixed.
