### ISSUE TITLE
Bug: letters after label/label# don't parse right in Best Guess mode

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#90]
SIR 705b - Papa Was A Rollin Stone (Instrumental).mp3
does not parse out the Label correctly.
Label: ""
Title: "SIR 705b - Papa Was A Rollin Stone (Instrumental)"

**Comment by danlyke** [comment]
Fixed in 407880a66440b27549be4451d586a8b33760741e

**Comment by mpogue2** [comment]
Verified fixed on Mac OS X.
