### ISSUE TITLE
Feature: User-selectable Pan Law

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#910]
See discussion in #821.

The best long-term solution is probably to let the user choose the Pan Law.  This is probably pretty non-obvious to any normal callers, so some documentation would be good.  

Although there are many possible choices here, I think there are two main choices for curve shape:
- Constant Power (what we have now, using sin/cos), and
- Balance (flat, then linear or sin/cos)

Those two, together with the new Makeup Gain control, I think will cover 99% of the use cases.

Default should be what we have now (Constant Power), so as not to mess up any existing persisted Mix control settings.  When switching between the two curve types (or the makeup gain control for that matter), I think we can get away with no automatic conversions on the Mix control.

I'm leaning toward implementing flat + linear first, and then Gero can test it and see whether it feels OK.

**Comment by Gero5** [comment]
This one is just for me, I guess. As stated in #821:
I do not think that we gain a benefit for the average user with that. IMO you can close this and better invest your developing time in other issues. Sorry for the inconvenience that I brought up.

**Comment by mpogue2** [comment]
@Gero5 I think this was a great discussion, and not an inconvenience!  I'll close this one, but the notes from the discussion are still discoverable.
