### ISSUE TITLE
No 'Save' in Playlist menu when playlist has been modified

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#911]
version 1.0.5

I do not understand why there is no 'save' entry in the playlist menu. It should appear as soon as a playlist is modified. 
'Save Playlist As...' is the only choice I see.

**Comment by mpogue2** [comment]
For historical reasons, this is in the File menu.

**Comment by Gero5** [comment]
nice to know.

From a user's perspective it makes no sense to have "load playlist" and "Save playlist" in separate menus IMO.
"Save playlist as" is in both. "Save playlist 'name'" only in one?
I propose to move all to the playlist menu.

**Comment by mpogue2** [comment]
@Gero5 I will think about how to do this -- it's not straightforward.  The Mac convention is to put file operations in the File menu, but Playlist (which is a file) has its own menu.  Essentially, we are "editing" a couple of things at the same time, which is somewhat unusual on a Mac.  I think that means having separate Save menu items for each type, but I'm not sure.  "Open Audio File", for example -- maybe it should be in the Music menu?  But, it's also a "file".  Should there be a "Close Audio File", and if so where should it be?

Perhaps:

**Music Player** (perhaps rename tab Music Player to just Music?): Open Audio File... (should it be Load Audio File?), (then should there also be a Close or Unload Audio File?)
**Playlist**: Load Playlist..., Load Recent Playlist..., Clear Playlist (and remove all 3 from the File menu)
**Cuesheet**:  Save Cuesheet, Save Cuesheet As... (should there also be a Load Cuesheet?)

**Comment by mpogue2** [comment]
Implemented by: efe63390d502e7d0dcf8e7848bc3d8ec039e69d2 .

**Changes:**
- Music Player tab renamed to just "Music"
- File > Save, File > Save As..., and File > Print... removed.  Individual menu items were added to the Playlist, Cuesheet, and SD menus.  
- Fixed a bug where Cuesheets could not be Save As..'ed until they were unlocked.  Now anytime you can see a cuesheet, you can Save As... it.
- Open Music File... moved to the Music tab
- Dances menu item renamed to "Load Dance"
- Save Sequence As... renamed to "Save Sequence to File..."

Playlist menu looks like this now:
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/39e2a298-60fb-410b-aafe-db2c0d9fca8f)

Music menu looks like this now:
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/7273c804-4134-4455-a91e-bc4ee6bdd097)

Cuesheet menu looks like this now:
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/28f0176f-48b5-44c7-8399-a77e75dc13d3)

SD menu looks like this now:
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/00507ad4-9f0c-425c-a894-bc98523e8a2a)

**Comment by mpogue2** [comment]
I believe this is fixed, so closing.
