### ISSUE TITLE
Bug?: Box.net makes copies of squaredesk.sqlite3 for no reason

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#926]
This is annoying.  Every time we modify the sqlite3 DB and save it, Box.net (which I'm using for sync between devices) makes an EXTRA copy of it, called "SquareDesk (mpogue@zenstarstudio.com).sqlite3", thinking that there is some sort of conflict happening.

It's almost certainly this mechanism: https://support.box.com/hc/en-us/articles/360044193953-Duplicate-Files-With-Email-Address-Added-After-Sync

I'm not sure how to drop it from doing this.  It doesn't seem to do this with text files, only this one sqlite3 file (because it's a binary file, perhaps?).

**Comment by danlyke** [comment]
it'd mean jacking up sqlite and inserting a new event-sourcing architecture
in there, but if we wanted to go for the real computer science solution to
this...

What if we had a database directory, and in that directory wrote a new file
consisting of changes, for every time SquareDesk is quit. Timestamp those
events, and those file names, with an additional GUID for uniqueness in the
name. On startup, we read all files in that directory and apply those
changes, in time order, to an in-memory database.

Pretty standard ESA. With a little thought we could assume some merge time
and build intermediate caches, to keep the number of files down, though
it's probably only a few hundred per year worst-case.

Sync on whatever cloud service syncs this directory, and thus the latest
change from any sync'd machine wins.

**Comment by mpogue2** [comment]
In doing a little testing, it seems that a new folder in a new musicDir does NOT have this problem.  
Since this problem started in about April, I am suspecting that Box is confused.

Lemme try to see if I can fix this a lot more cheaply that replacing sqlite3 with a brandy-new transaction mechanism... :-). I can actually live with the extra copies, it's just that they tend to grow over time, and it's a manual cleanup, when Box should not be creating them in the first place (and in fact, does NOT create them with a clean new folder).  

So, I'm first gonna try to delete and recreate the .squaredesk folder, to see if this fixes the problem. :-)

**Comment by mpogue2** [comment]
I think I'll also try iCloud again, to see whether the previously-known pause bugs are gone now.  It's been a couple of years, so maybe?

**Comment by mpogue2** [comment]
OK, this does appear to be a Box.net bug, probably introduced last April.

What I did that seems to have fixed it (no more extra copies of squaredesk.sqlite3 created -- YAY!):
- Duplicated the ".squaredesk" folder using Finder
- Renamed the original to ".squaredesk_good_old" as a backup
- Renamed the copy from ".squaredesk copy" to ".squaredesk"

Now everything seems to work fine again -- no extra copies of SquareDesk.sqlite3 when I quit SquareDesk!
My theory is that by creating a new folder with the same name as the old one, that Box.Net sees it as a new folder, and so it doesn't think that it already has a different copy of the .sqlite3 file (which it then needs to rename at download time, to avoid a conflict).  I think it was being nice by trying to retain "both copies of the file", when it was just confused and there was only one file.

Hopefully this will stay fixed now. :-) My backup plan is to move back to iCloud, which used to NOT work, but currently seems to work just fine.

**Comment by mpogue2** [comment]
@danlyke Of course, if you really want to write your own distributed transaction-based database... :-)  I do think that the original design decision to use sqlite3 was still a good one, and it's still holding up over time! :-) :-)

**Comment by mpogue2** [comment]
I still haven't had any extra copies of SquareDesk.sqlite3 created by Box.net since I did the above fix, so closing this issue for now.
