### ISSUE TITLE
Feature: Consider obsoleting the Dance Programs tab

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#931]
I don't think anybody is using it, and there is a much, much better (and sharable) way to do this, using Joe Dehn's online SCVSDA.org dance programs page.  Therefore, I think we should obsolete the Dance Programs page at this point.  

It might be useful to either:
- replace the Dance Programs page with a tabWidget that has the three pages below linked via URL (requires internet access)
- make it easier to do the same thing (add a URL, basically) on the Reference page

Here's what we've been using, and because the dancers can see it online, it's a great resource for them, too.

### Joe's user admin page:
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/4de2acc2-8db3-4060-a60f-7fe757b2b9c1)

### Dancer view (super useful for dancers, and yes those are animations!):
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/fe241e49-131b-4f7b-a377-1f3a90394385)

### Compare our progress to other local clubs (e.g. to answer the question "what calls can I use at a multi-club hoedown, that all the dancers have been taught?"):
![image](https://github.com/mpogue2/SquareDesk/assets/6316003/d974e2aa-d344-4dd4-99d3-0dc565e1a8f5)

**Comment by danlyke** [comment]
I'm not teaching it right now, so I'm not using it, and if/when I do start teaching again I'm willing to reconstitute it at that point with whatever form might work better for me, but...

I don't think Joe's page is a reasonable substitute because I've never had net access while teaching...

**Comment by mpogue2** [comment]
Ok, fair enough!  Maybe this is a workflow style question? I also never have internet access at the dance....I could, but I intentionally disable it to avoid being interrupted by various notification noises. Windows users also need to avoid forced updates (yes, I've seen that happen to callers more than once, when the dance was stopped in its tracks! :-). I'm also very focused on providing a calls-taught list to the students.

Maybe what I'll do is just hide it for now, so we can easily bring it back again later.

**Comment by danlyke** [comment]
Cool. If I start teaching again, I suspect my workflow will be different from what it was, and this could always be something stand-alone.

**Comment by mpogue2** [comment]
Commit: 79fbd1760dac8bb2d648f31af158a7955e2a1b57

Just hidden for now.  We might do something better later.  See discussion in the Github Issue.
