### ISSUE TITLE
Bug: songTable text items do not update their color when Preferences > Font Color is changed

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#939]
v 1.0.6 X
font color for singings is dark green - no chance to read that in dark mode
Prefrence/Musik/Musik type/ singings --> change color to light green
font color is not changing 
any work around?

**Comment by Gero5** [comment]
Quit and restart brings the new color to work

**Comment by mpogue2** [comment]
That seems like a bug to me!  Good catch...

**Comment by mpogue2** [comment]
Fixed by d9d5e2ffa7647ce7941434a83c40db3dc6b738cb .
