### ISSUE TITLE
Feature: remove Preference to save Tempo/Pitch/In/Out 

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#94]
I don't think anybody DOESN'T want these to be remembered.  So, let's remove the 
checkbox from the Experimental Preferences tab.  And, internally it defaults to REMEMBER.

**Comment by mhkull** [comment]
Absolutely!

**Comment by mpogue2** [comment]
Experimental feature promoted to full always-on feature in: 2cccaadb58e3d71b0f4346143d6f52333bf29462 .
