### ISSUE TITLE
Bug: Cuesheet loop markers in dark blue can hardly be seen

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#942]
on the Cuesheet Tab

**Comment by mpogue2** [comment]
Ah, yes I see this.  It's a bug!

**Comment by mpogue2** [comment]
These?  Could you take a screenshot of yours, so we can compare?

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/4992513a-b7fa-4183-a9a7-5e97d3838fc0)
