### ISSUE TITLE
Bug: add to playlist for second playlist goes to third playlist

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#950]
See screenshot

**Comment by Gero5** [comment]
![image](https://github.com/mpogue2/SquareDesk/assets/128936259/6f867a68-a13e-461a-a245-232b29ed1a98)

**Comment by mpogue2** [comment]
Reproduced it.

**Comment by mpogue2** [comment]
Fixed by 3d4d0713e700526a0ff27c354215d8408ec8677e .

It was a cut/paste error. Nice catch, thanks!
