### ISSUE TITLE
Bug: Top-level Playlist menu not relevant in Dark Mode

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#957]
I think the top-level Playlist menu is now essentially obsolete. It works correctly only with Light Mode, where the playlist was in the songTable (no longer true in Dark Mode).

Playlist > Next Song, Playlist > Previous Song, and Playlist > Continuous Play are all broken now. They work in Light Mode, but not Dark Mode. All 3 need to be made Playlist-relative, I think.

**Comment by mpogue2** [comment]
Commit: a3be45e707268282ba0d038304efa57e5036c252

is a placeholder for getting rid of the Playlist Menu in Dark Mode.  When we have Next/Prev Song and Continuous Play implemented for Dark Mode, we can execute on this.

**Comment by mpogue2** [comment]
@Gero5 If I remember right, you are the only user of Continuous Play mode.  Since it doesn't work correctly right now in DarkMode, would you be willing for me to postpone fixing it until after 1.0.7 for now?  I'd like to focus on getting a 1.0.7 out there, rather than fixing this bug right at the moment.  So, I'd like to hide the main Playlist menu entirely when in Dark Mode, and I'll fix Next/Previous Song (used by Bluetooth remote users only) and Continuous Play mode (used by you) later.  If you still are using it...

**Comment by Gero5** [comment]
What is 'continuous play mode'? if that means song 2 is started after the end of song 1 - I never used it in SquareDesk so far.

For afterparty background music that would be fine, but I do not have a playlist for that. I used a 16 min patter music on loop mode for that purpose and nobody complained so far. (see caller's unique selling points) :-)

**Comment by mpogue2** [comment]
Yes, that's right.

Commit: a3e9ac76c3d50d5b450a8e397f703cdebbb38934

In DarkMode, these functions have moved to context menus on the individual playlist slots, or on playlists in the Tree View.  So, removing the main Playlist menu when in Dark Mode.

**Comment by mpogue2** [comment]
Pulled out the Next/Prev Song and Continuous Play mode breakage into #964.
