### ISSUE TITLE
Feature: better SoundFX and better SoundFX stop functionality

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#97]
Later on, we can have it scan the soundFX directory, and dynamically build the soundFX menu, with names for sound FX (maybe "1-whistle.mp3" becomes "whistle" in the menu?).

**Comment by mhkull** [comment]
I use the program quertyGO for this feature - however I appreciate this add-on

**Comment by mpogue2** [comment]
QwertyGo is a very cool program...What mode do you use for the keys that you use for triggers?  (There are several modes that you can select, and I want our sound FX to use the "most commonly used" mode...)  Thanks!

**Comment by mhkull** [comment]
I am not quite sure what you mean. I use the german keyboard layout. 8 Channels, Sample Rate 44100, Audio buffer 512. Is that what you were asking?

**Comment by mpogue2** [comment]
I was really asking about how you trigger sounds using QwertyGo -- the setting of Play Mode in your Playback tab.  One option is to trigger immediately with a keypress.  Another is to trigger on keypress, and stop on second keypress.  Another is play while key is held down...

The quick sound FX option I just implemented is a one-time trigger.  It plays the whole sound when the keyboard shortcut is triggered.  You can't stop it at this time.  I was curious as to which mode you use in QwertyGo (and whether you ever use more than one mode, and if so, why?)...

**Comment by mpogue2** [comment]
One more note:  QwertyGo is a cool program (has lots of neat features!), but it's also US$39.  The new soundFX feature in SDP is not nearly as cool, but it's US$0 ! :-)

**Comment by mhkull** [comment]
Got it.

I use "trigger on keypress and stop on second keypress".

Here is how I use it:

1
"Happy Birthday" - It happens more than once, that during announcements they say "and now we sing to ..." and all I do is swipe to QuertyGo and press the key.
"Intro Sounds" - in order to get attention I have a tune opening announcements and closing ist.
And various other "special sounds" that I do not have to stop in between .... so they actually do not need the stop function.

2
"Applause", "drum roll" and other sounds I use need the stop function, because they are lengthy tunes in order to tailor them for the occasion on the fly I need the stop funtion.

3
"quak quak" "horse sounds" and other gimmicks I use to entertain the dancers are short - they do not need the stop mode.

These 3 uses demonstrate IMHO that the stop function is good to have but not necessary - However - if you press the wrong key, it is a great tool to stop it immediately :-)

Hope that answers the question.

**Comment by mpogue2** [comment]
Thanks, this is VERY helpful!  I'm not going to close this Issue, until we have implemented "trigger on keypress and stop on second keypress" (or something equivalent).

A related question:  I think SDP should provide some default sounds in the soundfx directory, maybe exactly the sounds you suggest:  HB2U, Applause, Drum Roll, Duck, Horse?  If you provide the complete list of what you use, I'll try to find those sounds....  There are many free and open source sounds available (I am testing with "whistle", "submarine horn", and "clown horn"), and it would be pretty simple to provide a set of these as default sounds.  Most (with the exception of HB2U) are pretty small, too.  And nowadays, Happy Birthday is freely usable, too! :-)

**Comment by mpogue2** [comment]
OK, I'm going to do this in three phases:
1) expand to 6 sound FX, and they must be named like "1.foobar.mp3".  The 1 will attach the sound effect to menu item 1 and key Cmd-1.  And, "foobar" will be the text in the menu item.
This was added by 1a7195ff60b09c157e8af4be07b7cc87d74ce22e .

2) I want to include a set of 6 miscellaneous sounds, that are auto-copied into the soundFX directory (if there are no sounds there already).  They are just a "starter set", and I expect people will replace them with what they want.  At the same time, should also copy a break_over.mp3 and long_tip.mp3 sound there, so they can be more easily replaced.

3) If the shortcut key is pressed a second time during playback, it should stop the current sound.  As @mhkull suggests, this is probably the most commonly needed form of "stop".

**Comment by mpogue2** [comment]
For the record, the default set of sounds are freely redistributable.  They are:
 ```
           "1.whistle.mp3",            // police whistle
            "2.clown_honk.mp3",  // honking horn
            "3.submarine.mp3",    // could be used with Load the Boat, maybe?
            "4.applause.mp3",       // some applause
            "5.fanfare.mp3",          // brass fanfare (for announcements)
            "6.fade.mp3"               // record winding down
```

**Comment by mpogue2** [comment]
Also, I'm not sure how Linux will be packaged, so the source dir for the starter set of sounds is a guess.  If the starter sounds are found, nothing gets copied.  If no suitable sounds are found in the soundfx directory, nothing gets played.  So, it should be safe to use on Linux (although we won't get all of the automatic setup features there).

**Comment by danlyke** [comment]
Yeah, I need to dive back into Linux packaging for a couple of other
issues of where resource files live. I'll fight that battle in a while.

**Comment by mpogue2** [comment]
No rush...I just don't want to break the Linux build!
