### ISSUE TITLE
Feature: keyboard shortcuts for going to Music or Lyrics tabs

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#98]
Manual version of the "auto go to Lyrics tab, if lyrics available".  With a shortcut, you can go or not at anytime (from the keyboard).

**Comment by mpogue2** [comment]
What key to use?  Also, should this be a toggle (press once to go Music -> Lyrics, press again to go Lyrics -> Music)?

**Comment by mhkull** [comment]
SqView uses "T" for that. I like T(ext). And yes, pressing T again should take me back to music.

**Comment by mpogue2** [comment]
"T" sounds good to me.  If the current tab is neither the Music tab nor the Lyrics tab, should it go to the Music tab, or do nothing?

**Comment by mpogue2** [comment]
OK, in this commit, pressing "T" will toggle between Music and Lyrics tabs, and if the current tab is neither of those, it will go to the Music tab.  Let me know if this is expected behavior (the principle of Least Surprise applies! :-)....

Commit: 75ae49291f81faee676a95a6a1db7aaa8577e252 .

**Comment by mpogue2** [comment]
Closing, since this is implemented now.
